### ISSUE TITLE
Support for Remote Database Server

### ISSUE THREAD

**Issue by mrconnerton** [omega8cc/boa#1009]
I can't find a definitive answer on this. Some questions:

1. What is the current status of remote database servers with BOA 3.x?
2. Should we install it as another aegir server? Should we configure it in the octopus conf?
3. Assuming there is a solution to this, is it possible to migrate an existing sites database from the master server to the remote?

Thanks!

**Comment by memtkmcc** [comment]
There are no plans to support ordinary remote database servers, since it is already implemented as a part of db/web cluster support (with Galera for db heads). We still need to make it more generic, since current implementation is a result of custom work done some time ago, and thus is not documented, yet.

Related issue: https://github.com/omega8cc/boa/issues/502

**Comment by mrconnerton** [comment]
> We still need to make it more generic, since current implementation is a result of custom work done some time ago, and thus is not documented, yet.

Are you referring to omega8cc specific implementations or boa as a project? Should I leave a comment on #502 looking to see if anyone has any more details on setting up a remote db?

**Comment by memtkmcc** [comment]
It is implemented in BOA project since 2014, just not documented, only mentioned, because it is still not generic enough to qualify as supported feature. Yes, please follow up on #502, if needed.
