### ISSUE TITLE
Drupal contrib - Highly Critical - Remote code execution PSA-2016-001

### ISSUE THREAD

**Issue by Pls** [omega8cc/boa#1025]
As we know today highly critical security release for drupal contrib module will be released. Maby BOA plans to patch this module instantly using Skynet?

I remember this happened instantly on Drupalgeddon and BOA users got secure. Wondering if we will do the same thing today.

**Comment by omega8cc** [comment]
In the past it was about Drupal core, and the patch was extremely simple. We will **not** patch any contrib module. There is no way to ensure it's effective, since the problem affects more than one contrib module, people use different versions, perhaps patched for other reasons, so we can't blindly patch them all. The patch could fail for many reasons, like version incompatibility or other patches applied before, etc. So, no, there are no plans to patch anything, at last for now.

**Remember: You should not rely on BOA for hosted codebase security / protection**.

Obviously we can't discuss details before they will be published on drupal.org, but we will do our best to check, if there is anything BOA could do to mitigate the vulnerabilities. It's even possible that BOA default configuration already mitigates them. Who knows? We don't have any prior knowledge.

**Comment by Pls** [comment]
Great, good to know. Let's wait then for more details when all info will be released.

**Comment by Pls** [comment]
Ok, so it's three modules are affected - RESTWS, Coder, Webform Multiple File Upload: https://www.drupal.org/psa-2016-001

As it's critical level of security risk I think that overall it has pretty low usage. Anyway, let's update.

**Comment by omega8cc** [comment]
BOA and vanilla Aegir running Nginx is not affected by Coder vulnerability: SA-CONTRIB-2016-039 http://bit.ly/29C5Ujw

**Comment by omega8cc** [comment]
BOA will temporarily disable `webform_multifile` and `restws` if enabled in any hosted site during daily autonomous maintenance.

If you are using any of those two, upgrade first and then add them to `_MODULES_SKIP` in `.barracuda.cnf`

**Comment by omega8cc** [comment]
We have removed the temporarily added logic to disable these two modules. Sites owners who use them, should update before enabling them again. We could think about a method to check module version and disable it again, if not updated, though.
