### ISSUE TITLE
Add UTF8MB4 Convert Drush extension

### ISSUE THREAD

**Issue by omega8cc** [omega8cc/boa#1047]
The [UTF8MB4 Convert](https://www.drupal.org/project/utf8mb4_convert) Drush extension, once confirmed as free of [catastrophic bugs](https://www.drupal.org/node/2781545), could be perhaps added by default.

Related issue #1020

**Comment by cvining** [comment]
Since upgrading to boa 3.1.3 all my sites report this warning in 'status report':

'Database 4 byte UTF-8 support	Enabled, but database tables need conversion'.

So what is the current best practice in handling this warning? I tried 'drush @none dl utf8mb4_convert-7.x' like the convert project recommends, but I get a 'Directory /home/o1.ftp/.drush exists, but is not writable. Please check directory permissions'

Hardly an emergency for me at present as I don't really need 4 byte UTF-8 support. I can wait until this is all fully supported. Just wondering what the current best practice might be.

my latest 'boa info' output:
https://gist.github.com/cvining/4fb5bff4c6f9df4866e8310f4957d4ac

Again, thanks for all the fish!

-- Cronin

**Comment by memtkmcc** [comment]
> I don't really need 4 byte UTF-8 support.

Then ignore these Drupal core stupid warnings. No idea how anyone found them useful to put there.

Normally you don't announce new feature via warning on the status page.

Aegir supports this new feature, but converting existing sites is beyond the scope of the project.

You need to figure it out, if you want to use it.

**Comment by dnotes** [comment]
To me this one is a little more than a new feature, since mysql's utf-8 implementation has led to several security vulnerabilities, a few of which are listed on [this page](https://mathiasbynens.be/notes/mysql-utf8mb4). Therefore even though I have no need for the 4-byte characters, I will be switching as soon as I can. However, I'm all for making sure the drush extension is safe before including it in boa.

**Comment by omega8cc** [comment]
I couldn't find any vulnerability related to Drupal there. If there was any, we should assume that basically all Drupal sites in the world are easy to hack, which is not the case, I think?

**Comment by kopeboy** [comment]
I cannot write in .drush folder, how to use the UTF8MB4 Convert Drush extension so that I can convert my databases and enable emoji on my Omega8 sites?

**Comment by omega8cc** [comment]
You can't and shouldn't use custom extension before it is officially supported, because it will be wiped out during upgrades.

Of course you could try, but then you are on your own :)

Hint: you need to unlock the write permissions first (as root) with `chattr -i -R .drush`

**Comment by EdNett** [comment]
>Hi,

Is there any update on this? 

Best regards,

Ed

**Comment by omega8cc** [comment]
Not yet.

**Comment by jfayad** [comment]
What kind of progress shall we be looking at to "forecast" a GO on this ?

On another website hosted on the client's server, we needed to convert the DB to mb4 support because some YouTube videos included emojis in their title and we couldn't add them to the website if the DB wasn't converted. We used the utf8mb4_convert drush extension on it and it worked very well (on more than 300 tables).

@omega8cc it's not very clear what is the green light you are waiting in here ? Community confirming you that it has worked elsewhere ? or you want to review the code of this project ?

**Comment by omega8cc** [comment]
@jfayad -- If the status is "postponed", it means that we can't yet associate the issue with some upcoming release/milestone, because there are higher priority issues/tasks to complete first.

**Comment by angel0d** [comment]
maybe not exactly the same issue but relevant

for those who needed utf8mb4 support and have already converted their databases/tables please note that daily backups as taken right now do not properly export those emojis so you will need to take extra backups yourselves

you will need to use `--default-character-set=utf8mb4` to create proper backups

All together something like `ionice -c3 nice -n19 mysqldump --default-character-set=utf8mb4 --single-transaction --quick --no-autocommit --skip-add-locks --hex-blob YOUR_DB_NAME | bzip2 -c YOUR_BACKUP_FILE.sql.bz2`

@omega8cc could/should this be a separate issue ?

**Comment by angel0d** [comment]
note for anyone following this issue and having already converted a DB to utf8mb4

you have to use custom sql config for mysqldump - for example in /etc/mysql/my.cnf so that it is respected globally by mysqldump. add a new line so that the mysqldump section looks like

```
[mysqldump]
quick
default-character-set   = utf8mb4
max_allowed_packet      = 32M
quote-names
```

and also instruct boa to not override it with `_CUSTOM_CONFIG_SQL=YES` in `.barracuda,cnf`

**Comment by omega8cc** [comment]
We should switch the mysql default configuration and connections to utf8mb4, since it's backward compatible anyway.

**Comment by omega8cc** [comment]
The `utf8mb4_convert` is already used in BOA and available both on command line and used automatically to convert hostmaster database, because otherwise it won't work with Drupal 9 core.
