### ISSUE TITLE
race conditions on barracuda and octopus up-stable for dedicated servers with software RAID

### ISSUE THREAD

**Issue by EdNett** [omega8cc/boa#1055]
Hello,

This is a dedicated server 4 cores, 32 GB ram, with a software RAID mirror - a very common setup for production servers. I know that since the wheezy to jessie upgrade disasters, you now do not suppor this setup anymore. I ask you to take this bug report seriously, however, because many, many BOA users are still going to use a dedicated server with a software RAID - because: a) that is the best financial offering in the marketplace, and b) we/they have had such dedicated server (with a software RAID and without virtualization) for many years, and have NO INTENTION of giving it up!

after a barracuda up-stable for 3.1.2,  in which , when downloading drush mini (at the very beginning of the up-stable), I saw the load (I was running top on a separate terminal)
 speed up to over 201! (1 min) and over 45 for the 5 min! - I believe you call this "race conditions"?

Then at the end of a successful barracuda up-stable (I believe it was successful), I saw that the load (on a powerful dedicated server with 4 CPUs and 32 GB of ram, 12GB of which are never used, WAS ONLY 0.61, so I ran "octopus up-stable o1 both" and got this result immediately:

BOA [16:59:42] ==> UPGRADE B: Aegir automated install script part B
BOA [16:59:42] ==> UPGRADE B: Creating directories with correct permissions
BOA [16:59:42] ==> UPGRADE B: Running standard installer
BOA [16:59:42] ==> UPGRADE B: Downloading drush micro-8-23-07-2016...
BOA [16:59:44] ==> UPGRADE B: Installing Aegir Provision backend...
BOA [16:59:44] ==> UPGRADE B: Downloading Drush and Provision extensions...
load on system too heavy (51.61 11.99 5.49), aborting               [error]
Drush command terminated abnormally due to an unrecoverable error.  [error]
BOA [16:59:45] ==> UPGRADE B: FATAL ERROR: Drush is broken (/opt/php56/bin/php /data/disk/o1/tools/drush/drush.php help failed)
BOA [16:59:45] ==> UPGRADE B: FATAL ERROR: Aborting AegirSetupB installer NOW!
BOA [16:59:45] ==> UPGRADE A: FATAL ERROR: AegirSetupB installer failed
BOA [16:59:45] ==> UPGRADE A: FATAL ERROR: Aborting AegirSetupA installer NOW!
BOA [16:59:45] ==> FATAL ERROR: AegirSetupA installer failed
BOA [16:59:45] ==> FATAL ERROR: Aborting Octopus installer NOW!

So, my question to you is - what is it about downloading drush mini that causes these race conditions on dedicated servers with a software RAID (mirror, of course) - and can you modify the BOA.sh script so that this does not happen?

I appreciate your help.
Regards,

Ed

BOA info more here:
https://gist.github.com/EdNett/a1bbcb1c74542ae38e54e448214e5bf4

**Comment by omega8cc** [comment]
This has nothing to do with BOA, I'm afraid. Also, this is precisely why we no longer support running BOA on bare metal, under no circumstances, and without exceptions. It is your hardware problem, not BOA problem, so there is literally nothing we can to do help you. By the way, we have the usage stats, and we know that almost all BOA users don't use this type of hardware configuration, so your suggestion that "many, many BOA users are still going to use a dedicated server with a software RAID" is just a perspective error, and you should avoid telling us what we should do, just because you want something which meets your very specific perferences. I'm sorry, but this is not how the things work.
