### ISSUE TITLE
Redirect module breaks Drupal 8 sites in BOA if present

### ISSUE THREAD

**Issue by florisvanwoudenberg** [omega8cc/boa#1061]
What are the best practices to install a custom Drupal 8 platform? Are there any caveats?
Is there a recommended workflow (we currently use a files based workflow without the use of configuration manager)
I tried to migrate one of our Drupal 8 projects to a Barracuda server, without any succes. The site is installed, though I had to manually add a profiles directory, but after drush sqlc database, I get a lot of entity-updates, removing most of the fields.

**Comment by omega8cc** [comment]
General advice is to use the directory structure as provided by vanilla tarball you can download from drupal.org.

Just add it as a custom platform in ~/static and you will be able to install/migrate/clone D8 sites with zero issues.

Custom builds/platforms created with drupal-composer don't work at the moment.

Some related issues/reports:

https://github.com/omega8cc/boa/issues/525#issuecomment-243151831
https://www.drupal.org/node/2736801

**Comment by chrisarcherhydrant** [comment]
Hi,

Whats the state of custom Drupal 8 install profiles  I have been having issues getting one to install.  I have managed to add the platform under /static and install the site. But I keep getting a redirection loop.  Any ideas?

I have posted the issue on: https://www.drupal.org/node/2877619#comment-12086457

Thanks,
Chris

**Comment by memtkmcc** [comment]
@chrisarcherhydrant Are you using https://www.drupal.org/project/redirect module in your D8 codebase / site?

Custom D8 platforms should just work, if your installation profile has all required code and the codebase structure follows traditional Drupal directory structure ( we still don't support the `web/` subdir structure ).

**Comment by chrisarcherhydrant** [comment]
Hi @memtkmcc 

Yes the module is there in code but not installed.  If I remove the module from code all works fine.  Which is odd, testing locally on Dev Desktop it works fine.

Thanks,
Chris

**Comment by memtkmcc** [comment]
@chrisarcherhydrant Interesting, I have seen one similar support request in our queue at https://aegir.happyfox.com so there is something to investigate about this module in the BOA context, perhaps.

**Comment by chrisarcherhydrant** [comment]
Yeah that is odd, I wonder if its the way they store aliases in the db?

**Comment by maestrojed** [comment]
I am experiencing this issue. I am an Omega8 customer and may be the request @memtkmcc mentioned above. I am happy to answer any questions about my experience or provide any debug info. I have a very vanilla D8 site set up that reproduces this issue. 

I did want to comment on:
> Yeah that is odd, I wonder if its the way they store aliases in the db?

I didn't have any aliases in my database and this issue manifested.  I created some aliases (on a version of the site not running on BOA) and tested that on BOA. This issue persisted. The issue seems to exist regardless of none or any aliases in the database table.

The redirect module for D8 does more than redirects/url aliases. It also replaces the Global Redirect module from D7. This feature forwards all system paths like /node/### to their prettier URLs. It could be this aspect of the module or some other new D8 feature causing the issue.

**Comment by omega8cc** [comment]
It seems that we have hijacked unrelated issue.. Can we move this discussion on redirect module apparent problems to a separate issue, please?

**Comment by omega8cc** [comment]
We could also rename this issue to make it redirect D8 module related, and use #1116 to follow up on the original topic?

**Comment by omega8cc** [comment]
OK, let's continue the "Best practice for installing custom Drupal 8 platform" related discussion on #1116

**Comment by omega8cc** [comment]
The weird part here (if confirmed) is actually this:

> Yes the module is there in code but not installed. If I remove the module from code all works fine.

**Comment by maestrojed** [comment]
Thanks for the organizing the threads. Sorry for the confusion. 

> The weird part here (if confirmed) is actually this:
> > Yes the module is there in code but not installed. If I remove the module from code all works fine.

I did not experience this. I was able to uninstall the module (via drush) and the issue resolved. The redirect module is still present as part of my profile.

**Comment by cwaone** [comment]
I have also a problem with the Redirect Module on Drupal 8.

After activating the Module  the Site ends up in an endless loop while redirecting q=/?q=/?q=/... - i need to uninstall it via drush and all is good. I´ve tried it with real url and site redirection via the aegir ui, also without of course, with xml sitemap module enabled and without. Clean install or existing site. 

i´ve added the drupal 8 platform in static folder as described in the howtows.

Drupal Version 8.3.2 - Redirect Module Tried the actual alpha and dev.

Are there any news on this?

Thanks,

Michael

**Comment by tourtools** [comment]
Same here, I did install It because on a non boa server gave no problems.
I did have to uninstall It and deactivate redis for this site, to go back to a normal situation (redis on  a per domain basis It's really aggressive :D)

**Comment by omega8cc** [comment]
No progress yet, sorry. We are too busy with everything which is expected to be included in the next feature release.

**Comment by cwaone** [comment]
ok, thanks for your replay. 

Michael

**Comment by serhatozkara** [comment]
I found out the issue. If you enable "Enforce clean and canonical URLs." option from redirect settings, the site gets stuck in a redirect loop. The culprit was, Drupal 8 was utilizing line 1005 of nginx_vhost_common.conf  "rewrite ^/(.*)$ /index.php?q=$1 last;" which is intended for Drupal 6.
I simply changed the line with "rewrite ^ /index.php?$query_string last;" which is intended for Drupal 7 & above. It seems there is a problem with drupal version detection.

**Comment by yaazkal** [comment]
Hi, I can confirm:

1. Site works after the module is uninstalled (via drush) and the issue is no present just if the files are there.
2. Is true that the feature that is causing the issue is _Enforce clean and canonical URLs_.

The **good news** is that there is a way you can make it work and also disable that option without messing with config files: Before enabling the module put the site in _maintenance mode_, enable the module and you see that there is no redirection loop (just because the module actually has no effect on maintenance mode), then go to the module configuration at `admin/config/search/redirect/settings` and unckeck _Enforce clean and canonical URLs_ save and you can now disable maintenance mode safetly and will no experience the loop.

The **bad news** (depends on your needs) is that without _Enforce clean and canonical URLs_ you can see the same content using /node/1 or /beuaty-path-to-node-1.html wich I think is bad for SEO.

Now, I think it should be changes from the BOA side because `?q=` is still present at the end of the url.

### Extra info
I'll try to be more clear with my scenario:

The main reason I'm using redirect module is because I also use pathauto, so, if there is a path update (because the title has changed, for example) I want to redirect from the old path to the new path. And this can work without the _Enforce clean and canonical URLs_.

So, consider this path pattern for entities of type products (using commerce module): `products/[commerce_product:title].html`

If I add a product with title "Product 1", pathauto will generate `example.com/products/product-1.html`
If I change the product title to "Product 1 with changes" pathauto will set the path to `/products/product-1-changes.html` (the word "with" is eliminated per pathauto config) and then the system will create a redirection from `/products/product-1.html` to `/products/product-1-changes.html` to prevent a 404 error if a visitor goes to the old path.

Now, if I go to `/products/product-1.html` I get correctly redirected to the new path, but I end with a url like `/products/product-1-changes.html?q=products/product-1.html`, this could be not a big deal (maybe yes for SEO) but for sure is not desired.

If I found more things I'll share. But at least you can use redirect on your site (with some caveats for now).

**Comment by omega8cc** [comment]
This commit should fix the problem: https://github.com/omega8cc/provision/commit/a36d8ca7a27450d5e4134f5baf6ce75e32b280e5

Thanks all for the feedback!
