### ISSUE TITLE
Mongo installation clarification

### ISSUE THREAD

**Issue by MetaBureau** [omega8cc/boa#1062]
Having upgraded my system and added Mongo (barracuda.cnf from "No" to "Yes") I can see that mongo PHP extension is installed.

BUT is Mongo itself installed? Commands such as service mongo start, mongo, mongo, mongdb are all fruitless and this suggests that perhaps Mongo itself isn't installed.

So do I need to manually install Mongo?

**Comment by MetaBureau** [comment]
LOL that is indeed what I had to do. Sorry but maybe this will help someone else.
Do this (https://docs.mongodb.com/manual/tutorial/install-mongodb-on-debian/) AS WELL as enable the PHP extension.

**Comment by omega8cc** [comment]
MongoDB support in BOA is not intended to include MongoDB server, only the PHP driver, usually for remote MongoDB server access. You can install it locally, if you wish, but it is not supported (no service auto-healing, etc)

**Comment by MetaBureau** [comment]
Do you think delegating watchdog, cache and session to Mongo is worthwhile within the BOA context?

**Comment by omega8cc** [comment]
A waste of time. You would add another thing, totally redundant, because:

1. You have much faster and reliable Redis server for caching
2. You should not enable dblog/watchdog on any production site
3. For non-production sites standard dblog/watchdog in SQL is just fine
4. For sessions you want stable backend and not extra daemon with no auto-healing
