### ISSUE TITLE
system file /bin/sh is modified TWICE after every upgrade

### ISSUE THREAD

**Issue by dnotes** [omega8cc/boa#1066]
Whenever I upgrade my BOA Aegir servers, using `barracuda up-stable` with or without the `system` at the end, I get a long list of modified files detected, among which is /bin/sh. It seems only natural that files would be changed during upgrades, so I have never worried about this.

Then, an hour later, I get **another** notification of modified files, generally just /bin/sh, though as I recall there was a time when I would see /bin/websh in that list as well. I'd like to confirm that this is expected behavior, and to know why it happens. 

BOA Info (for one of my servers, though this happens on all of them) is [here](https://gist.github.com/dnotes/3c53f33ba7e9c60acd946ebf1361aa57) and host is DigitalOcean. Thanks!

**Comment by omega8cc** [comment]
It is normal, because during the upgrade barracuda will switch /bin/sh to point it to bash or dash, so /bin/websh doesn't break builds etc. Then, once the upgrade is complete, [manage_ltd_users.sh will switch /bin/sh back to /bin/websh](https://github.com/omega8cc/boa/blob/master/aegir/tools/system/manage_ltd_users.sh#L2011), as soon as possible, so normal production settings are active again.

**Comment by dnotes** [comment]
Thanks! I thought it was probably working as intended. I appreciate the
explanation.
