### ISSUE TITLE
`letsencrypt` is now `dehydrated`

### ISSUE THREAD

**Issue by macmladen** [omega8cc/boa#1074]
Due to copyright issues, on September 13th, the project had to be renamed so now it is called [dehydrated](https://github.com/lukas2511/dehydrated)

> Note: This project was renamed from letsencrypt.sh because the original name was violating Let's Encrypts trademark policy. I know that this results in quite a lot of installations failing but I didn't have a choice...
> For now there is a wrapper script for compatibility with old config locations and symlinks, but it will be removed in a few weeks.

**Comment by angel0d** [comment]
i am not if it suitable but another candidate could be

https://certbot.eff.org/#debianjessie-nginx

I used the other day on a mail server and it seemed pretty simple.

renewing in that case is a single command

`certbot renew --pre-hook "service nginx stop" --post-hook "service nginx start"`

**Comment by omega8cc** [comment]
There are no plans to use `certbot`. Also Aegir upstream new [hosting_https](https://gitlab.com/aegir/hosting_https) module depends on `dehydrated`. We will change the name of the script used in BOA, when we will have time to implement the upgrade procedure so it doesn't affect other users of `hosting_le` module and will not break things because of some changes `dehydrated` implemented in the meantime (because it doesn't care much about backward compatibility).

For some context please check: https://gitlab.com/aegir/hosting_https/issues/9

**Comment by omega8cc** [comment]
This has been done already in head.
