### ISSUE TITLE
You yourself checked Installer work in a clean system (debian-8.0.0-amd64-netinst)?

### ISSUE THREAD

**Issue by omega8ccboa** [omega8cc/boa#1082]
good afternoon

Where can I find detailed instructions?

https://github.com/omega8cc/boa/blob/master/docs/INSTALL.тхт
Instruction is still relevant?

Two days trying to set a boa on Debian 8.0 (netinstall) virtualbox host windows 10.

While it is impossible, all the time any problems.

Maybe it's in the version "debian-8.0.0-amd64-netinst"?

You yourself checked Installer work in a clean system?

Do you plan to upgrade the video guide?

translate.google

**Comment by omega8cc** [comment]
Please change your username. It is unacceptable to use our TM username and BOA name as your username!

**Comment by omega8ccboa** [comment]
How can I change?

**Comment by omega8cc** [comment]
Please go to https://github.com/settings/admin and change your username to something unique, not related to omega8cc and boa.

As for the issue, it has been closed because if you follow the docs, it just works. Hundreds of people use it for years. Try to debug this after following the docs to the letter.

That said, we don't recommend localhost installs these days, if you are not familiar with BOA yet. It was discussed in the issues queue in the past,

The best way to test BOA is to get VPS at Linode or DigitalOcean.

**Comment by omega8ccboa** [comment]
Well, just as soon as the setting "boa"
