### ISSUE TITLE
Dirty Cow BUG fix?

### ISSUE THREAD

**Issue by EdNett** [omega8cc/boa#1084]
Hello, Are you planning to update the kernel to fix the dirty cow bug? Can we go directly to a 3.16.x kernel, instead of a 3.2.x kernel?

See https://security-tracker.debian.org/tracker/CVE-2016-5195

Best regards,

Ed

**Comment by omega8cc** [comment]
BOA doesn't manage your system kernel, but it will update it during standard barracuda upgrade, if the OS distro provides new version, and will ask you to reboot afterwards.

As for the kernel version switch, don't do this on any dedicated box if you have not tested this on exactly the same box before, or if you can't safely manage the booting process via serial console, because hardware incompatibility may prevent the system from running different kernel.

Even on a VPS, make sure you don't mix 32-bit system with 64-bit kernel, or the other way around.
