### ISSUE TITLE
How to add LE redirect exception?

### ISSUE THREAD

**Issue by ixiam** [omega8cc/boa#1097]
We are using LE certs for our sites. When using **Required** to force https redirection, is there anyway to add exceptions to this redirection?

In our case an url for a payment proccesor callback, which doesn't support SNI certs, so we need to open a http exception for this url

add directives in local.settings.php seems to have conflict with the LE redirections. 
Where do we have to define these directives?

**Comment by omega8cc** [comment]
It is not possible, because this type of redirection is managed by Aegir backend, directly in the vhosts, and with multiple server {} blocks method, not via redirects within the same server {} block, so exceptions are not possible to inject there without hacking Aegir backend.

Your only option is to use Enabled instead of Required mode, and then possibly add selective HTTP->HTTPS redirects in the local.settings.php file.

**Comment by ixiam** [comment]
I've created a website with LE SSL Enabled, and in local.settings.php, I've added the force redirection to https, but the exception url

[https://gist.github.com/ixiam/d30c59ab835c81b2a22cd77ace364b2c](url)

The result it's I'm getting a browser error **This webpage has a redirect loop**

Is it local.settings.php incompatible with LE redirections?

**Comment by omega8cc** [comment]
This old code will not work, because we no longer use HTTPS proxy, with its extra headers etc. Instead we use standard HTTPS vhosts, so there is no proxy layer involved. This makes this detection a bit tricky, and the old method will indeed cause redirect loop, because it doesn't detect if the request is made via HTTPS or not. Hm...

**Comment by omega8cc** [comment]
Try to replace the first line with:

`
$request_type = ($_SERVER['SERVER_PORT'] == '443') ? 'SSL' : 'NONSSL';
`

**Comment by omega8cc** [comment]
Or:

`
$request_type = ($_SERVER['HTTPS'] == 'on') ? 'SSL' : 'NONSSL';
`

**Comment by ixiam** [comment]
@omega8cc yes, last line seems to work and does the correct redirection.

tx!

**Comment by omega8cc** [comment]
Great!
