### ISSUE TITLE
Problem with Installing Barracuda and Octopus on localhost

### ISSUE THREAD

**Issue by Yusadolat** [omega8cc/boa#1099]
Hello there, I'm Installing BOA system on localhost, and have Download and run BOA Meta Installer. When I tried Installing Barracuda and Octopus I got the below error . What am I getting wrong Please.?

ERROR: BOA requires minimal, supported OS, with no services installed
ERROR: The only acceptable exceptions are: sshd and mail servers
Bye

**Comment by omega8cc** [comment]
What is the "localhost" system / virtualization?

**Comment by Yusadolat** [comment]
Vagrant (Virtualbox)

**Comment by omega8cc** [comment]
Hello,

It should work if you are using some minimal OS image (without web server and mysql server installed).

However, the localhost based install is not supported currently, and is known to cause problems, depending on the virtualization and OS image used.

The localhost mode was never intended to be "production" ready, because BOA was never designed for local development. It was always designed to be used on servers.

We don't have a time nor resources to keep fixing the localhost mode to accommodate changes in software like Virtualbox and thus we recommend to install BOA in the standard mode on some small VPS instead.

We may revisit this from time to time, but it is not expected in the next few months.

**Comment by dev286** [comment]
I was able to install it as 'localhost' no problem.  
VirtualBox in OMV with Debian 8. 

Set it to static IP and add "XXX.XXX.XXX.XXX o1.sub.aegir.local yoursite.aegir.local etc." to your hosts file on your workstation. You'd need to do this to each workstation.

Install log has the one-time-path to get the password. Reset the password for your o1.ftp user.

**Comment by luxio** [comment]
I had also no problem installing BOA in localhost mode with [debian/jessie64](https://atlas.hashicorp.com/debian/boxes/jessie64) vagrant box.

**Comment by omega8cc** [comment]
Thanks for the confirmation. It is good to hear that it still works also on localhost!
