### ISSUE TITLE
403 Forbidden when nginx default server location is set to an aegir site root.

### ISSUE THREAD

**Issue by Corvalan** [omega8cc/boa#1112]
I need to have all domains with an a record pointing to my servers IP, to show one specific drupal website that I imported in aegir. 
The goal is to have all these domains show the same website (and then they are dynamically rewritten to show a landing pages in the site, but thats not the current question)

What I did to accomplish this is change the nginx.conf default server location in the file
/var/aegir/config/server_master/nginx.config/server_master/nginx.conf

Instead of:
     `root   /var/www/nginx-default;`
I made it:
    `root   /data/disk/o1/static/example;`

However, that returns the page '403 Forbidden - nginx'

The edited nginx.conf as mentioned above shows the following:

```
#######################################################
###  nginx default server
#######################################################

server {
  listen        *:80;
  server_name  _;
  location / {
    expires 99s;
    add_header Cache-Control "public, must-revalidate, proxy-revalidate";
    add_header X-Content-Type-Options nosniff;
    add_header X-XSS-Protection "1; mode=block";
    root  /data/disk/o1/static/example;
    index  index.html index.htm;
  }
}
```

What is the correct way to accomplish this setup so it works?

**Comment by omega8cc** [comment]
You can't add duplicate and working (with PHP, Db connections, and most of all, system permissions) server in the default (Barracuda) catch-all configuration. Impossible.

The only correct way is to add all those domains as aliases to your "default" site.

**Comment by angel0d** [comment]
@Corvalan 

I assume that you already have symlinked the sites/default folder to point to your drupal specific website sites/yourdrupal.site

the best you can do to avoid adding domains and/or their subdomains as aliases one by one is to add as server_name an (almost) catch all directive for top level domains like this

server_name   *.com *.net *.org *.etc;

at the bottom of : /data/disk/o1/config/server_master/nginx/vhost.d/yourdrupal.site

to make this change permanent and make sure it does not get lost when verifying the site you should add the following hook in one of you custom modules

<?php
  function yourcustommodule_provision_nginx_vhost_config($uri, $data) {
    $conf = array();
    // alter server_name for yourdrupal.site so as to catch all following TLDs
    if ( preg_match("/(yourdrupal)/i", $uri) ) {
      $conf[] = "";
      $conf[] = "server_name *.com *.net *.org *.etc;";
      $conf[] = "";
    }
    return $conf;
  }

for more info on the hook see : 

http://docs.aegirproject.org/en/3.x/extend/altering-behaviours/#injecting-into-site-vhosts

**Comment by angel0d** [comment]
@Corvalan note that you have to put the hook in a file with drush.inc as extension

like : yourcustommodule.drush.inc

also the module needs to be installed on you aegir satellite instance

**Comment by Corvalan** [comment]
@angel0d  Thank you, that is what I'm looking for! 
I will probably need to include any and all possible domains since the website sells domain names of all kinds and extensions, serving each domain on its own landing page in the same site.  So it will probably become:

server_name *;

I will check out if this works, thank you for your tip.

**Comment by angel0d** [comment]
@Corvalan I guess you use some API via which you register the domains

that API probably also answers the available extensions it has

you could then setup a cron to check for these extension, populate a var and use that var in the hook above

you should only trigger a verify job on your main site when the domains change

here the problem might be the separation of logic as you 'll have to implement the API again for the aegir satellite instance

internet suggests that there might be a serious performance issue for nginx to hash and store those super long directives in case it can support them

but if you must have a real catch all directive then 

`server_name *;` or `server_name *.*;` will not work

you will have to use `server_name _;`

and also delete the default server blocks that use the same server_name from both

`/data/disk/o1/config/server_master/nginx.conf` and `/var/aegir/config/server_master/nginx.conf`

I 'd suggest that you don't go this way as it has some unavoidable risks

(although I think the templates for those configs haven't change in this repo since 2013)

you will need to make sure that these two server blocks do not get re-enabled. if they do nginx will not start.

if you both of them immutable (`chattr +i`) then you might break updates or worse you will not receive any update without noticing

this might seem a risk to take but (unless you have SKYNET off) in any of next drupageddon you will miss the one update you will come to regret

there might be other workarounds you could probably use but that depends on how your service is setup

you could use `server_name www.*;` which I haven't tested but seems valid and create an A record only for www.yournewlypurchased.domain

but in that case I cannot think of a way you could redirect non www domains in the www version

**Comment by Corvalan** [comment]
@angel0d When I set a catch-all or wildcard in the server_name as you suggested, I always get a 404 page not found, and the URL redirects to 'example.com/install.php'

What I did in **/data/disk/o1/config/server_master/nginx/vhost.d/example.com** is
replace  
`server_name example.com www.example.com`
with
`server_name _;`

I also tried with server_name *.net *.org for testing out, but the same 404 error.
Each time after modifications of the configuration file I restarted nginx and tested with different domains that have their A record pointing to the BOA ip address.
I did not verify any site (in order to prevent any overwriting)

Am I missing something?

**Comment by angel0d** [comment]
@Corvalan 

1st line 1st comment

just symlink sites/default to your /sites/site.name

**Comment by biomassives** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  acmeideal@gmail.com
    Domain biomassiv.es has exceeded the max emails per hour (110/100 (110%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
------ The body of the message is 8260 characters long; only the first
------ 5000 or so are included here.
Received: from github-smtp2-ext3.iad.github.net ([192.30.252.194]:47065 helo=github-smtp2b-ext-cp1-prd.iad.github.net)
	by chi-server32.websitehostserver.net with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.87)
	(envelope-from <noreply@github.com>)
	id 1cWmiM-0032Yn-Lx
	for greg@biomassiv.es; Thu, 26 Jan 2017 10:15:58 -0600
Date: Tue, 24 Jan 2017 15:17:22 -0800
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1485299842;
	bh=3yzeypMrSNcpXGJ0+6n30MUr24l+hXPswF+6F5cHlqA=;
	h=From:Reply-To:To:Cc:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=lg9PylDNR5/ss9dP5mpxa2Gm2BrsrJgSJSIRwrj/X1ImyoOr2Y8xt4EXPeMK9sFz3
	 mFqmSUcMIAYaQ4Eh+iWV5Eua3GjFvpg1vqGN6BMJjB2Y0tzPEL0DMxMEtZhd9pFa+O
	 AqYgg2O4nx0Ror3Tp8SxGs9n3g1vjktB1+GjHHP4=

**Comment by Corvalan** [comment]
@angel0d  yes, symlink is workng. Thanks!
