### ISSUE TITLE
BOA server infrastructure questions 

### ISSUE THREAD

**Issue by Pieter-Lab** [omega8cc/boa#1136]
To Whom it may concern

We are currently looking at the following cloud server setup:
- Load Balancer
-- 2 Web servers: Both will be BOA
-- 1 Mysql Database sever

In your experience or according to your knowledge is their any red flags you can think of for having two BOA servers with the same site running under one load balancer. 
The BOA servers will be identical and have only one site. That one site on the two BOA boxes will connect to the one DB server.
It is a good idea to use BOA for this?

**Comment by angel0d** [comment]
@Pieter-Lab from very few tests and no production experience I think there are 3 things to consider for a setup like this

1) BOA and site crons

Running site cron in 1/2 web server should be enough. I guess that BOA crons could behave fine given that common DB is remote.

2) Redis cache

I think you should look into clustering Redis too or using 1 redis instance. I assume that you need more than 1 web servers because of having many authenticated users. I think it would be really dangerous to balance authenticated users and use a per server cache.

3) Site Files

Off course site files should be on a shared or synced folder. Or other alternatives like what s3fs module provides.

**Comment by omega8cc** [comment]
@Pieter-Lab What is the reason to use load balancer for 2 web heads with only 1 db head?

BOA comes with (unofficial) support for cluster setup, with multiple web heads and multiple db heads running as Galera master-master cluster, but it requires some custom setup for files sync between web heads and network configuration, which is not covered in BOA. Furthermore, it requires installing BOA in a special cluster mode, which installs different instances for the main web head, secondary web heads and all db heads.

It is quite complicated to make it right, and you should have really good reasons to even start thinking about cluster with BOA.

But I don't see any reason/advantage to run load balancer for not synced web heads and single db head. No to mention the issues @angel0d pointed out. Why not to use one bigger/faster machine with just single BOA system? You will still have the single point of failure, but without all the mess inevitable when you try to configure the 2web+1db system.

**Comment by Pieter-Lab** [comment]
@omega8cc 

Thanks for the reply.
Do you have a link for me to the documentation you used for "BOA comes with (unofficial) support for cluster setup"?

**Comment by omega8cc** [comment]
@Pieter-Lab It's totally undocumented and not ready for general consumption, but here the discussion about making this happen at some point: https://github.com/omega8cc/boa/issues/502

**Comment by omega8cc** [comment]
Please check: https://github.com/omega8cc/boa/blob/master/docs/CLUSTER.txt
