### ISSUE TITLE
[hosting] cron runs even when set to disabled at site level

### ISSUE THREAD

**Issue by pricejn2** [omega8cc/boa#1145]
If I create a new site and set cron to disabled on install, then cron never executes. However, if I ever change it to enabled (the interval doesn't matter) and then re-disable, it will continue to run at the octopus default interval (24 hours). 

Steps to duplicate:

1. create a new site with cron disabled
2. during install, cron is not executed: last_cron = 1969-12-31 19:00:00
3. change cron to 5 min interval and verify, cron is executed: last_cron = 2017-04-13 11:26:33
4. change cron to disabled and verify: cron_interval = 0
5. wait 24 hours, cron is executed: last_cron = 2017-04-14 11:27:03

I believe this is upstream. Currently running BOA 3.2.0 on Debian Jessie.

**Comment by omega8cc** [comment]
Thanks for the report.

It is not upstream, because BOA comes with Aegir core cron module replaced with `hosting_advanced_cron`, originally from https://www.drupal.org/project/hosting_advanced_cron and later greatly improved: https://github.com/omega8cc/hosting_advanced_cron

So it executes site's cron, even if Aegir displays it as disabled? Definitely a bug.

**Comment by pricejn2** [comment]
That's correct. When cron is set to disabled, after enabling at least once in the past, it shows as disabled in Aegir. Yet, Aegir will still display last cron runtime of less than 24 hours ago. The site itself also logs cron as having been executed.

**Comment by omega8cc** [comment]
This old issue has been fixed with this patch https://github.com/omega8cc/hosting/commit/8289b907ac64a1fa19f314b8c9a8d5bbc83d83db
