### ISSUE TITLE
Can't run update.php because Database 4 byte UTF-8 support is enabled but tables need conversion

### ISSUE THREAD

**Issue by kopeboy** [omega8cc/boa#1148]
I don't remember how I enabled UTF8MB4, and it's weird because I can't edit settings.php not even using utf8mb4_convert module (I'm hosted by omega8.cc), but now I get this error and I can't run update.php.

What should I check that I might edited that is causing the problem and restore to default?

Thanks 

![screen shot 2017-04-16 at 18 33 37](https://cloud.githubusercontent.com/assets/4728367/25072607/4009f956-22d3-11e7-959f-0ef934b61904.png)

**Comment by omega8cc** [comment]
Please don't try to run `/update.php`

If you really want to run db updates manually (they are run for you automatically when you follow Aegir best practices), the use either Drush on command line or the Update task in Aegir.

**Comment by omega8cc** [comment]
Aegir enables utf8mb4 support if the database supports it, to make it possible to get it active when you create new sites, and to make it possible to support conversion of existing sites, if possible. But we don't convert existing sites, because it is too dangerous to do it automatically.

It is the Drupal core which causes confusion showing a warning.

Please just ignore this, if you don't need this feature.

We will include the Drush extension to help with converting existing sites, once it is safe to use.

You can watch the progress at: https://github.com/omega8cc/boa/issues/1047
