### ISSUE TITLE
barracuda up-stable upgrade MariaDB

### ISSUE THREAD

**Issue by DominicBoettger** [omega8cc/boa#1167]
Hello,

i have a central MariaDB instance and want to test the barracuda system upgrade. Now i am asking myself if the barracuda upgrade does any modifications on the hosted website databases. I want to ensure that i can check the system upgrade and after it was successfully i switch the boa host to the upgraded one. During the upgrade or if the upgrade fails the websites should run on the original server.

Does the upgrade any modifications on the database? My Aegir database is locally and only the databases of the websites are hosted on the central MariaDB.

Thanks a lot

Dominic

**Comment by angel0d** [comment]
@DominicBoettger hi

AFAIK no BOA update itself runs any DB updates on hosted sites unless there is something very special released. I think if there is any such future case it will be noted in the release notes

on the other hand though new cron(s) might be added on a BOA update that do run very frequently and perform routine check and changes on hosted sites

I am not sure which would be the best way to configure cron (if possible) to avoid headaches

even you stopped cron before running the upgrade because BOA stops cron on an upgrade and starts it after

regarding the aegir(s)

`barracuda up-stable system` does not update any
`barracuda up-stable` asks you if you want to upgrade the master aegir instance
`octopus up-stable all both` upgrades the satellite aegir instance(s)

**Comment by omega8cc** [comment]
@DominicBoettger What you mean by local/central db server?

Both barracuda up-stable and up-head will upgrade db server, if there is new Debian package already available. We can't release new BOA just because there is new MariaDB or new PHP or whatever else, so we don't limit this in any way.

We do plan to add feature to run even daily packages-only auto-upgrades via barracuda, if they don't require config updates, which would trigger full barracuda upgrade procedure if the package needs more attention to be aware of its BOA context.

**Comment by DominicBoettger** [comment]
I am using Amazon RDS and i am pretty sure that BOA will not upgrade the Amazon database ;-). The question was about the data in the database. If there will be any modifications of the site databases during a upgrade of BOA.

**Comment by omega8cc** [comment]
OK. BOA upgrades never touch your databases directly, in any way. Only if you run db server managed by BOA, its packages upgrade procedures we don't control may modify your databases tables (schema) to make them up to date.

**Comment by DominicBoettger** [comment]
Thank you for the clarification
