### ISSUE TITLE
Query re best practices re updating software between BOA stable releases?

### ISSUE THREAD

**Issue by EdNett** [omega8cc/boa#1169]
Hello,

What are BOA users doing re the fact that there are now about 150 jessie package updates to be made since 3.2.0 stable was released. This seems to be too many to update by running another 3.2.0 up-stable? OR am I wrong?  

What is suggested best practice:

1)  Wait until next stable release of BOA is issued and let the up-stable handle all upgrades (could be well over 200 in some cases!)  . If this is suggested, what about security updates?

OR

Periodically run an up-stable (weekly, for example, or whenever a piece of software has an update ..) so that there are never, at any one point in time, more than 20 or 30 upgrades for aptitude to do?

Thanks for all feedback on how users/testers are successfully using BOA.

Best regards,

Ed

**Comment by tourtools** [comment]
For me is the second workflow, if there are urgency=high upgrades I ran an "up-stable system", but if there are only upgrades with urgency=medium and below I wait until there's time to do it (however never more than 1-2 weeks from the notification).

**Comment by omega8cc** [comment]
We are working on a new quick-packages-only upgrade mode, which will be safe to run at any time, and barracuda will detect if there are any packages requiring full upgrade, but will allow to use the quick upgrade mode if none of the pending upgrade packages could affect otherwise modified config files. In the meantime, if the previous BOA stable was released more than 1 month ago, we recommend to run barracuda head upgrades -- we use barracuda head in production, se we do everything we can to never break it (even if it is not officially recommended). We aim to find a better way to keep the systems always up to date without waiting for BOA stable releases, which should be reserved for new features, new Aegir versions, or new Drupal core releases.

**Comment by yaazkal** [comment]
I also run `up-stable system` and never use head in production even that I know it could be safe to use (like a personal capricho) (capricho = whim).

But I wish if @omega8cc team will like to use the last digit of the BOA version to include simple patches or system upgrades they actually made to head, like upgrading core and platforms to a more recent versions but just for security versions, it will be like implementing [semantic versioning](http://semver.org).
So, if there is a Views security update (a module that aegir hostmaster use) we can just grab a BOA 3.2.1 using up-stable, and if there is a Drupal 7 security update (the core that hostmaster use) we can use BOA 3.2.2 using up-stable and so on for system updates (like nginx, mariadb, etc) and that will give us such a peace in our souls.

But is just a proposal and I don't know if that fits on their development/maintenance workflow (imagine BOA 3.2.87). It could be a "simple" (lazy) solution meanwhile but maybe it can take time and unnecesary server load (I guess that up-stable will make BOA to update and rebuild all things just for a simple fix).

**Comment by omega8cc** [comment]
@yaazkal -- We have already used semantic versioning for years (with rare exceptions). The problem we face at the moment is that because of running Barracuda head plus Octopus stable in production, plus some clients priorities, we have added (almost complete) cluster support in head, while some issues and features in Aegir we depend on for next feature release were still in progress, and partially delayed. This effectively blocked releasing anything in the 3.2.x series. We are still planning the future-proof workflow for both Barracuda and Octopus releases, so we don't get blocked again. That said, its not feasible to release new BOA for every component related update, so we need to find a sane middle ground.

**Comment by yaazkal** [comment]
@omega8cc thanks for the info.

So you are suggesting that running `barracuda up-head` and `octopus up-stable` commands will be ok on production enviroments at this moment in order to stay up to date as the OP ask?

**Comment by omega8cc** [comment]
@yaazkal Yes, but only `barracuda up-head`. It doesn't make sense to run `octopus up-stable`, unless you want to reinstall already auto-deleted built-in platforms/distros. That said, HEAD *can* be broken in an unexpected ways, so it is not recommended unless you are prepared to detect and fix possible problems.

**Comment by yaazkal** [comment]
@omega8cc great, thanks so much for the info.
