### ISSUE TITLE
A proper way to re-enable TLSv1

### ISSUE THREAD

**Issue by zanami** [omega8cc/boa#1171]
I have a site with about 10% of users running Windows XP, Vista, Windows 7 and other outdated systems and browsers. They complain a lot. I'm looking for an easy way to make things a little less restrictive by re-enabling TLSv1 (I believe it resolves IE 8-10 / Win 7  Server closed connection).

It's currently suggested by Mozilla's "intermediate" config and it's used at Cloudflare.

What's the best way to do it? I don't mind if it's a server-wide option, I believe other sites also suffer from this problem. What are the possible drawbacks if any? I don't really care about security, it's just a regular site and SSL is there mostly to please Google and the site owner who wants that green little lock.

Also if there's a way to detect and redirect that "old browsers" to a non-https version of the site it would solve all my problems.

**Comment by omega8cc** [comment]
It's not possible to redirect from not working https to woking http, because the redirect would work only when the browser can access https w/o issues.

There are a few places in the configuration which would have to be adjusted, but you can start with adding `TLSv1` to `ssl_protocols` line in the `/var/aegir/config/server_master/nginx.conf` file and reload nginx with `service nginx reload`.

Note that it will be overwritten the next time you will run barracuda upgrade.
