### ISSUE TITLE
Ownership of .po files in static/platform/sites/all/translations ?

### ISSUE THREAD

**Issue by EdNett** [omega8cc/boa#1181]
Hi,

We have some multilingual sites on BOA stable 3.2.0 which have trouble updating localization files in static/platform/sites/all/translations using l10n_update. Some of the translations/localizations are updated, and some aren't. For the ones that aren't, the error is that they can't be saved.  I have seen that for the files that could be saved, and thus WERE updated, they are owned by o1.web  (122:100) and the files that couldn't be updated are owned by o1 (121:100).  Both have group ownership set as 100, even though in /etc/passwd o1.web shows (122:33).  Sometimes we try to update translations via drush as the o1.ftp user (which procedure often doesn't recognize that there are updates when in fact there are), sometimes via the site admin area (which always recognizes that there are updates when there are).

Are the  .po files in static/platform/sites/all/translations suppossed to be owned by o1.web?
If so, we will simply chown  122:100 static/platform/sites/all/translations/* should that do the trick?

We know that the static/platform/sites/all/translations directory itself has to chmod to 777 in order to actually update the translations, and that this must be done manually since octopus/boa will set it to 775 constantly.

Thanks for the clarification.  We have no idea as to how the .po files ended up with different ownerships, unless they end up with the ownerships of whatever method (drush or web site admin) was used, but this awareness doesn't solve the problem of some translation/localization files being unable to be saved - meaning, in fact, I take it, that the existing .po file is unable to be written over..

Best,

Ed

**Comment by omega8cc** [comment]
The web server has no write access there, so it will not work, because this directory is a part of the codebase, not files where web server could write something. It could work only with Drush on command line, perhaps.

You managed to get some files created there by web server only because you have set the permissions to 777.

It is against the very basic concept in BOA, and also in general, which dictates that the web server should never be able to write to the codebase, because it makes hacking attempts trivial to succeed.
