### ISSUE TITLE
I don't understand the backups.txt - how to perform a restore from Amazon S3 ?

### ISSUE THREAD

**Issue by Corvalan** [omega8cc/boa#1199]
I read the following in backups.txt and I still don't understand how to perform a restore from Amazon S3. It says:

```
USAGE:
  $ backboa backup
  $ backboa cleanup
  $ backboa list
  $ backboa status
  $ backboa test
  $ backboa restore file [time] destination
  $ backboa retrieve file [time] destination hostname

  RESTORE EXAMPLES:
  Note: Be careful while restoring not to prepend a slash to the path!
  Restoring a single file to tmp/
  $ backboa restore data/disk/o1/backups/foo.tar.gz tmp/foo.tar.gz
```

Questions:
What is the 'file' mentioned above? the example uses a foo.tar.gz file in the backups directory that gets restored to tmp/foo.tar.gz ? Does this have nothing to do with Amazon S3? 
When a nightly automatic backup is done by backboa, it does not create local backups on the server, right? It only backups up the whole system to Amazon S3. If I can't restore a site (codebase and database) from amazon s3, then how do I perform a complete system backup? Just by entering backboa restore? It does not say...

**Comment by yaazkal** [comment]
> What is the 'file' mentioned above? the example uses a foo.tar.gz file in the backups directory that gets restored to tmp/foo.tar.gz ? Does this have nothing to do with Amazon S3?

Yes, it has to do with Amazon S3 as it will retrieve the file from the bucket, you're just giving to the script the file name and the destination.
Note that with backboa you will backup the entire system (including files and databases), so if you are using it, maybe doing backups from the aegir panel is optional or redundant but it all depends on your use case. The advantage is that using backboa you even can restore an entire server if for any reason things go wrong. The example is pointing an assuming that a backup file that was created from the control panel exist. Take in mind that those backup files from the control panel if are not stored in another location (in this case aws s3) they are no "real backups" that can save you from issues.

> When a nightly automatic backup is done by backboa, it does not create local backups on the server, right? It only backups up the whole system to Amazon S3.

Yes, it does _not_ run aegir backups so you can see them on the control panel of your octopus. It runs backups but in another way: incremental backups of your entire file system depending on your configuration and it sends it to aws s3. The default runs a complete backup every 7 days and just incrementals day by day.

>  If I can't restore a site (codebase and database) from amazon s3, then how do I perform a complete system backup? Just by entering backboa restore? It does not say...

Looks like an ambiguos question for me.
Yes, _you can_ restore backups (files and databases) from Amazon S3 for a given site.
To perform a complete system backup (from your server to amazon) you run `backboa backup`.

### Restoring a site
So, maybe there is a lack of documentation about how to restore specifically a site or an entire server. But is also a lack of information about what do you want to restore from the server or site: modules? themes? the entire site? just the database? maybe the entire platform where the sites is located? the entire server configuration?

Let's try to restore the site example.com using some examples:

First, we want to know what are the available files for restoration:
`backboa list`

Usually it will print a big list, so is better to save the result to a file and we can easily look at it:
`backboa list > available_files.txt`

Now, you can check what files are related to example.com using:
`grep 'example.com' avilable_files.txt`

Note that the list is still big, because it will list files that maybe you will not need to restore unless there is a serious problem (nginx configuration, certificates, etc), so just for simplicity let's just look only the drupal related files:

`grep 'sites/example.com' available_files.txt`

You will get a list about dates and files that contains sites/example.com; something like: https://gist.github.com/yaazkal/36ab5af458c5b6e4f04ab1a9f4e6e6e6

If you want to list files from a specic date, like August 31st, you can:

`grep 'Aug 31.*sites/example.com' available_files.txt`

As we are going to restore the entire site, let's get just what we are interested about: The path of the site,  you can see that the site is actually stored at
`data/disk/o1/distro/012/drupal-7.54.2-prod/sites/example.com/`

So, to restore all the files from the previous complete bakcup, it is recommended to create a temp folder when you are going to check the files and then copy them to the real path, you just run:
`backboa restore data/disk/o1/distro/012/drupal-7.54.2-prod/sites/example.com tmp/example.com`

Check files and if everything is as expected go and copy those files to the path in the server. If not, try to restore it from a given date as is documented in backups.txt

Now, we just need to look for the database, the database usually is named `examplecom` (your domain without dots) but it can be different if you had performed some platform migration or backups restoration from the control panel, so just look for the right name looking at the drushrc.php file:
` grep 'db_name' tmp/example.com/drushrc.php`
Now that you have your database name, just go and check where it is stored quering again the `available_files.txt` file:

`grep 'examplecom' available_files.txt`

And you will notice again that the .sql files are stored in a path that looks like this:

`data/disk/arch/sql/your.servername.com-170831-0351/examplecom.sql.bz2`

where those numbers in the path is the date and hour of that given database snapshot.

So, you just have to restore that file (I mention how to restore a file or a directory above) and import that database to your site, you can do that using drush.

Good luck !

**Comment by yaazkal** [comment]
Maybe something like `backboa restore sitename.com` or something like that could be a good feature to add to the script in the future, just for restoring a site. @omega8cc

**Comment by Corvalan** [comment]
Thank you yaazkal, very helpful!

**Comment by yaazkal** [comment]
@Corvalan you are welcome and I'm glad that the information helped. Remember that you can also get information about the path and database using drush like `drush @example.com status` but I mentioned how to do it manually as I imagine the worst scenario posible when even no drush information about the site (like a completly deletion for any reason).

Regards!

**Comment by karudonaldson** [comment]
Hey @yaazkal thanks for the good info, much appreciated.

The backboa tool could be so much more powerful though I have often wondered how others handle their boa backups/DR strategy?  Would love to hear feedback?

It would be handy if one could snapshot a complete boa system, spin up a new VM and recover that snapshot to the new VM retaining all of your configuration/customisations/custom-platforms/sites/databases but getting the benefits of a clean system.  

In many cases this would be gold.  Examples might be testing in-head, local or a new OS release, a new feature.  Sure there are plenty of ways to do this.  Again, feedback welcome :)

I've highlighted features that I felt could be useful:

**DR restore a full system**
The docs mention backboa is geared towards DR so it makes sense that one could spin up a new VM, install just the backboa client and restore a full system like this:
`backboa restore svr.foo.bar YY/mm/dd`

**Which would**
- restore system configuration, any customisations and control files
- run the boa install script with the above directives already in place
- prompt for new hostname/IP or allow config in the command string as "newname" suffix
for example (back boa restore svr.foo.bar YY/mm/dd --setip=1.2.3.4 --hostname=svr2)
- recover custom platforms in static
- hostmaster UI customisations
- check all sites in the backup, and restore them all and their databases

Some other useful feature options might be:

**List and restore a platform and all sites within it**
`backboa list svr.foo.bar YY/mm/dd @PlatformAlias ALL`
`backboa restore svr.foo.bar YY/mm/dd @PlatformAlias ALL`

**List and restore an individual site as mentioned**
`backboa restore @sitename`

**Full SQL server restore**
`backboa restore svr.foo.bar date sql ALL`

I'm thinking out loud so any and all feedback would be useful to everyone.

**Comment by karudonaldson** [comment]
@omega8cc Is there any current method for restoring all sites from the backboa backup archive?  

Or does drush/Aegir have a mass restore script of all "Aegir backed up" sites from /data/disk/o1/backups directory, if all sites were backed up in the Aegir UI?

I understand the single site restore process using:
`drush provision-save` and `provision-deploy`

But if you're dealing with 100+ sites, all of a sudden that's not a viable method.

The hosting-remote-import is also handy, skipping a bit of the manual process, but can only be done one at a time, though a bulk site importer/exporter utility would compliment devop workflows for boa.

Grace and I had this discussion some years ago but a lot has changed since then. :)
