### ISSUE TITLE
Recommendation for optimizing SFTP connection. Currently very slow and repeating key authentication

### ISSUE THREAD

**Issue by Corvalan** [omega8cc/boa#1201]
I've been investigating why my SFTP connection is responding very slow (approx. 30 seconds waiting time) for starting the filder listing, upload and download files from the server. What I see is that after a short period of inactivity (5-10 min?) the server apparently closes the connection and then takes very long to process the private key authentication. 
Even after reconnection, downloading or listing files again takes the same long time, apparently this authentication lag repeats itself for different purposes.
There could be different reasons for this, but first I would like to know if this is a known issue/configuration in the BOA system.
In my experience this behavior is not normal and looks like a DNS related issue.

**Comment by omega8cc** [comment]
BOA disables DNS lookups in SSHD, so I doubt it's DNS related. This may happen if you open too many connections. Then the SSHD server or CSF flood-detection will start to throttle your connections. And when there are really too many connections, CSF may block you due to port flood. Try to whitelist your IP address with csf -a `123.123.123.123`, or even add your IP to `/etc/csf/csf.ignore`, run `csf -q` and see if you still experience the problem.
