### ISSUE TITLE
Include Aegir Configuration Management

### ISSUE THREAD

**Issue by yaazkal** [omega8cc/boa#1207]
It can be useful to have [Aegir Configuration Management](https://www.drupal.org/project/aegir_config) module available in order to manage configuration for Drupal 8 sites from the aegir control panel.

From the module description:

> This module provides tools around configuration management in Drupal 8.
Press the "Export Config" button, and Aegir will run `drush config-export` for you.
Press the "Import Config" button, and Aegir will run `drush config-import` for you.

Maybe is not a _must have_ module or a major feature for BOA since those drush commands can also be executed using alias, custom scripts or tasks, but maybe can be useful for the _no shell_ or less advanced user of BOA to find a button on the aegir interface (well, maybe that kind of user uses the drupal interface to run that task)

Anyway is just a proposition, not exactly a feature request.

**Comment by omega8cc** [comment]
We are tying to avoid too many extra tasks, to not overload the interface. Also, only extra tasks which may be useful as a complete solution for users with no SSH access, are good candidates. This one is not a complete solution for proper D8 upgrade workflow, and since you still have to run other commands with drush on command line to make this export/import useful, it makes little sense to add it in the control panel, in our opinion.

**Comment by yaazkal** [comment]
Makes completly sense.
