### ISSUE TITLE
Force Composer to use PHP 7.2 if available

### ISSUE THREAD

**Issue by omega8cc** [omega8cc/boa#1213]
Since Composer is used mainly for Drupal 8 sites, we should globally switch it to run PHP 7.0 or newer, instead of default 5.6

We can't make it configurable per Octopus instance, like we do this for Drush, but it's not needed anyway.

This should fix problems reported by some users, for example:

>"`composer update doctrine/inflector`" to version 1.2 throws this error:
doctrine/inflector v1.2.0 requires php ^7.0 -> your PHP version (5.6.31) does not satisfy that requirement

**Comment by yaazkal** [comment]
> This release removes support for HHVM and bumps the minimum supported
PHP version to 7.1.0.

https://github.com/doctrine/inflector/releases/tag/v1.2.0

Maybe this can have a side effect and drops HHVM support for D8 in BOA?
the update of doctrine/inflector is more like a few use case. Drupal runs normally on PHP 5.6 since doctrine/commons requires doctrine/inflector 1.*, so it will take the version that fits PHP 5.6

**Comment by yaazkal** [comment]
What I'm trying to say is that maybe this can be delayed for another BOA version.

**Comment by omega8cc** [comment]
Yeah, we have tested this and it's not really possible without making PHP 7.0 the system default PHP version, so we are dropping this idea.

**Comment by yaazkal** [comment]
A quick update with a workaround in case someone is experiencing the same problem and ended up here after a search.

**Clarification:** Is recommended to not run `composer update` on production and better to run it a controlled environment (local), and after verifying everything is working good, then update the _composer.lock_ file and run `composer install --no-dev` on the server side. At least is a practice I follow and I also do commit _composer.lock_ file on git to prevent uncontrolled behavior on production.

Now, that kind of errors also happens if your local/dev machine is running a php version that is newer than the cli version of the server. In this case, the _composer.lock_ file has been generated using PHP 7.0 so it adds php 7.0 dependencies but you face a problem because the server has PHP 5.6 on its CLI and composer dosen't install the dependencies because they don't match.

In BOA environments you can have CLI version (to run drush and composer) different than the PHP-FPM version that actually runs the site, So is safe to run this command to install/update your platform ignoring the cli php version:

`composer install --no-dev --ignore-platform-reqs`

That will prevent the error and composer will download the correct dependencies that supports the newer php version. Make sure to clear cache of the site and to run the site with the correct (newer) php version by editing the `~/control/multi-fpm.info` file.

**Comment by nadorator** [comment]
The solution provided here is not enough at all. 

Imagine the case: 

composer install is run from a rundeck plateform in php5 with ignore reqs, then php 7+ is used every where. Then the files are uploaded to the final server but this server is in php 7.0. You used google ads api which use Symfony/serializer version php 7.2 then crash it won't work…

**Comment by omega8cc** [comment]
System default PHP (that one Composer ends up using) is going to be the latest 7.2 in the upcoming BOA release. With even D6LTS, not to mention D7 now supporting PHP 7+, we will use PHP 7.2 as a new default for new installs, but will keep 7.1, 7.0 and 5.6 as available options per Octopus instance. However, since Composer is used basically only with Drupal 8+ there is no point in keeping system default PHP at anything older than 7.2
