### ISSUE TITLE
Redirect module conflict with manual cron execution in D8

### ISSUE THREAD

**Issue by pricejn2** [omega8cc/boa#1215]
Follow-up from #1061 as of BOA-3.2.1

When running cron manually from admin/reports/status, cron does not execute and ends in a redirect loop with a URL such as https://gist.github.com/pricejn2/8d784f0e2cd10e02297ba19fcdbffec8

**Comment by omega8cc** [comment]
Please don't include not truncated error output in the issue body. Truncate it to some sane length and link using gist. Thank you.

Also, since we are using proper syntax in Nginx to support Drupal 8 (I think), not sure why you think it's a BOA and not redirect module problem? Have you tried it on some non-BOA system running Nginx?

**Comment by pricejn2** [comment]
Oops, didn't realize how long that ended up being.

I'll try and test in a non-BOA environment to confirm.

**Comment by yaazkal** [comment]
Hi, I can confirm that this happens in a BOA environment and not locally: [gist](https://gist.github.com/yaazkal/44066470289d0b09bb48ded9f4ce3325) (also when checking for updates).

As pointed on issue #1061 this happen when the option `Enforce clean and canonical URLs` is enabled. I can see errors even when trying to select a variation of a commerce 2.0 product (ajax call) as seen [here](https://imgur.com/a/szHXl)

**Comment by omega8cc** [comment]
I can't reproduce this issue with Varbase D8 distro. It just works when running cron manually. But Varbase modifies cron with ultimate_cron module, and this perhaps breaks the built-in Aegir site cron, because it doesn't work, while the manual cron works.

This makes me think that you may be using some contrib module which causes the problem, and it's not related to the redirect module, or you have configured redirect module incorrectly.

I don't think it's related to Nginx configuration either, because we are using proper rewrite now.

**Comment by omega8cc** [comment]
I guess this could be the culprit breaking automated site cron: https://github.com/omega8cc/hosting/commit/7eb8039fa33f1027616001c2618ccd2f9ab68135

Note that its not related to the issue here (probably). Who knows!

**Comment by yaazkal** [comment]
I've tested today again (BOA 3.2.1) and I'm updatind this issue just for the record.  Make sure that the option `Allow redirections on admin paths.` it's enabled.

ping @pricejn2

**Comment by pricejn2** [comment]
thanks @yaazkal!

@omega8cc is this a forced override that makes sense in global.inc? `redirect.settings ignore_admin_path` defaults to false but needs to be true to avoid manual cron and admin redirect issues.

**Comment by omega8cc** [comment]
We don't use this module in D8, so don't have an opinion, but if this helps, patches/PR are welcome. Just curious why the D8 module comes with default settings which break things? Maybe it should be reported as a bug?

**Comment by yaazkal** [comment]
@pricejn2 not sure If you are experiencing issues with the core search feature, the url like `/search/node?keys=search example` looks like `/search/node?keys=search example&keys=search example&keys=search example` etc... so lots of redirects as the cron you initially mentioned.

@omega8cc this happens on BOA and not on local development (nginx and php-fpm is also used on local), so not sure if this needs to be re-opened.
