### ISSUE TITLE
_SSH_ARMOUR=YES not compatible with OpenSSH 7.6

### ISSUE THREAD

**Issue by ar-jan** [omega8cc/boa#1218]
OpenSSH 7.6 removed support for hmac-ripemd160 MAC. So maybe this is specific to _SSH_FROM_SOURCES=YES, but I couldn't login to my server anymore: `ssh_exchange_identification: read: Connection reset by peer`, and after rebooting: `ssh: connect to host web.example.com port 22: Connection refused`.

See #1217, posting as an issue as well in case anyone's looking for this in the issue queue.

**Comment by omega8cc** [comment]
Thanks for the report. It's related to this experimental feature:

`_SSH_ARMOUR=NO #---------------- Allows to enhance OpenSSH security when YES`

**Comment by omega8cc** [comment]
Patch committed. Thank you!

**Comment by EdNett** [comment]
Please forgive my ignorance, but we still can't login via ssh after the update from 3.2.0 stable to 3.2.1

Is this ssh armour that seems to be the problem the same thing as the Novell apparmour?

How, with only an ftp access in a rescue mode, can we disable SSH_ARMOUR and configure the sshd so that we can login once again via SSH?

Thanks for any pointers or help.

Best,

Ed

**Comment by ar-jan** [comment]
The patch was committed after 3.2.1 was released, so you should manually apply [these changes](https://github.com/omega8cc/boa/pull/1217/commits/fa2b13700e9a6f5c34abbc7819a1c84520f42e9d) to /usr/etc/sshd_config.

**Comment by EdNett** [comment]
Thank you. That worked fine.
