### ISSUE TITLE
Cloning tasks does not clone the module enabled/disabled settings well

### ISSUE THREAD

**Issue by Corvalan** [omega8cc/boa#1220]
For one of my aegir sites, the clone tasks (in the same platform) does not enable all required modules in the cloned version. The site is cloned, but a lot of enabled modules are not enabled any more.
I can't see why this happens, the module are just where they should be in foo.com/modules, everything appears as an exact clone with regard to modules, locations, permissions, etc. I'ts just that some modules are not enabled any more after the clone tasks.
Any ideas what could cause this?

**Comment by Corvalan** [comment]
Okay I found out that cloning directly to another domain name on the same platform has this behavior mentioned above, while cloning to a subdomain of the website does work well. After that, migrating the subdomain to the new domain works fine. I can't remember reading this method, though.

**Comment by omega8cc** [comment]
There is no such procedure expected. It looks like you have a feature you are using which may cause unexpected issues with modules status. Aegir doesn't disable/enable any modules during clone/migrate tasks. The source of the problem is probably related to your own codebase/features, which modify the site on db updates or cache clears, etc.
