### ISSUE TITLE
Issues with Webform in Drupal 8

### ISSUE THREAD

**Issue by c-archer** [omega8cc/boa#1225]
After installing the Webform module on a couple of sites, I've started getting the following alerts:

`Time:   Sun Oct 29 20:08:44 2017 +0000
File:   /tmp/confi_40442686-ce6e-4ff6-b002-ff0aeed1b321/webform.webform_options.phone_types.yml
Reason: Script, file extension
Owner:  aegir:aegir (114:124)
Action: No action taken`

This is `YML` file that is the default for the webform module.

Contents of the file is:

`uuid: 
langcode: en
status: true
dependencies:
  enforced:
    module:
      - webform
_core:
  default_config_hash: 
id: phone_types
label: 'Phone type'
category: Demographic
options: "Home: Home\nOffice: Office\nCell: Cell\n"
`

**Comment by omega8cc** [comment]
Looks like you are using the master Aegir instance for sites hosting? It's not expected and not supported.

Does it affect Octopus instances too?

**Comment by omega8cc** [comment]
The problem is that our configuration for CSF/LFD monitors system `/tmp/` and will report unexpected files it finds there, while for Octopus it will not happen, because LFD doesn't monitor Octopus specific own tmp directory, which is located within the restricted web user home directory.

Please stop using the master instance and move sites to Octopus.

The other option is trying to modify the CSF/LFD  config (not recommended).
