### ISSUE TITLE
Support Amazon RDS

### ISSUE THREAD

**Issue by iaminawe** [omega8cc/boa#1236]
Here is my BOA info https://gist.github.com/iaminawe/815a9e20d4556fd2ea64ce576f9ab469

This is the second time I have encountered this problem so thought I should post it as an issue although it may end up being a feature request

I have a EC2 Server running BOA and hosting about 20 sites. All of the site databases are hosted on an an AWS RDS Instance (which as far as I understand is just like a normal remote db server) https://aws.amazon.com/rds/

When I ran a BOA system upgrade earlier - I found that after the upgrade completed without issues - all of the site credentials could no longer connect to the remote Database Server.

I have been able to restore them by editing each drushrc.php file and adding the master sql details and then migrating the site to a temp and then back to final domain. This works to restore them but is a pain to do for 20 sites so I would really like to look into how I can avoid this happening in the future.

Does BOA change these credentials by default on upgrade and is there a way I can disable this if it does happen as part of standard upgrade procedure. 

Thanks for any insight or suggestions you may have

**Comment by omega8cc** [comment]
It's not BOA, it's like Aegir works -- it will create new DB credentials (database name, db user name, db password) on every site Migrate task, and this can't be avoided, because to be able to auto-recover from failed task, and to not overwrite existing database too early, it must keep the credentials unique for the before/after Migration db connections.

I don't know how exactly you did this since remote DB is NOT supported in BOA (except when in a cluster mode installed with BOA scripts), but it sounds like the Aegir "root"/ system db user doesn't have enough privileges on the remote db server? Or it's not behaving like Aegir expects, so Aegir fails to update web server configuration with new credentials -- no idea, because we don't know what exactly happens -- does it create new databases and credentials and then simply fails to update web server configuration? Or it fails to create new db credentials and updates web server config with not working credentials? It is quite confusing.

**Comment by iaminawe** [comment]
Thanks for the explanation. I think I finally found out what was happening was the db users in RDS were given permissions based on IP and or hostname - and on running updates - a new IP or hostname update was being correctly assigned which was then breaking the existing creds ability to access the db. I am going to close this now as was not BOA's fault. Thanks again
