### ISSUE TITLE
Drush 9 support

### ISSUE THREAD

**Issue by pricejn2** [omega8cc/boa#1264]
Would be great to see Drush 9 support added into BOA. Thanks!

**Comment by omega8cc** [comment]
Drush 9 will not work with Drupal core older than 8, so there are no plans to use it in Aegir.

Aegir will migrate away from Drush in 4.x but we could provide newer Drush versions on command line only, I guess.

The only problematic and confusing detail is that Drupal 8 distros often include local copy of Drush, and this may cause problems until it's removed.

**Comment by EdNett** [comment]
Hello,

I think this is really necessary (having drush 9 that we can at least use from the cli) because D8 distros (like thunder) are using drush 9, and drush 8 commands in BOA (when thunder is installed as a static platform) are causing problems, and there are multiple errors - just in viewing site admin pages with recent  static composer-installed thunder versions (for example 2.39 running drupal 8.7.0)

Could you please give us the possibility to call drush 9 from the command line by adding it to /opt/tools/drush ... ?

It would probably help all d8 static installed platforms to use drush 9 as default for drupal 8 sites and platforms. I think open social also uses druah 9.

best regards,

Ed

**Comment by omega8cc** [comment]
Please don't open duplicate issues.

**Comment by omega8cc** [comment]
We are adding Drush 9 on command line after all. It still needs a few tweaks, but should be useful as `drush9` on command line.
