### ISSUE TITLE
Drupal hostmaster version 7.56

### ISSUE THREAD

**Issue by timlie** [omega8cc/boa#1284]
Hi,

I was really happy with the (extremely fast) automatic patching you guys did for the second time in a couple of weeks for #drupalgeddon2 and #drupalgeddon3
While I was checking yesterday if all my platforms were patched I noticed I had some problems with my hostmaster site. I could not log in. So I decided to do:

octopus up-stable all force

After rebuilding the hostmaster I could log in again. I thought everything was fixed.
Only, this morning I suddenly realized I wasn't sure this new hostmaster was patched or the version installed 7.56 was patched on your side.
After checking I could see it wasn't. The version installed is unpatched 7.56 which makes it vulnerable to attacks for #drupalgeddon2 and #drupalgeddon3

I think updating hostmaster version is big need here.

Thanks!

**Comment by omega8cc** [comment]
That is correct, stable BOA doesn't include security fixes, and if you re-install stable after the system was already patched, it will not touch the hostmaster codebase again, because it relies on control files and not codebase verification. This doesn't affect hosted sites/platforms, which are constantly patched if needed. New BOA release is coming shortly, but in the meantime we recommend to run BOA head, which is production-level stable (we are using it all the time). We are working on new release/upgrades policy/workflow to avoid such delays in the future. Sorry for the trouble!

**Comment by LunkRat** [comment]
> * Please never use HEAD version on any production server. Always use Stable.
>   The HEAD can be occasionally broken and should be used **only** for testing!
— https://github.com/omega8cc/boa/blob/master/docs/INSTALL.txt#L18-L19
