### ISSUE TITLE
Request / Suggestion - OpenSocial - D 8 distro

### ISSUE THREAD

**Issue by EdNett** [omega8cc/boa#1322]
Hi,

How about having OpenSocial in BOA - D 8:

drupal.org/project/social

Thanks,

Ed

**Comment by omega8cc** [comment]
We have tried it already, but it still includes old core version and doesn’t include many libraries it should by default. A bit surprising state of affairs so we have left it for ongoing testing and future release.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Corvalan** [comment]
@omega8cc  I hope you don't mind I quoted your reply in an issue that I posted in the OpenSocial project on Drupal.org
https://www.drupal.org/project/social/issues/3030498
Maybe it helps if you comment on that issue and clarify the more specific requirements?

**Comment by ronaldtebrake** [comment]
Hi guys, as one of the maintainers of Open Social I'd love to pitch in here.

I'm not sure about what you need for Open Social to run on BOA, but our recommended way of installing is by using composer instead of the drupal make files. 
The make files indeed need manual installation of libraries, due to the fact [Drupal doesn't whitelist libraries as quickly](https://www.drupal.org/project/drupalorg_whitelist ) as we are releasing versions . But again we highly recommend using composer for this. 

Other than that our [composer json](https://github.com/goalgorilla/open_social/blob/8.x-4.x/composer.json) doesn't include a specic version but a version range, so when core security update hits people don't have to wait for us to update core but can do it already themselves.

Hope this clarifies the current state & versioning / constraints we have on our end.

**Comment by omega8cc** [comment]
Thanks for your comments @ronaldtebrake -- we have obviously tested the distro with Composer like a few other distros we intend to include in BOA by default, using the commands on the project page on drupal.org and we got not ideal results -- Drupal core 8.6.5 and Open Social 8.x-4.2, so previous version.

The build command which was run 10 days ago was:

`composer create-project goalgorilla/social_template:dev-master social --no-dev --no-interaction`

Here are the screenshots:

![available updates social o1 v1 do de boa io-1](https://user-images.githubusercontent.com/128547/52225953-f5cecc00-28ab-11e9-9080-788adf29edb7.jpg)

![status report social o1 v1 do de boa io](https://user-images.githubusercontent.com/128547/52225975-07b06f00-28ac-11e9-97fa-01556632146a.jpg)

![social-8 4 3 octopus system powered by barracuda](https://user-images.githubusercontent.com/128547/52226019-1dbe2f80-28ac-11e9-9b32-fe315f9c7558.jpg)

Regarding missing libraries, it was from another distro testing, sorry for the confusion. Here it was just outdated Drupal Core and distro itself, so we have paused further testing.

**Comment by omega8cc** [comment]
@ronaldtebrake Just tested the build again and it still references the outdated code: https://gist.github.com/omega8cc/47aa509e140a94f91116df7529547624

**Comment by ronaldtebrake** [comment]
@omega8cc Thanks a bunch for the information, for some reason the build of the template didn't update correctly referencing old code like you encountered. 
I've just pushed the latest updates in to our template. For reference:
https://github.com/goalgorilla/social_template/commit/e5adea41685853b172dd65aa8ce33a9c0d010a01

Thats probably why the code was outdated. Hope it helps.

**Comment by omega8cc** [comment]
@ronaldtebrake Another test after clearing the cache, still old core: https://gist.github.com/omega8cc/7c47bb2f620a743f8b4b50abe4c34040

**Comment by omega8cc** [comment]
@ronaldtebrake Will try again, thanks!

**Comment by websiteexpress** [comment]
It would be terrific to get Open Social included in BOA now that BOA is supporting Drupal 8 Distros :)

**Comment by omega8cc** [comment]
Working on it!

**Comment by omega8cc** [comment]
@ronaldtebrake Would it be possible to update the template for core 8.6.8? It's still on 8.6.7 -- thanks in advance!

**Comment by ronaldtebrake** [comment]
@omega8cc, we haven't had a chance to test the latest patched version of Core with Open Social. 
We usually update the template once we have tested the changes. 
(Only for security releases we immediately update it)

I expect this core release update to land in our release coming wednesday (that's also when we update this template).

**Comment by omega8cc** [comment]
@ronaldtebrake -- Thank you, we will wait eagerly then, or will just include the current version in our release, because the other three (Lightning, Thunder and Varbase) templates already include 8.6.8 core.

**Comment by ronaldtebrake** [comment]
@omega8cc No, thank you ;)!
 
We have written a lot of extensions and patches on top of these versions so we can't automatically update these without the possibility of our distribution users running in to bugs. 
That's why it could be that it takes a little more time than other templates. (8.6.8 only got released yesterday for that matter). 

So i'd advise to just use the current version. Doing a composer update regularly will get you the latest core & open social versions as well! (We release new Open Social versions at least every month)

Hope it helps :)

**Comment by websiteexpress** [comment]
Now that the BOA configuration has been adjusted to support service workers, is there any merit in including https://www.drupal.org/project/social_pwa with this?

**Comment by omega8cc** [comment]
@websiteexpress We will include this module by default -- thanks for the reminder!

**Comment by omega8cc** [comment]
@ronaldtebrake -- That is absolutely understandable if you have enough core patches which need testing and potentially debugging. Since we are making the build-in platforms /codebases immutable, because upgrades in place are not a good idea in Aegir, which is designed to easy create new codebases and migrate sites to upgrade the codebase with automated rollback if anything fails, we can't rely on composer updates. We are using Composer like it was Drush Make -- once the codebase is built is site's on it provisioned, it shouldn't be modified to preserve codebase/schema sync and track changes. We will include existing version for now. Thank you for the information on your process.

**Comment by ronaldtebrake** [comment]
Thanks a lot @omega8cc for the detailed explanation, that makes a lot of sense.

**Comment by Corvalan** [comment]
I'm interested in the progress of supporting Open Social in BOA.  Currently I'm trying to upgrade to version 5.1 of the OS distribution, but I can't find documentation how to do that. I made a copy of the platform but since upgrade using composer is recommended, I'm a bit confused what to do.

**Comment by EdNett** [comment]
This is working great for us installed with composer in the static platform area. Sites are installing, verifying and working just fine.  We started with 8: 5.1 .

**Comment by omega8cc** [comment]
It should just work, we may include it in the future feature releases.

**Comment by omega8cc** [comment]
@ronaldtebrake You are now officially on board! https://github.com/omega8cc/boa/blob/master/README.txt#L158
