### ISSUE TITLE
Question: What is recommended mariaDB 10.2 to 10.1 downgrade path?

### ISSUE THREAD

**Issue by EdNett** [omega8cc/boa#1342]
Hello,

Since mariaDB 10.2 doesn't allow php 7.1 + (and we have experienced pure_ftpd_mysql incompatibilities with mariaDB 10.2 and 10.3 on other apache 2.4 based servers) we would like to have your recommendation as to what is the best way to downgrade?  Are we forgetting about Galera? Should we be thinking of moving to Percona or XtraDB? 

We thought we'd open this as a place for discussion for Boa testers and users who are running MariaDB 10.2 on Jessie and who wish to  use PHP 7.1+

A simple downgrade to mariadb 10.1 left us with unusable databases that appeared corrupted (possibly a collation problem) and we had to re-install 10.2 to get sites up again. 

Best,

Ed

**Comment by omega8cc** [comment]
There is no downgrade path usually. It will remove 10.2 (just leaving the data) and install 10.1 from scratch. This may or may not work, we haven't tested it.

**Comment by omega8cc** [comment]
Re:

>> Are we forgetting about Galera? Should we be thinking of moving to Percona or XtraDB?

Not sure what you mean?

**Comment by EdNett** [comment]
Hello,

Well, it seems like BOA has reached the end of the road with mariadb. Is that true? If we can't update to newer, "better" versions of mariadb, like 10.2 or 10.3, then that probably means that we will be leaving mariadb for good, it seems.  So, that means that we shouldn't use or count on galera , or splitting the db among more than one server, right?

My question is (especially since there are errors when downgrading to mariadb 10.1), shouldn't we just wait until BOA decides which mysql-like replacement for mariadb it is going to use (and I mentioned the most likely, I thought), and then move to that new db?  This assumes that if we keep mariadb 10.2 installed that we will be able to update our php 7.0 version to something past 7.0.24. We seem to be stuck at php 7.0.24 with mariadb 10.2.x installed, and we don't know why. Shouldn't a BOA install on Jessie with Mariadb 10.2 be allowed to upgrade php 7.0 to the current 7.0.33 or 7.0.36 - whatever it is in the php 7.0 series? 

Any feedback on what db BOA is going to choose to replace mariadb would be appreciated so that we can ponder our options.

Best regards,

Ed

**Comment by omega8cc** [comment]
To be honest, you experience issues only because you have decided to use non-default and thus risky MariaDB version instead of continue to use supported default which is 10.1

We have no plans to deprecate MariaDB, but we plan to add official support for Percona (don't confuse it with Galera, which is totally unrelated and used only in cluster variant).

We have already explained that you do can continue to use MariaDB 10.2, but because of its incompatibility with never PHP versions, you won't be able to install these newer PHP versions, until either PHP or MariaDB devs will fix the incompatibility.

It's beyond our control.

That's everything you need to know about this situation.
