### ISSUE TITLE
Please re-open drush 9 requested - issue 1264 - it is now needed for d8 sites and platforms

### ISSUE THREAD

**Issue by EdNett** [omega8cc/boa#1377]
Hello,

I think this is really necessary (having drush 9 that we can at least use from the cli) because D8 distros (like thunder) are using drush 9, and drush 8 commands in BOA (when thunder is installed as a static platform) are causing problems, and there are multiple errors - just in viewing site admin pages with recent static composer-installed thunder versions (for example 2.39 running drupal 8.7.0)

Could you please give us the possibility to call drush 9 from the command line by adding it to /opt/tools/drush ... ?

It would probably help all d8 static installed platforms to use drush 9 as default for drupal 8 sites and platforms. I think open social also uses drush 9.

see this issue, for example - drush 9 needed for upgrading drupal 8.6.7 to 8.6.8:

https://www.drupal.org/project/drupal/issues/3031128

I request you re-open this issue, please.

best regards,

Ed

**Comment by omega8cc** [comment]
It's Drupal core problem, not Drush problem, also "This issue is resolved by release of Drupal 8.6.9"

We don't have plans to include Drush 9 because it doesn't support Drupal 7, while Aegir runs on Drupal 7 and still has to support Drupal 7 and Drupal 6 sites. Adding Drush 9 only on command line is not going to help in anything, only would add confusion, because it can't be used by Aegir backbend anyway. Drush 8 is still developed to make sure it supports latest Drupal 8 core.
