### ISSUE TITLE
barracuda up-stable or barracuda upgrade

### ISSUE THREAD

**Issue by nirmaan-admin** [omega8cc/boa#1428]
The installer suggested to run the command `barracuda upgrade` after the installation
![image](https://user-images.githubusercontent.com/55142793/64680364-48ecab00-d49b-11e9-888a-e439d2dfeaa0.png)

wherein the document suggests `barracuda up-stable`
https://github.com/omega8cc/boa/blob/216d1297456d5580770544cd9a71946f23b47c8d/docs/INSTALL.txt#L5

Are they both same?

**Comment by lexsoft00** [comment]
I would suggest doing a` barracuda up-head`

I believe that `barracuda upgrade` is for changing the OS from Debian8 to Debian9, not 100% sure of this.

And `barracuda up-stable` it's being deprecated.

Hope this helps.

**Comment by omega8cc** [comment]
The "barracuda upgrade" is a description of the action, not the exact command to run, because the are a few options available. Typically, if you have installed BOA with `in-stable`, you should upgrade with `up-stable`, and if you have installed with `in-head`, you should upgrade with up-head. Of course you can install with `in-stable` and upgrade with `up-head` -- that's how we test upgrades, BTW. None of these command are being deprecated, but running head is safe most of the time, so if there is no new stable for longer than 3 months, we recommend to run head not the old stable, unless for testing. We are still working on switching to the rolling release procedures.

**Comment by ar-jan** [comment]
Changing this to `Please reboot and upgrade barracuda` may avoid any confusion.

**Comment by omega8cc** [comment]
The `docs/INSTALL.txt` already says at the top:

```
### IMPORTANT!

* After initial installation please reboot your system and then run
  the `barracuda up-stable` upgrade to complete all tasks and prepare
  the system for production use -- it is very important especially on
  newer systems like Debian Stretch.
```

That said, any displayed instructions should say exactly what command to run, as otherwise they always will be confusing. While we do expect that everyone actually reads the `docs/INSTALL.txt` we should perhaps just specify the exact command which is at the time recommended.
