### ISSUE TITLE
site install fails with message 'Write operation is not allowed.'

### ISSUE THREAD

**Issue by steeff** [omega8cc/boa#1432]
Hello,
8.x distribution sites install all fail with the same error message:
`exception 'Drupal\Core\Config\StorageException' with message 'Write operation is not allowed.' in /data/disk/o1/static/varbase-8.x-6.13/core/lib/Drupal/Core/Config/InstallStorage.php:118`
same when the distribution is installed by default by octopus (not in /static), same with varbase, thunder, lightning, ... platform itself is green and validated

This BOA has been moved to 4.0.1 recently, 7.x distribution sites work fine, os is still jessie. another BOA installed recently directly with 4.0.1 works fine on another server (stretch)

**Comment by omega8cc** [comment]
Please read and follow https://github.com/omega8cc/boa/blob/master/CONTRIBUTING.txt

**Comment by steeff** [comment]
thanks for your reply, here is the boa.info https://gist.github.com/steeff/79be8c15da8b4cb6ab180def24b30960 
in the meantime i've upgraded the server to stretch but still the same issue... another info that might be related, when I try to change the value of _PHP_FPM_VERSION and PHP_CLI_VERSION from 5.6 to 7.2 then it is immediately reverted to 5.6 after save... ??

let me know if you need more input

**Comment by omega8cc** [comment]
You must install newer PHP versions before you will be able to use them. Since you haven't installed them yet, the system reverts your attempts to use the version available. Please check and follow the docs: https://github.com/omega8cc/boa/blob/master/docs/cnf/barracuda.cnf#L72

We do recommend that you upgrade barracuda and octopus to head instead of stable to make these things easier.
