### ISSUE TITLE
LE renewal fail / The LE Certificate attempted creation failed

### ISSUE THREAD

**Issue by Juc1** [omega8cc/boa#1453]
I had a LE problem in October which was fixed by https://github.com/omega8cc/boa/issues/1433

But now I am having a similar problem on the same Debian server (Digital Ocean) -  existing certificates are failing to renew. I have tried disabling and then requiring encryption. I have tried deleting and then creating the problem sites. Either way I get the same warning = 

[hosting_le] The LE Certificate attempted creation failed in data/disk/o1/tools/le/certs/example.com - warning
[hosting_le] Make sure that all aliases have valid DNS names pointing to your instance IP address.	- warning
[hosting_le] The alternative is to disable SAN mode for this site with empty ctrl file: /data/disk/o1/static/control/ssl-no-san-example.com	1 s. warning

BOA INFO = https://pastebin.com/CwakRSz8

Any ideas please?

**Comment by omega8cc** [comment]
Please don't try too many failed Verify tasks when you see that it's not all green, because too many failed attempts will block you on LE servers temporarily.

Instead, please check the task logs for details, and expand the line starting with "[hosting_le] ACME Output" — it will tell you why it failed with detailed explanation.


<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Juc1** [comment]
> Instead, please check the task logs for details, and expand the line starting with "[hosting_le] ACME Output" — it will tell you why it failed with detailed explanation.

@omega8cc problem fixed, thank you
