### ISSUE TITLE
Update "upgrade" documendation to use HEAD.

### ISSUE THREAD

**Issue by bserem** [omega8cc/boa#1469]
https://github.com/omega8cc/boa/blob/10af8056afb84dd1c5d93b52da846cee14f94834/docs/UPGRADE.txt#L35
should probably be updated to use HEAD instead of stable as discussed in #1467 and in other issues.

**Comment by omega8cc** [comment]
Yes. but only once we release the last old style "stable" and switch to rolling release (soon).

**Comment by Anoesj** [comment]
Sounds good! Could you elaborate what you mean with "rolling release"? Will we have to modify configuration? When will you be switching to rolling release (approx.)? Ever since we run on "head", we're getting "New BOA-4.0.1 Stable Edition available" emails, promoting a very old stable release. Will this be fixed as well?

**Comment by macmladen** [comment]
How soon will rolling be recommended?

With the problems in "stable" #1576 #1578 fresh install cannot be made and is very confusing.

**Stable** should be something that works nonetheless so it should be urgently patched to 4.1.4 or whatever but to enable a clean install (which I am attempting now).

**Comment by Anoesj** [comment]
At this point I'm quite confused about the right channel to be on. Should we be on HEAD or STABLE? What's the current state of these channels? Like, what does stable do and what does the head channel do.

**Comment by omega8cc** [comment]
Fixed in https://github.com/omega8cc/boa/commit/7fcc3f22937352e273c3e129bea75da8d9446bb0
