### ISSUE TITLE
Barracuda keeps running upgrade multiple times today

### ISSUE THREAD

**Issue by ar-jan** [omega8cc/boa#1485]
I have a pretty much default BOA install that's been chugging along for more a long time. I have automatic updates enabled, running on Sundays. I haven't made any changes in a long time. Today, the automatic upgrade has run already three times (I'm receiving the email message stating `REPORT: Successful Barracuda upgrade ...`, and it's also briefly taking down some of the hosted sites according to my monitoring). Has something in BOA changed/broken in the past week that could explain this? Here's the [boa info](https://gist.github.com/ar-jan/728e0dc5493f6a1f895e9d25547c2df8).

**Comment by omega8cc** [comment]
This was intended behaviour after we have discovered that many auto-updates failed to start or left some servers in an unstable state with not completed procedure, due to either network or DNS issues with some third party services we still depend on for MariaDB downloads, so we have decided to temporarily add extra entries in the system cron. This affected mostly servers with already re-built PHP, which was important for security reasons.

**Comment by ar-jan** [comment]
Ah, all good then, thanks!
