### ISSUE TITLE
_AUTO_VER=head causing trouble

### ISSUE THREAD

**Issue by Anoesj** [omega8cc/boa#1510]
Hello,

This morning, we noticed 6 of our 14 BOA servers were down after they were updated by the weekly update. The problem turned out to be that php (7.0/7.2/7.3) couldn't start anymore. `service php70-fpm start` threw this error: `error while loading shared libraries: libmysqlclient.so.18: cannot open shared object file: No such file or directory` (same for other php versions).

We were surprised to find out that most of our servers have been updated from BOA 4.0.1 to 4.1.1-dev automatically and broke on MariaDB being upgraded to 10.2. This seems to be related to #1504 . Why was `_AUTO_VER` set to `head` [by default](https://github.com/omega8cc/boa/commit/ad5349aaa3181bd64344d7ee00fde2fd7761df9d#diff-7023f0af6df0ad35c26db54b4d92f5a9R122)? I thought MariaDB 10.2 [wouldn't work well with PHP 7.1+](https://github.com/omega8cc/boa/issues/1320#issuecomment-456197899)?

I also saw this error in the email log:
```
...
sed: can't read /var/opt/php-7.2.31/Makefile: No such file or directory
...
/opt/php72/bin/php: error while loading shared libraries: libmysqlclient.so.18: cannot open shared object file: No such file or directory
...
```
(same issue with servers running php 7.0 or 7.3)

Thank you

**Comment by omega8cc** [comment]
You shouldn't run stable at this point, as it's outdated. Enabling autonomous updates is actually pointless if used with stable, because it doesn't actually upgrade anything in sync, worse yet, you are using over one years old code to update system, where Debian packages moved significantly in the meantime, and it may cause all kinds of unpredictable issues we don't cover. Head is the new stable, and should be used in production. We have switched default auto-updates exactly for this reason. You could still enforce stable with auto-updates, but we wouldn't recommend that.

**Comment by Anoesj** [comment]
Ah okay, we'll use `head` from now on then. That doesn't solve our problems though. Any idea where the PHP error `error while loading shared libraries: libmysqlclient.so.18: cannot open shared object file: No such file or directory` is coming from? Seems weird, especially since you just said you're not using libmysqlclient anymore.

**Comment by omega8cc** [comment]
I would suggest to add `_PHP_FORCE_REINSTALL=YES` to `/root/.barracuda.cnf` and see if that fixes the problem during `barracuda up-head`. Please make sure to update installers first with:

`cd;wget -q -U iCab http://files.aegir.cc/BOA.sh.txt;bash BOA.sh.txt`

**Comment by Anoesj** [comment]
Thanks for the fast replies, I appreciate it! We'll try this out tonight/tomorrow and let you know if it worked :)

**Comment by Anoesj** [comment]
We ended up rebuilding the servers, just to be sure. Thanks for your help.
