### ISSUE TITLE
php7.4-fpm missing libicuio.so so won't start

### ISSUE THREAD

**Issue by EdNett** [omega8cc/boa#1513]
gist here: https://gist.github.com/EdNett/0925c4a5ba789de1c0763b472d3bc48a

boa infor more here:  https://gist.github.com/EdNett/91fe3ed0874e6d65735dca422dfea6d2

Is there really a libicuio? Do you want libicu instead? libicu57 is already installed.

did you mean libicu57?

libicu67 is only found in unstable and testing.

**Comment by omega8cc** [comment]
You are using not supported environment, so it's hard to tell anything beyond "we can't reproduce the problem".

**Comment by EdNett** [comment]
Hello,

Sorry to have to say this, but your answer is absurd. So, we're not using a vps. Big deal! The error in the barracuda script remains, alas.

Have a good day,

Ed

**Comment by omega8cc** [comment]
I will explain. We are regularly testing installation and upgrades on Linode and Ocean Crawler plus obviously on VServer systems. We couldn’t reproduce this problem anywhere which confirms that it’s specific to your environment. The problem with dedicated machines is that they are running OS installed by your host staff, they are not regular OS images you could test on any popular VPS. So yes, it’s a big deal because we cannot even try to replicate your specific problem if we don’t experience it in our testing, so effectively you are on your own with debugging issues like this. That’s what we mean by saying that you are using unsupported environment. You need to check barracuda logs, try to rebuild PHP manually etc. It’s quite a lot to figure out. We can log in to your server and see if we can help, but your attitude needs to change first.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
