### ISSUE TITLE
php7.3 not updating to 7.3.20 - staying at 7.3.18

### ISSUE THREAD

**Issue by EdNett** [omega8cc/boa#1514]
Hello,

On today's head update  php7.3 was suppossed to update to 7.3.20 (from 7.3.18) and even though the update on the cli showed success, both sites and root (php -v) show 7.3.18 still!

boa info more here: https://gist.github.com/EdNett/91fe3ed0874e6d65735dca422dfea6d2

BOA [06:48:44] ==> INFO: Installed PHP version 7.3.18, upgrade required
BOA [06:48:44] ==> INFO: THIS PHP EXTRA is --with-freetype-dir=/usr
BOA [06:48:44] ==> INFO: Building PHP 7.3.20 from sources, please wait...
BOA [06:49:01] ==> INFO: Building PHP 7.3.20 part 1/3
BOA [06:49:13] ==> INFO: Building PHP 7.3.20 part 2/3
BOA [06:51:51] ==> INFO: Building PHP 7.3.20 part 3/3
BOA [07:36:13] ==> INFO: Installing PhpRedis for PHP 7.3.20...
BOA [07:37:12] ==> INFO: Installing UploadProgress for PHP 7.3.20...
BOA [07:37:26] ==> INFO: Installing JSMin for PHP 7.3.20...
BOA [07:37:42] ==> INFO: Installing MongoDB driver for PHP 7.3.20...
BOA [07:39:42] ==> INFO: Installing Imagick for PHP 7.3.20...
BOA [07:40:18] ==> INFO: Installing YAML for PHP 7.3.20...

**Comment by omega8cc** [comment]
You are using not supported environment, so it's hard to tell anything beyond "we can't reproduce the problem".

**Comment by EdNett** [comment]
Hello,

Sorry to have to say this, but your answer is absurd. So, we're not using a vps. Big deal! The error in the barracuda script remains, alas.

Have a good day,

Ed

**Comment by omega8cc** [comment]
I will explain. We are regularly testing installation and upgrades on Linode and Ocean Crawler plus obviously on VServer systems. We couldn’t reproduce this problem anywhere which confirms that it’s specific to your environment. The problem with dedicated machines is that they are running OS installed by your host staff, they are not regular OS images you could test on any popular VPS. So yes, it’s a big deal because we cannot even try to replicate your specific problem if we don’t experience it in our testing, so effectively you are on your own with debugging issues like this. That’s what we mean by saying that you are using unsupported environment. You need to check barracuda logs, try to rebuild PHP manually etc. It’s quite a lot to figure out. We can log in to your server and see if we can help, but your attitude needs to change first.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
