### ISSUE TITLE
BOA without Aegir

### ISSUE THREAD

**Issue by lexsoft00** [omega8cc/boa#1515]
Hi Omega8,

I was wondering if you have an install with all the server security and firewalls and but without Aegir or Drupal.

I'm looking for a secure install with database tools, PHP and Nginx for other tools such as Matomo (https://matomo.org/) and many other tools that would require a separate server.

Or could you recommend a trustworthy install?

Thanks a lot

**Comment by Amstercad** [comment]
While I'm not with Omega8, I think I can answer your question. BOA is an acronym for Barracuda, Octopus, and Aegir. Aegir is very important, and Aegir is purely a Drupal thing. Aegir is a Drupal website managing other Drupal websites, very well. So I believe the answer to your question is that your change request will not be approved.

**Comment by omega8cc** [comment]
We could consider adding this easily. In fact BOA can host out of the box also Wordpress and Grav CMS etc, it's just not automated yet, but as a hosting environment it's pretty app-agnostic, even if originally tuned for Drupal.

**Comment by Amstercad** [comment]
Please consider adding this functionality to BOA, especially when the cost & effort is no big deal. This would add value to BOA.

**Comment by Amstercad** [comment]
To elaborate:

I always describe Acquia, Pantheon, Platform.sh, etc. as "closed-source hosting platforms for your open-source Drupal website" while pointing out Omega8.cc is a fully open-source platform offering free support here on on Github and otherwise paid, professional support is available, and everyone over there really knows their stuff.

Once Omega8 allows hosting of non-Drupal stuff like Wordpress, well that'll keep me honest when I continue to make the argument about closed vs. open-sourced hosting platforms.

**Comment by lexsoft00** [comment]
If I can give an opinion on this:

Aegir will not be compatible with WordPress and it should not be from my opinion.
For BOA to be a PHP hosting application it will need to have 2 versions
1. BOA hosting for Drupal
1. BOA hosting for PHP App and decupled from Aegir, Drush and other Drupal specific built in tools. 

I would rather see more futures in BOA like automated testing, CD/CI automation for Drupal then having efforts to support other PHP frameworks.

That being said, it would be great if BOA could provide complete documentation for beginners in their official docs on how to add external PHP apps (database, nginx alias, redis cache, files and folder permissions for each group users) including awareness about security risks and what not to do without breaking changes and with support for upgrades.

**Comment by omega8cc** [comment]
Hosting WordPress on Aegir is absolutely possible for years, we just never had interest in adding this, keeping our pure-Drupal focus in the BOA stack -- see https://github.com/mlutfy/hosting_wordpress

That said, our own website is running Grav CMS on BOA for years, so it's not a rocket science to extend BOA with tools to host and manage other PHP apps, if there is an interest and if we receive financial contribution to make this possible (which means maintained, not just added and unsupported feature).

We obviously don't intend to invest heavily in making BOA officially supporting other PHP apps, but rather in making it possible without going via some kind of BOA university ;-)

Our focus remains dedicated to Drupal and Aegir, since we declared to provide LTS support for the classic Aegir (even if Aegir 5 is in the works) and by LTS we mean not just the usual "minimally maintained", which doesn't apply here, but efforts to support Drupal 10 and newer versions of PHP, Composer, Drush etc.

**Comment by omega8cc** [comment]
You can now install just Barracuda, without Octopus. But the Aegir Master is still installed in `/var/aegir` to make sure that web services (Nginx, Percona and PHP-FPM) have working configuration, which can be used without actually using Aegir. Not sure if that fits the suggested purpose, but it's there for those interested: https://github.com/omega8cc/boa/blob/5.x-dev/docs/INSTALL.md -- and the relevant example:

**Barracuda without Octopus with 4 PHP versions in silent non-interactive mode**

`boa in-lts public server.mydomain.org my@email system`
