### ISSUE TITLE
Today there are frequent `files.aegir.cc is not available`

### ISSUE THREAD

**Issue by macmladen** [omega8cc/boa#1526]
Today I am performing third complete VM reinstall, bare system and **BOA** and I am frequently facing fails due to availability:

```
root@mek:~# boa in-stable public boa.mek.rs mek_aegir@bluefish.rs o1
ERROR: uk.files.aegir.cc is not available, please try later
root@mek:~# boa in-stable public boa.mek.rs mek_aegir@bluefish.rs o1
ERROR: nl.files.aegir.cc is not available, please try later
root@mek:~# boa in-stable public boa.mek.rs mek_aegir@bluefish.rs o1
ERROR: jp.files.aegir.cc is not available, please try later
root@mek:~# boa in-stable public boa.mek.rs mek_aegir@bluefish.rs o1
ERROR: files.aegir.cc is not available, please try later
root@mek:~# boa in-stable public boa.mek.rs mek_aegir@bluefish.rs o1
 
BOA [09:17:10] ==> Skynet Agent v.BOA-4.1.3 welcomes you aboard!
 ```

It is just after plain Debian 9 server install with US English and all defaults with only SSH and essential tools.

Not sure whether in scripts the protocol is http or https and which should be respected as in `INSTALL.txt` an **http** is suggested

```
cd;wget -q -U iCab http://files.aegir.cc/BOA.sh.txt;bash BOA.sh.txt
```

There were also some problem in **install**:

```
BOA [09:30:49] ==> OOPS: mytop-1.6.tar.gz failed download from http://files.aegir.cc/dev/src/mytop-1.6.tar.gz
/opt/tmp/boa/lib/functions/sql.sh.inc: line 918: cd: /var/opt/mytop-1.6: No such file or directory
```

```
BOA [09:38:47] ==> OOPS: mysecureshell-master-20-03-2015.tar.gz failed download from http://files.aegir.cc/dev/src/mysecureshell-master-20-03-2015.tar.gz
/opt/tmp/boa/lib/functions/system.sh.inc: line 136: cd: /var/opt/mysecureshell: No such file or directory
sh ./install.sh yesall failed.  Error (if any): 0
```

```
BOA [09:52:43] ==> OOPS: yaml-2.0.4.tgz failed download from http://files.aegir.cc/dev/src/yaml-2.0.4.tgz
/opt/tmp/boa/lib/functions/php.sh.inc: line 724: cd: /var/opt/yaml-2.0.4: No such file or directory
```

```
BOA [10:04:58] ==> OOPS: imagick-3.4.4.tgz failed download from http://files.aegir.cc/dev/src/imagick-3.4.4.tgz
/opt/tmp/boa/lib/functions/php.sh.inc: line 658: cd: /var/opt/imagick-3.4.4: No such file or directory
BOA [10:04:59] ==> INFO: Installing YAML for PHP 7.3.22...
BOA [10:05:10] ==> OOPS: yaml-2.0.4.tgz failed download from http://files.aegir.cc/dev/src/yaml-2.0.4.tgz
/opt/tmp/boa/lib/functions/php.sh.inc: line 724: cd: /var/opt/yaml-2.0.4: No such file or directory
BOA [10:05:13] ==> INFO: Installing Limited Shell 0.9.18.9...
BOA [10:05:32] ==> INFO: Installing Redis update for Debian/stretch...
BOA [10:05:43] ==> OOPS: redis-6.0.6.tar.gz failed download from http://files.aegir.cc/dev/src/redis-6.0.6.tar.gz
/opt/tmp/boa/lib/functions/redis.sh.inc: line 227: cd: redis-6.0.6: No such file or directory
BOA [10:05:51] ==> INFO: Installing Aegir Master Instance, please wait...
```

Now a ton of other errors and failed install, obviously all to unresolvable domain, which is sometimes visible, sometimes not.

**Comment by Amstercad** [comment]
I am also experiencing this issue.

**Comment by macmladen** [comment]
My server is based in Germany, **Hetzner** which has always been an excellent provider.

**Comment by macmladen** [comment]
Today everything installed perfectly.

**Comment by Amstercad** [comment]
This issue seems fixed, and I think the ticket can be closed.

Still, I'll enclose the results from my first attempt at upgrading from head to stable, while I figure out what to do next about it.

Barracuda System managed by Skynet Agent v.BOA-4.1.1-dev welcomes you aboard

ams:~# barracuda up-stable
 
BOA [06:57:58] ==> Skynet Agent v.BOA-4.1.3 welcomes you aboard!
 
BOA [06:58:01] ==> INFO: UPGRADE
 
Do you want to proceed with the upgrade? [Y/n] 

BOA [06:58:17] ==> VIRT: This system is supported: Linux KVM guest
 
BOA [06:58:17] ==> Aegir on ams.whiskeytangobravo.com Debian/stretch x86_64 PHP 7.4
 
BOA [06:58:25] ==> INFO: Installing extra Drush versions...
BOA [06:58:29] ==> INFO: Drush 9.7.2 already installed
BOA [06:58:34] ==> INFO: Drush 9.7.2 setup complete
BOA [06:58:34] ==> INFO: Running system packages update...
BOA [06:59:12] ==> INFO: Upgrading required libraries and tools...
BOA [06:59:38] ==> INFO: Running aptitude full-upgrade...
BOA [07:01:01] ==> INFO: Installed Nginx version nginx/1.19.1, upgrade required
BOA [07:01:01] ==> INFO: Upgrading Nginx...
BOA [07:03:16] ==> INFO: Installing MySecureShell master-20-03-2015...
BOA [07:03:29] ==> INFO: Installed MyQuick 0.10.0 for 10.2.32 (10.2.33), rebuild required
BOA [07:03:29] ==> INFO: Building MyQuick 0.10.1 from sources, please wait...
BOA [07:03:45] ==> INFO: Installed PHP version 7.2.31, upgrade required
BOA [07:03:45] ==> INFO: Building PHP 7.2.33 from sources, please wait...
BOA [07:03:51] ==> INFO: Building PHP 7.2.33 part 1/3
BOA [07:03:54] ==> INFO: Building PHP 7.2.33 part 2/3
BOA [07:04:39] ==> INFO: Building PHP 7.2.33 part 3/3
BOA [07:16:15] ==> INFO: Installing PhpRedis for PHP 7.2.33...
BOA [07:16:34] ==> INFO: Installing UploadProgress for PHP 7.2.33...
BOA [07:16:42] ==> INFO: Installing JSMin for PHP 7.2.33...
BOA [07:16:50] ==> INFO: Installing Imagick for PHP 7.2.33...
BOA [07:17:04] ==> INFO: Installing YAML for PHP 7.2.33...
BOA [07:17:16] ==> INFO: Installed PHP version 7.3.19, upgrade required
BOA [07:17:16] ==> INFO: Building PHP 7.3.22 from sources, please wait...
BOA [07:17:22] ==> INFO: Building PHP 7.3.22 part 1/3
BOA [07:17:25] ==> INFO: Building PHP 7.3.22 part 2/3
BOA [07:18:13] ==> INFO: Building PHP 7.3.22 part 3/3

BOA [07:29:40] ==> INFO: Installing PhpRedis for PHP 7.3.22...
BOA [07:29:59] ==> INFO: Installing UploadProgress for PHP 7.3.22...
BOA [07:30:07] ==> INFO: Installing JSMin for PHP 7.3.22...
BOA [07:30:16] ==> INFO: Installing Imagick for PHP 7.3.22...
BOA [07:30:29] ==> INFO: Installing YAML for PHP 7.3.22...
BOA [07:30:40] ==> INFO: Installed PHP version 7.4.7, upgrade required
BOA [07:30:40] ==> INFO: Building PHP 7.4.10 from sources, please wait...
BOA [07:30:46] ==> INFO: Building PHP 7.4.10 part 1/3
BOA [07:30:49] ==> INFO: Building PHP 7.4.10 part 2/3
BOA [07:31:30] ==> INFO: Building PHP 7.4.10 part 3/3
BOA [07:42:02] ==> INFO: Installing PhpRedis for PHP 7.4.10...
BOA [07:42:21] ==> INFO: Installing UploadProgress for PHP 7.4.10...
BOA [07:42:29] ==> INFO: Installing JSMin for PHP 7.4.10...
BOA [07:42:37] ==> INFO: Installing Imagick for PHP 7.4.10...
BOA [07:42:51] ==> INFO: Installing YAML for PHP 7.4.10...
BOA [07:43:02] ==> INFO: Installed Redis version 6.0.5, upgrade required
BOA [07:43:02] ==> INFO: Installing Redis update for Debian/stretch...
 
Do you want to upgrade Aegir Master Instance? [Y/n] BOA [07:44:28] ==> INFO: Running Aegir Master Instance upgrade
BOA [07:44:56] ==> INFO: Testing previous install...
BOA [07:44:56] ==> INFO: OPS, zombie found, moving it to backups...
BOA [07:44:57] ==> INFO: Testing previous install again after removing zombie...
BOA [07:44:58] ==> INFO: Test OK, we can proceed with Hostmaster upgrade
BOA [07:44:58] ==> INFO: Moving old directories
BOA [07:44:58] ==> INFO: Downloading drush 8.3.5.2...
BOA [07:45:02] ==> INFO: Installing Aegir Provision backend...
BOA [07:45:02] ==> INFO: Downloading Drush and Provision extensions...
BOA [07:45:05] ==> FATAL ERROR: Drush is broken (/opt/php74/bin/php /var/aegir/drush/drush.php help failed)
BOA [07:45:05] ==> FATAL ERROR: Aborting AegirUpgrade installer NOW!
BOA [07:45:05] ==> FATAL ERROR: AegirUpgrade installer failed
BOA [07:45:05] ==> FATAL ERROR: Aborting Barracuda installer NOW!

BARRACUDA upgrade completed
Bye

**Comment by Amstercad** [comment]
Files that depend on ny.files.aegir.cc cannot be accessed (or pinged) so things are now failing over here again.

**Comment by omega8cc** [comment]
We are sorry for the hiccups, we have updated mirrors and some had incorrect firewall settings, so could block your server if there was silence in the logs otherwise. Now fixed.

**Comment by MetaBureau** [comment]
New server after reboot this is not working: wget -q -U iCab http://files.aegir.cc/BOA.sh.txt

**Comment by Amstercad** [comment]
files.aegir.cc doesn't seem to be available currently.

**Comment by omega8cc** [comment]
Please use some external methods to check, it's up an running with no issues..

```
$ curl -I files.aegir.cc
HTTP/1.1 200 OK
Server: nginx
Date: Tue, 29 Dec 2020 22:13:43 GMT
Content-Type: text/html
Content-Length: 420
Last-Modified: Wed, 27 Mar 2013 17:31:32 GMT
Connection: keep-alive
Vary: Accept-Encoding
ETag: "51532cf4-1a4"
Accept-Ranges: bytes
```

**Comment by Amstercad** [comment]
Thank you for your comment, and indeed you were correct. Still, I might as well report related weirdness in case it helps someone else: In the last 48 hours I've made multiple attempts to install BOA at both digitalocean.com and vultr.com without success. What worked, the first time thank goodness, was an install at linode.com.

My comment yesterday was the result of a failed install at vultr.com.

**Comment by Amstercad** [comment]
...and to provide more detail, using the new Linode server, I had no problem following the documented details from the **gorgeous** docs/MIGRATE.txt to copy about 50, D7 & D8 websites en masse away from an older Digital Ocean server, **flawlessly** while I drank a beer, (somewhat copy/pasted, GIT'd, & scripted in-advance).

**Comment by omega8cc** [comment]
We are relocating some mirrors to avoid issues, so it shouldn't be a problem anymore.
