### ISSUE TITLE
Wrong https certificate created with letsencrypt

### ISSUE THREAD

**Issue by timlie** [omega8cc/boa#1530]
Hi,

One of our sites created/updated this night a new https certificate.
When visiting the site, we now get the unsafe certificate "error". The certificate authority is now:

Fake LE Intermediate X1 

which is used for testing.

Has this anything to do with these two recent commits?:

https://github.com/omega8cc/boa/commit/b9c741fd8dd79605e880f8e220443a6464bd5b61
https://github.com/omega8cc/boa/commit/ccdb36b7a159e106091a6325131a0640c7bc6f4c

Certificates which were registered on 30 september are ok.

Thanks.

**Comment by omega8cc** [comment]
Oops, that could be very unfortunate coincidence. Have you tried to simply run Verify task on this site? We had to introduce both newer Dehydrate script and self-repair procedure, after receiving too many reports about failing certificate updates due to apparently broken or outdated account IDs, and the only way to enforce new account ID was to switch to demo temporarily, which should immediately switch back to live. By the way, our attempts with generating new account without switching to demo temporarily failed a dozen of times. The errors looked like this:

```
Processing [site name]
 + Signing domains...
 + Generating private key...
 + Generating signing request...
 + Requesting new certificate order from CA...
  + ERROR: An error occurred while sending post-request to https://acme-v02.api.letsencrypt.org/acme/new-order (Status 400)

Details:
HTTP/2 400
server: nginx
date: Thu, 01 Oct 2020 14:02:41 GMT
content-type: application/problem+json
content-length: 178
cache-control: public, max-age=0, no-cache
link: <https://acme-v02.api.letsencrypt.org/directory>;rel="index"
replay-nonce: 0101451H1-RSaiWNywp_BfV0vU49GsDf9cXVXX_4fEtGmkM

{
  "type": "urn:ietf:params:acme:error:malformed",
  "detail": "Malformed account ID in KeyID header URL: \"https://acme-v02.api.letsencrypt.org/acme/acct/\"",
  "status": 400
}

```

**Comment by timlie** [comment]
Sorry for late reply.
I did immediately try to re-verify site but no succes. Tried to disable ssl settings and enable it again, no succes. Disabled it until today. Today enabled ssl settings again and now it works fine again.
Thanks.

**Comment by timlie** [comment]
For the record, I had to re-verify (once per site) several sites today to get a correct ssl certificate, all had the:

Fake LE Intermediate X1

certificate.

**Comment by ar-jan** [comment]
I had this issue, on every single site hosted on that instance. Re-verifying did solve the issue for hosted sites, but the hostmaster instance itself was also affected and there re-verifying does not work.

**Comment by bserem** [comment]
@ar-jan I believe you should not issue LE certificates on the hostmaster instance.

In any case, my systems were also affected by this issue, a manual verify fixed it.

**Comment by ar-jan** [comment]
I did not enable encryption for the hostmaster in Aegir UI; the hostmaster is/was in live SSL mode by deleting `/data/disk/o1/tools/le/.ctrl/ssl-demo-mode.pid` and then stopped working when this problem occurred. I've also run `octopus up-stable o1 both` but that doesn't help either. At least it's not as big a problem because it's not user-facing (in my case).

**Comment by omega8cc** [comment]
We have added several self-healing/check procedures to fix the issue by re-registering the LE account.
