### ISSUE TITLE
Drupal 8 and 9 vanilla platform

### ISSUE THREAD

**Issue by macmladen** [omega8cc/boa#1537]
The thing I liked the most about BOA is the inclusion of an optimized core and centralized base for building websites.

I am not sure I quite understood why Drupal 8 vanilla is not included and distributions are? There was an issue about soft linking, but I see four distributions.

Even more, there seems that there will be vanilla Drupal 9 (hopefully sooner than 9.1.0) which makes lack of D8 platforms even more strange?

Of course, we can add ourselves but that does not match enhancements offered by D7 an D6.

```
 @ Drupal 9

 Drupal 9.0.0 ----------------- https://drupal.org/project/drupal/releases/9.0.0
 Thunder 4.5 ------------------ https://drupal.org/project/thunder

 @ Drupal 8

 Lightning 5.0.1 -------------- https://drupal.org/project/lightning
 Opigno LMS 2.16 -------------- https://drupal.org/project/opigno_lms
 Social 9.2 ------------------- https://drupal.org/project/social
 Varbase 8.6 ------------------ https://drupal.org/project/varbase
```

1. **Q:** Will there be optimized **Drupal 8** dev, stage, prod as it was with D7?
2. **Q:** Will there be optimized **Drupal 9** dev, stage, prod as it was with D7?

**Comment by omega8cc** [comment]
Starting with Drupal 8 BOA doesn't offer any enhanced core anymore, which was the main factor behind providing ready to use platforms for D6 and D7. For D8 and newer it no longer makes sense, because virtually every distro switched to Composer based build, with separate web and vendor directories for security etc, so it really no longer makes sense other than for testing -- and that's why we still provide very old D8 and D9 platforms -- so we could still easily test compatibility and upgrades in Aegir faster, but it's not intended for production use anymore. At least you are probably the only person requesting this.. ;-)
