### ISSUE TITLE
Can't get Redis for Drupal9 to work

### ISSUE THREAD

**Issue by timlie** [omega8cc/boa#1581]
Hi,

As mentioned in this issue (and on omega8cc's twitter account), this issue is fixed from somewhere in april:

https://github.com/omega8cc/boa/issues/1553

I updated boa to latest head, my boa info file:
https://gist.github.com/timlie/22542b2ba4dcb3a857681738f60ed332

I created new platform with drupal 9.2.3. Migrated site to this new platform. Site still uses the redis for Drupal 8 module.
Also tried explicitly setting the:

redis_use_modern = TRUE

setting in boa_site_control.ini but still no luck.

Any advice on this?
Thanks!

**Comment by tijmenve** [comment]
I'm having the same issue. Tried everything but can't get it to work.

**Comment by omega8cc** [comment]
The latest version of Drupal 8 Redis integration module works with Drupal 9, there’s no D8 version. To make it work you should upgrade both barracuda and octopus to head.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by timlie** [comment]
Hi @omega8cc thanks for your reply.

I updated both barracuda and octopus to head.

After migrating the site to the Drupal 9 platform, status report showed I was using an incompatible version of Redis.
I uninstalled the module.
When browsing the modules page, it shows the error you can see in this screenshot:

![redis](https://user-images.githubusercontent.com/8566627/129519393-26dfb1f5-6aa9-4dbf-8eba-a04d71a8af27.PNG)

The o_contrib_eight directory for this Drupal9 platform has two redis versions:
redis_compr (which has a version_requirement key for also drupal 9 in the info.yml file)
redis_eight (which has only 8.x version requirement key)

Thanks!

**Comment by omega8cc** [comment]
BOA by default enables the 9.x compatible version of Redis integration module, while both legacy and 9.x compatible versions reside in the same directory because otherwise it would break many sites not yet upgraded to latest Drupal 8.x or 9.x

For this reason BOA comes with special switch to enable legacy mode per site or per platform in the respective INI file:

```
;;
;;  The modern version of Redis integration module is enabled by default.
;;  However, for Drupal 8 and newer it requires at least core 8.8.x
;;  If you are running Drupal 8 older than 8.8.x you need to uncomment
;;  the line below and change it to TRUE to make Redis work again.
;;
;;  NOTE: This variable has no effect for Drupal 7 nor Drupal 6.
;;
;redis_legacy_mode = FALSE

```

However, if you have migrated D8 site to D9 platform, this may result with another edge case we may need to look into further, because our focus was on supporting Redis for newly created D9 sites, but without breaking it for both latest D8 sites and legacy D8 sites.

Please make sure that you have this option disabled in your INI file.

Furthermore, it doesn't really matter what Drupal says about the module, because it's not really a module, and current implementation works also when it's not enabled at all (just like for D7 and D6 before).

Furthermore, to make sure if the site is actually using Redis or not, you should check Redis monitor on command line.

**Comment by timlie** [comment]
Thanks for the reply.
It is indeed a Drupal 8 site which I migrated to the new Drupal 9 platform.
I checked on the command line and can indeed monitor Redis activity for this site. I assume that this is working as @omega8cc mentioned without enabling the module (which I can't at the moment because it is listed as an Drupal 8 module).
I could also see that the Redis activity for this site "uses" the redis_compr "module".

**Comment by omega8cc** [comment]
We have introduced separate `o_contrib_nine` directory for newer redis integration module, so it no longer confuses Drupal when both versions exist in the same directory. Note that new `o_contrib_nine` is created both for new and existing Drupal 9 platforms on verify, while existing `o_contrib_eight` is removed. You need to upgrade both barracuda and octopus to have this feature.
