### ISSUE TITLE
Fix connection not private on fresh install

### ISSUE THREAD

**Issue by jcandan** [omega8cc/boa#1582]
Getting a "Your connection is not private" message at the browser on a fresh install from `boa in-head ...`.

![image](https://user-images.githubusercontent.com/2332648/129493474-c17e7de3-242c-4adb-bdb2-9610385042af.png)

I do have 22, 80, and 443 opened up on the droplet. I am under the impression that `boa in-head ...` sets up the Let's Encrypt pieces to serve a secure page.

**Comment by omega8cc** [comment]
Please pay attention to what is displayed during Octopus install. LE support is by default installed in demo mode, withe self-signed certificate initially: https://github.com/omega8cc/boa/blob/master/docs/SSL.txt#L58

Please use browsers accepting self-signed certificates (basically any apart from Chrome), or delete the control file and run Octopus upgrade.

It's not possible to have live LE certificate on install, because the vhost is still not in place yet, and for hostmaster site it's managed separately from sites hosted.
