### ISSUE TITLE
/usr/bin/sh: line 601: /usr/bin/sh: Argument list too long

### ISSUE THREAD

**Issue by klevinkona** [omega8cc/boa#1616]
Running all the drush command i see the following issue:

**/usr/bin/sh: line 601: /usr/bin/sh: Argument list too long**

The command i did tested are this

    drush @hostmaster pm-updatecode drupal

    drush @platform_hostmaster provision-verify

    drush @hostmaster provision-verify

    drush @hostmaster updatedb

**Comment by omega8cc** [comment]
You should never run manual updates on @hostmaster, unless you really know how Aegir backend works.

This error simply means that you have a directory, perhaps the tmp directory with too many files, so it breaks Drush.

You will need to delete the directory causing this and recreate as empty, since `rm` on the directory contents will also fail.

**Comment by klevinkona** [comment]
May i ask what are the directories that i need to check?

**Comment by omega8cc** [comment]
It depends on where you have this large amount of files, but a good start would be to check:

`~/.tmp/`

Also worth checking (but you can't simply delete it) is `~/.drush/` and its subdirectories.
