### ISSUE TITLE
Site Users IP Addresses being blocked

### ISSUE THREAD

**Issue by dserrato** [omega8cc/boa#1652]
I have a situation in which users on some of our sites are getting their ip addresses blocked. I am familiar with the situation pointed out in this documentation and how to whitelist them:

https://learn.omega8.cc/how-firewall-works-is-my-ip-blocked-121

These are normal website site managers, not Aegir users, that are just updating content on their sites and they end up getting temporarily blocked from their site. 

Anyone have any experience in this area? Any words of advice on what could be happening or how to solve?

Thank you.
Dan

**Comment by omega8cc** [comment]
It happens when there is too little IPs noise (visits) in the nginx access log, or many people work behind shared IP address.

There are two options:

1. Whitelist their IP or IPs ranges/subnet in `/etc/csf/csf.allow` for web access -- like this:

`tcp|in|d=80|s=111.222.333.44 # Some comment`

Then

`$ csf -q`

2. Increase the global limit in `/root/.barracuda.cnf` from default 399 allowed from latest 599 dynamic requests to something like:

`_NGINX_DOS_LIMIT=499`

Then run `barracuda up-head system`

Please note that the higher this value the less DDoS protection is working (if at all).

**Comment by omega8cc** [comment]
Another thing to consider is checking the nginx access log for possible floods from redirects loop causing this for them.
