### ISSUE TITLE
Request return of updated (supported once more) Print module 7.x-2.4

### ISSUE THREAD

**Issue by EdNett** [omega8cc/boa#1656]
Request return of updated (supported once more) Print module 7.x-2.4. It is currently locked by drush at the unsupported 7.2.2 .. Can you remove the lock for D7 and allow it once again with the update?

Thanks.

Ed

**Comment by omega8cc** [comment]
These days Drupal codebases are built with Composer and you can still use Drush Make to build legacy codebases and include any module you wish. We will rather remove more modules from o_contrib to keep it at reasonable minimum, because it actually works well only with Drupal 7 and Drupal 6 --it doesn't work as intended for Drupal 8+ because Drupal switched to class loading style and ignores the old ability to override modules with directory tree moving up to `sites/all/modules` or even `sites/name/modules`, so you are stuck with versions in o_contrib since Drupal 8.
