### ISSUE TITLE
Clone server?

### ISSUE THREAD

**Issue by attiks** [omega8cc/boa#1658]
I would like to clone a server A to another server B, and set a new FQDN for server B (master and octopus instances), is this possible and supported?

**Comment by omega8cc** [comment]
Aegir runs on wildcard based vhosts so it will work perfectly fine for hosted website when recreated for backup on a  machine with new name, followed however with some manual changes in the hostmaster database because Aegir upgrades and all tasks will fail, since the the system hostname is hardcoded in the hostmaster database and you will need to manually update its db records and drushrc files. Otherwise it would consider the new machine a "remote" system and refuse to cooperate.
