### ISSUE TITLE
Plans for BOA 5.x?

### ISSUE THREAD

**Issue by Anoesj** [omega8cc/boa#1665]
Hi,

We're wondering if there's more info available regarding the BOA 5.x upgrade. A timeline, features overview and upgrade path would be great. Especially now that Debian 9 is EOL, we're starting to feel the heat a little bit.

As much as we appreciate your ongoing work, the communication from Omega8cc to other parties using BOA can be improved a lot. I had to find out that you're working on a 5.x release from single comments on GitHub issue threads, like:
- https://github.com/omega8cc/boa/issues/1660#issuecomment-1171001059
- https://github.com/omega8cc/boa/issues/1662

If this would be communicated in a clear way via a single communication channel, that would solve a lot of constant worrying and question marks in our heads.

Happy to hear from you,
Anoesj - [Fonkel](https://fonkel.io)

**Comment by omega8cc** [comment]
The 5.x will not introduce anything major, besides newer Debian versions support and switching barracuda system upgrades to opt-out instead of the old default opt-in, so there’s nothing to announce or worry about, really. The open source BOA version is currently behind quite a bit overall, including the issue tracker and documentation, but that’s reality unfortunately. We don’t have resources to keep everything updated if only very small group of users contributes patches and useful debugging reports while majority seems to not care much, not enough even to keep their servers updated to head. So it’s tricky situation to balance without our paying customers actually financing support for non-paying (not just in money but attention) community. Still, we are going to improve in the areas which can be improved on reasonable terms.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by petrowsky** [comment]
Out of curiosity, are we supposed to do system updates to 10 or 11 or wait for BOA 5 to facilitate the process for us. I've got three servers (all updated) but only one of them is fully using aegir. The others just slowly had sites pulled off of them with other services running. Are we in a holding pattern for now?

**Comment by omega8cc** [comment]
>Out of curiosity, are we supposed to do system updates to 10 or 11 or wait for BOA 5 to facilitate the process for us. I've got three servers (all updated) but only one of them is fully using aegir. The others just slowly had sites pulled off of them with other services running. Are we in a holding pattern for now?

@petrowsky BOA doesn’t expect you to run major system upgrades manually. Actually it would be really bad idea because you would break your server for sure and BOA 4.x couldn’t help you anymore.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Juc1** [comment]
@omega8cc or anyone

> majority seems to not care much, not enough even to keep their servers updated to head

Maybe some people - such as me - don't know when to update. In the old system there was an announcement for example here https://github.com/omega8cc/boa/blob/master/CHANGELOG.txt - so I know ok I need to update - but in the new system of using head how do I know I need to update head? Is there any announcement anywhere or how do I know it is time to update head?

Thanks...

**Comment by EdNett** [comment]
Hello All, Here's an idea which could prove very helpful to anyone using a limited-resource vps or dedicated:

If you haven't alerady, do the utf8mb4 database and table conversion before doing the next BOA update. The reason why: we recently did it for some D7 older sites, and found that for small-medium size databases, the excellent script used up 2 vCores all by itself - which could cause a BOA upgrade to falter due to high load ... 

We used the script mentioned in   https://github.com/omega8cc/boa/issues/1575 :
su -s /bin/bash - o1 -c "drush8 @hostmaster utf8mb4-convert-databases -y"
(replacing 'hostmaster' with the sitename, of course, and o1 with the name of your octopus instance - only for D7 sites).
Best, Ed

**Comment by omega8cc** [comment]
BOA 5.0.0 is almost ready for release. It comes with much improved support for all Debian and Devuan releases plus easy to use major OS upgrade procedure. With BOA 5.0.0 release we will restart the changelog updates too, so anyone confused with the rolling release policy will have an extra source of the information on accumulated changes.

Important -- we have dropped the idea of switching auto-upgrades to opt-out, it will be still opt-in as before.
