### ISSUE TITLE
master (barrracuda) instance and octopus instance both unreachable after initial head install on Buster

### ISSUE THREAD

**Issue by EdNett** [omega8cc/boa#1671]
Trying to reach the master barracuda instance and teh octopus instance doesn't work on chrome and edge. This on fresh install of head on buster:
ERR_CONNECTION_REFUSED

boa info more:  https://gist.github.com/EdNett/cc50ed88b6b4a5e9f0b6d55ab1b92627

**Comment by AntiNSA** [comment]
Im having the same issue on Debian 9. Did you ever get it to work?

**Comment by zanami** [comment]
I'm trying to install a fresh Buster VPS
Everything went fine (except mcrypt.so) but nothing works
The problem is there's no /etc/nginx/conf.d and /etc/nginx/conf.d/aegir.conf in particular
So Nginx knows nothing about your master & o1 & basically any other site.
I know Debian support 10 is "work in progress" but I'm not sure if there will be any progress.

**Comment by omega8cc** [comment]
It should work normally for a long time already.
