### ISSUE TITLE
How can we support Omega8 to release BOA on a supported Debian 

### ISSUE THREAD

**Issue by hodbakhalaf** [omega8cc/boa#1688]
I am hosting multiple BOA servers, and now I'm stuck with the unsupported Debian 9, and I'm hesitating now even to run the update script not to break anything.

How can we, as a community, support Omega8 to test, debug, and develop for the BOA to be released on a Debian-supported version?

It would be great if you list some tasks that we can help you with.

**Comment by opensouler** [comment]
+1

**Comment by sluc23** [comment]
looks like they are moving out from Debian to Devuan, according to last commits..

**Comment by omega8cc** [comment]
Yes, our focus and our own systems are moving away from Debian and Ubuntu because it's very clear at this point that both will be more and more problematic due to the lock-in nature of systemd, but obviously we will still support both Debian latest versions and Ubuntu latest versions, because you can't find Devuan easily on popular hosting clouds, so you still need them at least as starting point for migration to Devuan. We don't plan to enforce Devuan migration, obviously. But we have to be prepared for the situation when you will not be able to migrate from Debian anymore, at least without extended downtime for extra steps required because of systemd increasing control of the system, not just init. It's very similar to what happened with MariaDB, where at some point you just can't migrate to Percona and you are locked in and forced to use other tools to migrate BOA.

**Comment by omega8cc** [comment]
We now support all Debian and Devuan supported releases and even made it trivial to automatically upgrade from any supported Debian version to latest Devuan with simple commands:

   `$ barracuda up-head system`
   `$ touch /root/.run-to-chimaera.cnf`
   `$ service clean-boa-env start`

All details in the docs: https://github.com/omega8cc/boa/blob/master/docs/UPGRADE.txt#L2

Enjoy!
