### ISSUE TITLE
Install the full New Relic monitor agent.

### ISSUE THREAD

**Issue by cmastro-ixiam** [omega8cc/boa#1729]
We are trying to install the full New Relic monitoring agent with all the statistics (All sites, PHP, MySQL, Nginx, Log, etc.) on a self-hosted BOA server.

The default installation does not work because BOA removes `systemctl` and manual installation also does not work.

Is it possible to install the complete New Relic agent on self-hosted servers?

PD: We already know about the `_NEWRELIC_KEY` var in `/root/.barracuda.cnf` and `~/static/control/newrelic.info`, but we need to monitor the whole server and not just part of it.

Thanks!

**Comment by omega8cc** [comment]
BOA was never designed to support server level NR monitoring, only Drupal sites level monitoring, because BOA is designed around a concept of multi-Aegir instances working in their restricted sub-environments, so no Octopus instance should ever be able to use system level monitoring.

We don't have good experience with NR on broader business level so we never considered using their server level tools, so they are basically not supported.

We may look into this in the future if we receive financial support to make this happen, but we much prefer and recommend Site24x7 for this use case, which can be installed and used independently of Barracuda.
