### ISSUE TITLE
How to do legacy up-4.2?

### ISSUE THREAD

**Issue by leevh** [omega8cc/boa#1755]
I know its a strange request, but I don't have time until the holidays to do a full upgrade and migrate of sites to boa 5 (yay!) and I still face a strange issue where all my sites are down and I need to run octopus up-head all force to fix the lets encrypt cert and bring the sites back up.  That's not the concern right now as I will upgrade to 5 soon, but in the meantime, how can I run the octopus upgrade for 4.2?  There doesn't seem to be a legacy command for up-4.2.  

thanks!

**Comment by omega8cc** [comment]
You can upgrade both barracuda and octopus to current head 5 without going via OS major upgrade, it will work just fine, even if you still run on Debian Stretch.

We could consider adding the old stable upgrade option but there’s no point really and it may cause unexpected issues because it’s no longer tested.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by leevh** [comment]
It worked great, thank you!
