### ISSUE TITLE
Best practice: static vs. platforms

### ISSUE THREAD

**Issue by socialnicheguru** [omega8cc/boa#1766]
in aegir most platforms were placed in /var/aegir/platforms.

In BOA should we do the same and place our platforms here:
/root/o1/platforms

Or is it best practice to place it in /root/o1/static ?

**Comment by omega8cc** [comment]
Please follow https://learn.omega8.cc/how-to-add-custom-platform-properly-140

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by socialnicheguru** [comment]
I read that already. 
I was looking for more of the "why".
Why /static vs /platform?

**Comment by omega8cc** [comment]
Because BOA static is the older standard introduced before Aegir introduced the platforms directory, plus it’s used for other things like user space configuration for limited shell user and non-admin Aegir access designed with security in mind for multi tenant environment.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
