### ISSUE TITLE
The Catastrophe or The Christmas Present

### ISSUE THREAD

**Issue by EdNett** [omega8cc/boa#1771]
The Catastrophe or The Christmas Present

I was saddened to read of the DUAL LICENCE NOTICE you put up last week. 

At first I thought - this is it - the Catastrophe! I know that you have pretty high prices, and I also 
know that I have no money, no income, and that most of what I host on our BOA instances are 
not-for-profit sites for which I work for free. How will I keep things going and keep things secure and updated,
I asked myself?

Then I thought about the ten years in which I have been using BOA to host the mostly not-for-profit sites I 
care about, and how I haven't had to spend any money - just time - for BOA. And I also remembered that throughout the 
years - and I started using BOA in the 2.x series I believe - that often around the time of Christmas and/or around 
Easter you produced a bug-fix and/or new functionality wrap and a new stable version, and I saw that once again, this year that 
you fixed everything up so that BOA had a well-working stable/head version without major bugs just in time for Christmas, and 
I said to myself, this isn't a Catastrophe, but rather it's another Christmas Present! So I would like to thank you, for another 
Christmas Present - a well-working BOA.

I have always believed and still do, that one should be compensated for one's work, skills, talent, innovation, genius, etc.
Maybe, I thougt, the Catastrophe was that BOA and Omega8 no longer had enough paying clients - and that is a Castrophe, 
first and foremost - not for me, but for Omega8!

I have always felt indetted to BOA for providing a hosting system for Drupal sites which worked, and I don't believe in a free 
lunch, so I have always tried to help, mainly by testing new stable and head versions right away and finding and reporting any bugs.
I don't have the bash skills necessary to fix bugs, however I have tried my best to improve BOA in this informal way as a tester and bug/anomoly reporter.That is all I could offer. That's all I can offer still. 

I know I can build a server with plain AEgir and make it work, but it won't be as good as, and will perhaps be much more 
time-consuming to maintain than BOA. I have to maintain a test vps and a production server at all times, so that all upgrades
 can't affect the production server; I couldn't use BOA without this dual server system. I don't know how long AEgir or Drupal - which is becomming far too complicated with all its dependencies on Symfony, Twig, etc. to rely on - will remain free to use, either.
 
 So, I don't know what your pricing will be, but I bet I won't be able to pay it. I spend $5 for a test VPS and $40 for a fine server for BOA, and that's what my limited means allow me to do. I have never been able to resell BOA or sell Drupal hosting, although I have tried.
 
 So, once again, thank you for your latest Christmas Present. If you offer a program of free BOA use and upgrades for dedicated testers, or for not-for-profit site hosting, I will apply. I know that you may not do this, and I understand that it is problematic deciding what qualifies as a not-for-profit site, and that still you should be able to make a good living from BOA - that is perhaps the most important aspect of this entire issue. 
 
 SO, if this is the end, then I want to leave on a positive note - thanking you for a BOA which allowed me to host Drupal sites easily, efficiently and without too much work. I tried my best to help and not just be a user and a taker.
 
 So, Thank you! 
 
 Merry Christmas and Happy New Year!
 
 EdNett
 Ed of the Net

**Comment by omega8cc** [comment]
Thank you for your kind words!

It would be catastrophic turn of events if we closed BOA and made it a private project, for sure.

Instead, we have decided to introduce system allowing BOA to thrive and improve, hopefully at higher speed than in recent years.

We understand financial circumstances because we are affected by them too.

It’s not a secret that overall market share of Drupal is in decline since the drastic move with version 8 and leaving 6 and 7 users in the dust. This forced virtually every other hosting specializing in Drupal to add non-Drupal apps support to save their business. We have managed to avoid this route, but it’s time to adjust to reality we are in.

We don’t plan to offer free licenses, but we are happy to host non-profit Drupal sites free of charge— we do this for over 10 years actually and always have ample resources to share with non-profits. It’s a good alternative for small scale and small traffic sites.

Our assumption is simple— if you can afford to pay for the server, you should be in a position to pay for the license. If not, then perhaps it’s a better idea to apply for free Aegir hosting and cut your hosting expenses to zero.

Also, to clarify some things about the project ongoing costs. The reality is that supporting the project, which includes responding to issues is also our cost we have to cover, especially when it’s about individual issues we don’t experience. This adds up and we are still a small company without any external VC funding and millions of dollars, so we have to be careful to manage the balance between making money and sponsoring others at our cost.

We hope that the new way of supporting BOA will be beneficial to everyone and will help to make it better and more capable, while making BOA project sustainable— it’s important difference, because we are not planning to make a profit on it, just to make it sustainable to keep it available for everyone.

Thank you and Happy New Year!



<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by 0com** [comment]
> Thank you for your kind words!
> 
> It would be catastrophic turn of events if we closed BOA and made it a private project, for sure.
> 
> Instead, we have decided to introduce system allowing BOA to thrive and improve, hopefully at higher speed than in recent years.
> 
> We understand financial circumstances because we are affected by them too.
> 
> It’s not a secret that overall market share of Drupal is in decline since the drastic move with version 8 and leaving 6 and 7 users in the dust. This forced virtually every other hosting specializing in Drupal to add non-Drupal apps support to save their business. We have managed to avoid this route, but it’s time to adjust to reality we are in.
> 
> We don’t plan to offer free licenses, but we are happy to host non-profit Drupal sites free of charge— we do this for over 10 years actually and always have ample resources to share with non-profits. It’s a good alternative for small scale and small traffic sites.
> 
> Our assumption is simple— if you can afford to pay for the server, you should be in a position to pay for the license. If not, then perhaps it’s a better idea to apply for free Aegir hosting and cut your hosting expenses to zero.
> 
> Also, to clarify some things about the project ongoing costs. The reality is that supporting the project, which includes responding to issues is also our cost we have to cover, especially when it’s about individual issues we don’t experience. This adds up and we are still a small company without any external VC funding and millions of dollars, so we have to be careful to manage the balance between making money and sponsoring others at our cost.
> 
> We hope that the new way of supporting BOA will be beneficial to everyone and will help to make it better and more capable, while making BOA project sustainable— it’s important difference, because we are not planning to make a profit on it, just to make it sustainable to keep it available for everyone.
> 
> Thank you and Happy New Year!
> 
> Sent with [GitHawk](http://githawk.com)


**Thank you** sincerely for your perseverance in keeping BOA operational despite the challenges you've faced. I want to express my apologies if my words may potentially cause any frustration. I fully acknowledge that there is a considerable amount I don't know and should strive to understand better.

I would be immensely grateful if you could kindly guide me and correct any misunderstandings I may have to prevent unintentional missteps.

Since 2012, I have relied on BOA for my sole blog. Once a year, I export my database + Drupal 7 data, format VPS, and reinstall BOA with a renewed SSL certificate annually.

In other words, I never use updaters as such because I have never managed to do it without messing up my website/installation. I imagine it's 100% my fault since most of what I configure I do by editing using the console out of desperation, and I understand that it's not the right way.

As this year I have Octopus installed (it hasn't always been like this), and I don't know if this can cause an automatic action to start after 30 days that might disable my only blog for not paying for the updater (something similar happened to me a few months ago, unexpected automatic update "issue: #1660").

I'm contemplating whether it's permissible to undertake a new minimal installation without Octopus and abstain from using the paid updater, solely relying on the installation process, with the inherent vulnerabilities of infrequent updates until the next reinstallation. Would this approach lead to the remote automatic disablement of my blog, or is it within acceptable bounds?

**TL;DR** Is it acceptable to perform a minimal installation for my sole blog without Octopus and without regular updates?

I sincerely appreciate your time and consideration in reading this. **Thank you**

**Comment by lexsoft00** [comment]
@omega8cc , I hope you reconsider your decision.

This is indeed disheartening news and may not be the most favorable path forward. I've always regarded this project as one that would remain free and open source indefinitely. It would have been beneficial to consider separating the projects into a community-based version and a paid version, enabling us to continue using BOA.

While I've done my utmost to recommend BOA and Omega8 to the Drupal community, the enforcement of this dual license may compel me to seek an alternative solution.

It would greatly help if you could provide more information about what will happen to our instances. Will we no longer be able to update them? Are our websites at risk of going offline after January 31st?

**Comment by leevh** [comment]
@omega8cc , I'm wondering what the status is for this change?  I just noticed this today and it's almost a month past the deadline but I don't see any info on licenses on the compare page or any evidence of a change to BOA.  It would be great to know the pricing structure so I can decide how to move forward.  Migrating sites to a new platform would be a painful undertaking, so the more notice the better.  I do appreciate your need for the change and all the hard work you've provided for free over the years.  Please keep us updated.

**Comment by omega8cc** [comment]
The dual licensing introduction has been delayed to provide in-depth analysis of pros and cons for everyone to see that it’s in your all best interest and not a way to make money by us. 

The basic licenses will be cheap and almost symbolic, so they don’t have the commercial purpose.

There will be several licenses levels to meet the needs of the community.

The intention is to simply gauge the interest in supporting the project before we conclude that it’s better to make it private if no one is willing to pay anything like no one was willing to pay anything for Aegir development, while silently leveraging both Aegir and BOA to build competing businesses.

It’s thus a test of whether it makes sense to spend more time on supporting community expecting us to work for free or not.

We have been deeply disillusioned after seeing so many benefit while doing literally nothing to support the project (not just BOA but Aegir) and we want to see how people will react when the project becomes dual licensed.

We are not looking for money but for clarity in this endeavor.

It’s just demoralizing and demotivating for everyone if one side is giving their precious time and effort for free while too many expect to have their business sponsored that way.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by omega8cc** [comment]
We will post details shortly, but we have considered your feedback and discussed this internally further which resulted with conclusions as follows:

BOA project will be maintained in four branches:

1. LITE which will remain completely free to use without any kind of license as it was from the beginning.

2. PRO which will be free to install but with paid license to run upgrades, with several license levels for extra support.

3. DEV which will remain public but will not be available to use without license even for install.

4. OM which will remain our private branch with some things we don’t use removed and some added, but generally simplified for easier maintenance and modern coding standards.

What’s then the difference between LITE and PRO? 

LITE will be updated less regularly, perhaps quarterly, with occasional updates to address security issues. It may not receive all new features from the PRO branch, but should be still better and way more reliable than BOA was in the last few years.

PRO will be actively maintained with monthly releases and new features.

That’s the plan. It’s not set in stone yet, so please comment if you have an opinion or idea to make BOA future Bryght (anyone knows that old name?)


<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by omega8cc** [comment]
BOA 5.2.0 has been released with new branches, but for now lite==pro anyway.

Enjoy!
