### ISSUE TITLE
Cloudflare proxy for Aegir Hostmaster site results in ERR_SSL_VERSION_OR_CIPHER_MISMATCH

### ISSUE THREAD

**Issue by fotiDim** [omega8cc/boa#1772]
My Aegir Hostmaster site is no longer accessible and I am getting `Unsupported protocol
The client and server don't support a common SSL protocol version or cipher suite. ERR_SSL_VERSION_OR_CIPHER_MISMATCH` in the browser when I try to access it. Is there any way to fix this? My hosted websites still function properly.

**Comment by fotiDim** [comment]
Nevermind, it was a misconfiguration in Cloudflare DNS. I needed to make an entry for the subdomain of the Hostmaster site in Cloudflare and set it as not proxied (DNS only).

**Comment by fotiDim** [comment]
Nevermind, it was a misconfiguration in Cloudflare DNS. I needed to make an entry for the subdomain of the Hostmaster site in Cloudflare and set it as not proxied (DNS only).

**Comment by fotiDim** [comment]
Reopening to figure out a more optimal solution...
I have narrowed down the root cause and it is because Cloudflare does not issue SSL certificates by default for [multi-level-subdomains](https://developers.cloudflare.com/ssl/troubleshooting/version-cipher-mismatch/#multi-level-subdomains). Based on [BOA docs](https://github.com/omega8cc/boa/blob/093bc072d12dbc3fd9f012b5d3138e136e9f698b/docs/INSTALL.txt#L53-L54) the hostname should always be a subdomain (e.g. `server.mydomain.org`) so by default we end up with `o1.server.mydomain.org` which leads to the aforementioned issue.

One way to mitigate this is to enable [Total TLS](https://developers.cloudflare.com/ssl/edge-certificates/additional-options/total-tls/).

@omega8cc I wonder if it is possible to change the hostmaster url to be a single level subdomain e.g. `o1.mydomain.org` or even to match the hostname i.e. `server.mydomain.org`.

**Comment by omega8cc** [comment]
Octopus is by definition designed for hosting multiple Aegir instances on the same server. It’s not a good practice to use main domain as hostname either, because it makes managing DNS updates restricted by minimal TTL enforced by registrars. That’s why we don’t plan to change this logic based on subdomains.

While you can’t use Cloudflare for wildcard DNS records, nothing stops you from creating dedicate DNS record for your Aegir control panel.

Alternatively just don’t use CF proxy only DNS. That’s also why having subdomains makes sense because you can separate CF settings for Aegir and other sites using the same domain.

Note that if you decide to use CF proxy, you can configure there the kind of certificate to accept, also self signed works.

As for enforcing SSL we don’t plan to introduce this and we believe it should be left to the site own configuration for HTTP headers, simply because otherwise you may lock yourself without ability to access the site until its SSL certificate is updated (which cannot be done automatically for example when you have an alias pointing elsewhere).

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by fotiDim** [comment]
> While you can’t use Cloudflare for wildcard DNS records

Since recently it is [doable](https://blog-cloudflare-com.webpkgcache.com/doc/-/s/blog.cloudflare.com/wildcard-proxy-for-everyone) even for free accounts.

> While you can’t use Cloudflare for wildcard DNS records, nothing stops you from creating dedicate DNS record for your Aegir control panel.

That is exactly what I've done. I have a separate A record for the Hostmaster site and it works as described above.

---

Given that the subdomain for the hostname is there to stay, would it be possible to change the hostmaster URL to a single level subdomain? Would creating an `o1.mydomain.org` alias on the hostmaster site be a reasonable solution?

**Comment by omega8cc** [comment]
It’s not suitable because everything is based on the host name and not domain, which can point elsewhere, including for email addresses reasons. We have tried that before and it only caused confusion and problems for users, so we also use the same logic on all our servers, where it further helps when you use the same domain in various locations and use the host name to easily locate the server.

Nonetheless we don’t say it’s not possible, it’s just something most people should avoid.

We don’t have any interest in changing this logic but if enough BOA users will buy licenses once available or submit the patches, we are happy to look into this further.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
