### ISSUE TITLE
Two problems in sites with "HTTP Basic Authentication"

### ISSUE THREAD

**Issue by Naurisr** [omega8cc/boa#1790]
There are two problems in sites which have "HTTP Basic Authentication" enabled in Aegir:
1. SSL certificates does not renews while Basic Authentication is enabled. I have to disable it temporarily to be able renew certificate.
2. Cron on these sites does not work when Wget method is used. I'm not sure, but I think it worked before upgrade to 5.2.0. Using Drush method cron works.

Is it possible to fix these issues somehow?

**Comment by omega8cc** [comment]
For SSL certificates to be renewed you can’t have http access control enabled unless you would also whitelist all remote IPs LE is using.

Not sure if cron should still work properly because while it’s using local requests, you can’t have any kind of proxy active like Cloudflare. It’s explained in the legacy documentation.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Naurisr** [comment]
I found a solution for first problem. Just added the **auth_basic off;** in **location ^~ /.well-known/acme-challenge** in file hosting_le_vhost.drush.inc. Now /.well-known/acme-challenge is publicly accessible for certificate generation
```
    $lines[] = "  ###";
    $lines[] = "  ### Allow access to letsencrypt.org ACME challenges directory.";
    $lines[] = "  ###";
    $lines[] = "  location ^~ /.well-known/acme-challenge {";
    $lines[] = "    allow all;";
    $lines[] = "    alias $aegir_root/tools/le/.acme-challenges;";
    $lines[] = "    try_files \$uri 404;";
    $lines[] = "    auth_basic off;";  // <---
    $lines[] = "  }";
    $lines[] = "\n";
```

**Comment by omega8cc** [comment]
Good idea! Committed.

**Comment by omega8cc** [comment]
Regarding cron, it will never run on sites protected like this because we now force wget method since Drush (8) method can't be used for current Drupal core anyway. This shouldn't be an issue, I think, because when the site is protected with global HTTP Auth, it's probably a test/dev site which shouldn't run cron anyway. If you are using site level HTTP Auth, so not via Aegir simple/global protection, then you can whitelist cron requests as you wish, I guess.
