### ISSUE TITLE
BOA Upgrade / Network interface Error

### ISSUE THREAD

**Issue by velpan** [omega8cc/boa#1792]
Is it ok to go from BOA 4.1.1.dev to the last version BOA 5.2.0 on a Jesie Debian system?

**Update**: I tried the command **barracuda up-lite** and I get the message

ERROR: BOA requires the classic network interface naming convention.
ERROR: Typically it should be eth0 and not ens3 systemd convention.

When I run the command **ip addr show** I get

1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether 96:00:00:10:66:4b brd ff:ff:ff:ff:ff:ff
    inet 159.69.93.15/32 brd 159.69.93.15 scope global eth0
       valid_lft forever preferred_lft forever
    inet6 2a01:4f8:1c1c:304e::2/64 scope global
       valid_lft forever preferred_lft forever
    inet6 fe80::9400:ff:fe10:664b/64 scope link
       valid_lft forever preferred_lft forever

Thank you for your support.

**Comment by omega8cc** [comment]
We always removed systemd on Debian, it’s not relevant here.

The problem is that Jessie is just way too old for smooth upgrade with BOA tools.

Currently Stretch is the oldest Debian version BOA supports for upgraded to Devuan.

Still, it’s perfectly possible to upgrade Jessie too, but on some hosts it may crash hard.

If you are not experienced enough to manage major OS upgrade manually to debug and fix issues, consider installing new BOA server and migrating all sites.

Alternatively you can request paid support to upgrade your legacy BOA server at omega8.cc/contact



<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by omega8cc** [comment]
@velpan Please pay attention to warnings displayed. Your network interface is fine, you just need to add something to kernel configuration as explained on screen.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by omega8cc** [comment]
To reiterate: you can run barracuda upgrade on Jessie, but it will fail to rebuild PHP, so you should use the option for major system upgrade to Stretch first — don’t use the auto-upgrade scripts. It will allow you notice and fix issues which are inevitable for Jessie. Once on Stretch you can auto-upgrade to Chimaera easily. Unfortunately we no longer have any Jessie server for testing, only Stretch is still tested.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by velpan** [comment]
Thank you for the info

**Comment by omega8cc** [comment]
@velpan Yes.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
