### ISSUE TITLE
Problems with one-time login link and mail retrieval after BOA installation 

### ISSUE THREAD

**Issue by OlegBesch** [omega8cc/boa#1797]
Hello!
I installed BOA 5.3.0 lts today on Devuan Chimaera (VDS 8 vCPU, RAM 12 GB, Storage 150 GB). The installation was successful, judging from the installer messages. 
However, first, after the installation process was complete, I never received any email to the email address provided during the installation. 
Secondly, when I copied the one-time login link from the console and clicked on it in my browser, I got the message "You have tried to use a one-time login link that has either been used or is no longer valid. Please request a new one using the form below." Attempts to restore the password to my e-mail address also did not lead to anything - no e-mails come. That is, I can't log in to my account for administration.
Can you please tell me if there is any way to generate a new one-time login link and what could be the problem with receiving mail?
Any ideas on this would be greatly appreciated.

**Comment by omega8cc** [comment]
New BOA has been released today, but we are still adding hot-fixes as usual post-release when it's possible to live-test everything, since during development we can test only the dev branch, so I would recommend to give it another 24 hours before trying it on your own server.

However, the one-time login link will not work anyway, because the cache is cleared afterwards.

Next BOA release will print this helpful info at the end of the installation process:

```
NOTE! The initial one-time login link will no longer work.
To access your Aegir control panel after the procedure is finished...
...please generate a new link by running the following command:

  su -s /bin/bash o1 -c "drush @hm uli"

Bye!
```

**Comment by OlegBesch** [comment]
Oh, I see! I'll probably reinstall the new BOA in a couple days then. It's just that in addition to the problems mentioned above, csf/lfd didn't install either. I just installed it separately myself. And when I boot the server it shows errors when starting rc.local and redis-server.
Thanks for the reply!
