### ISSUE TITLE
Question about http2 during today's up-lts (nginx failed to start afterwards)

### ISSUE THREAD

**Issue by EdNett** [omega8cc/boa#1798]
During today's barracuda up-lts nginx failed to resart with the following errors:
root@server1:~# service nginx status
Nginx Server... is NOT running. ... (warning).
root@server1:~# service nginx start
Starting Nginx Server...:nginx: [emerg] unknown directive "http2" in /var/aegir/config/server_master/nginx/pre.d/nginx_wild_ssl.conf:8

Commenting out the http2 line in the file produced the same error in both octopus instance 👍 
z_o1.fqdn_ssl_proxy.conf and for the o2 also, of course. 

Commenting out all of those (3 in total for our system with 2 octopus instances) #"http2 = on" lines allowed nginx to start again

My question is - This is on an older boa server which has been upgraded from strech step by step up through to chimera. Is this a bug or is there something wrong with our system?  A reboot and another barracuda up-lts did not modify those three files, so nginx had no problem restarting. Are they supposed to be commented out by default?

Thanks for the great up-lts which is working great!  Ed

Boa info more is here:  https://gist.github.com/EdNett/83a87d0c367fc5a92224f400247e97e3

**Comment by omega8cc** [comment]
We always recommend to wait a few days after release before upgrading any live server so we can catch and fix bugs which couldn’t be debugged before since dev branch is hundreds of commits ahead and is the only branch constantly tested. New release bringing everything from dev to LTS is coming later today.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
