### ISSUE TITLE
Unable to login as octopus.ftp user - python 3.9 installed, script calling python 3.12 error

### ISSUE THREAD

**Issue by EdNett** [omega8cc/boa#1816]
Unable to login as octopus.ftp user - python 3.9 installed, script calling python 3.12 error

  Skynet Agent v.BOA-5.4.0-lts on Devuan/chimaera welcomes you aboard

Traceback (most recent call last):
  File "/usr/bin/lshell", line 52, in <module>
    main()
  File "/usr/bin/lshell", line 38, in main
    userconf = CheckConfig(args).returnconf()
               ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/lshell/checkconfig.py", line 67, in __init__
    self.conf['config_mtime'] = self.get_config_mtime(configfile)
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/lshell/checkconfig.py", line 809, in get_config_mtime
    return os.path.getmtime(configfile)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen genericpath>", line 67, in getmtime
FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/etc/lshell.conf'

  
  server1:~# ls /usr/bin/python*
/usr/bin/python*     /usr/bin/python3-config@      /usr/bin/python3.5*
/usr/bin/python2@    /usr/bin/python3-futurize*    /usr/bin/python3.5m*
/usr/bin/python2.7*  /usr/bin/python3-pasteurize*  /usr/bin/python3.9*
/usr/bin/python3@    /usr/bin/python3-unidiff*     /usr/bin/python3.9-config@
server1:~#

boa info more : https://gist.github.com/EdNett/f9222e7f6a602c292485daf1b7dfb947

**Comment by EdNett** [comment]
I solved this on a test server (#1813), I believe, by upgrading pip
pip install --upgrade pip

and then 
pip install readline

for what that's worth

On this VM running just updated again (Sept 24 barracuda up-lts + octopus up-lts), there is no file /usr/local/etc/lshell.conf
python 3.12 is installed in /usr/local/bin along with pip3 and pip3.12

so I ran pip install --upgrade pip 
and then
pip3.12 install readline

and that did not work. Still testing.

So, I removed dh-python  and installed python-is-python2 (since that seemed to be working on the other server also in Chimera) and that didn't work either; so I reversed that and have decided to stop trying for the moment. 

I think I've got it! - I will create a symbolic link at /usr/local/etc/lshell.conf leading to /etc/lshell.conf. I think that will do it. I'll let you know. - and that did the trick.

To note: so I've got this older server which has dh-python installed and does not have python-is-python2 installed, and I have a much newer server which does have python-is-python2 installed and does not have dh-python installed - and both are on the exact same version of devuan chimera running the exact same version of boa-lts - and that is a little disconcerting.

**Comment by timlie** [comment]
Hi Ednett, can you explain in bit more detail what exactly fixed your issue? I have same issue with lshell.

**Comment by aDarkling** [comment]
pip install --upgrade pip
and then,
wget -qO- http://files.aegir.cc/BOA.sh.txt | bash

did the job for me.  Before, the bash routine had complained that ssl wasn't set up.

--------------------------------------
python3-pip is already the newest version (20.3.4-4+deb11u1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
WARNING: Disabling truststore since ssl support is missing
Requirement already satisfied: pip in /usr/local/lib/python3.12/site-packages (24.2)
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/pip/
WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/pip/
WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/pip/
WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can'WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/pip/
Could not fetch URL https://pypi.org/simple/pip/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /simple/pip/ (Caused by SSLError("Can't connect to HTTPS URL because the SSL module is not available.")) - skipping
WARNING: Disabling truststore since ssl support is missing
WARNING: pip is configured with locations that require TLS/SSL, however the ssl module in Python is not available.
Could not fetch URL https://pypi.org/simple/pip/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /simple/pip/ (Caused by SSLError("Can't connect to HTTPS URL because the SSL module is not available.")) - skipping
WARNING: Disabling truststore since ssl support is missing
WARNING: pip is configured with locations that require TLS/SSL, however the ssl module in Python is not available.
-----------------------------------------
