### ISSUE TITLE
SSL Certificates Not Renewing

### ISSUE THREAD

**Issue by g33k-g1rl** [omega8cc/boa#1817]
Hi there,

I just had an issue come up with several websites that are nondrupal which I am using the work around of creating a dummy site to get an SSL certificate.

Each site when I try to renew has this error:
`[hosting_le] The LE Certificate attempted creation failed in /data/disk/oct/tools/le/certs/mail.snrg.us warning
[hosting_le] Make sure that all aliases have valid DNS names pointing to your instance IP address. warning
[hosting_le] The alternative is to disable SAN mode for this site with empty ctrl file: /data/disk/oct/static/control/ssl-no-san-mail.snrg.us.info`

I confirmed the DNS information is correct (and the www alias too), but now none of the SSL certificates for these websites will renew. 

I tried creating a site in the same platform and enabling SSL, with the same error.

**Comment by omega8cc** [comment]
Can you post the result of `boa info` please?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by EdNett** [comment]
We have had this same problem for the last couple of days - probably for certificates expiring on or after thursday 19 september, I think.

**Comment by velpan** [comment]
Check the Verify site in Aegir Control Panel.
SSL renews during Verify procedure.
For me once, Verify can not run due to lack of Disk space (over 90% used)

**Comment by EdNett** [comment]
I don't know if this is pertinent, but on both of my servers, the letsencrypt logs in /data/disk/o1/log/  haven't been written to since august 13 2024 - I don't know what they are for, but that is the last lets encrypt log I can find. That is also the date of our last /var/log/nginx/date-error.log and the regular gzipped error.log.1-10 etc started being created again on september 11 and are still being created. (the ones for today sept 25 are large (6+MB - probably because I restarted nginx a few times to see if that was being done in the verify task - which I have run dozens of times also) - filled with nginx warnings: nginx: [warn] the "listen ... http2" directive is deprecated, use the "http2" directive instead
nginx: [warn] protocol options redefined for 0.0.0.0:443

The only difference between our server on which this works and th one on which it doesn't is that the non-working server (in the sense that it isn't renewing LE certs has python-is-python2 installed and does not have dh-python installed; while the server which successfully renews the certs has the opposite.

For the non-working (re LE renewal generation) server no new certs are being placed in the /data/disk/fast2/tools/le/certs/domain.com/ directory, even though a site verify task (and I have tried disabling ssl, verifying, and then re-enabling again and re-verifying) shows that new certs are being generated. The ownerships and permissions of the le/certs folders are all correct as compared to the server which works. I can't seem to find a dedicated le log.

Thanks @velpan for your input but ther is plenty of disk space and firewall is not blocking either.

**Comment by EdNett** [comment]
Hello,  I have found an error in the let's encrypt certificate renewal (regeneration) process which is causing certificate renewal to fail, and also I have a query on somthing else happening with LE on the site verify task.

The relevant part of the site "domain.com" verify task is here:

https://gist.github.com/EdNett/0ed06e457b98c25f44facaf06ff4484a

Please see line 151 for the error ("type": "urn:ietf:params:acme:error:malformed",   "detail": "JWS verification error",   "status": 400)

and on line 157 I see that a site verify task for one domain is causing  13 different siet certificates to be moved to the archive folder - can this be intended behavior?

If you want me to file a separate support request for this issue, please let me know. It is probably related, I guess.

Best,

Ed

**Comment by omega8cc** [comment]
@EdNett Please refrain from posting comments in this thread and avoid hijacking discussions initiated by others. Kindly open a new thread for your own topic to keep the conversation organized and remove all your comments here.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by omega8cc** [comment]
@g33k-g1rl Please be aware that this is an old trick which is not tested anymore. It may still work, but only if your custom vhosts don’t confuse Aegir and LE extension on Verify and during auto-renewal by the BOA backend tasks. So it really depends on how your custom vhost are named (filenames) because it should make them loaded before vhosts Aegir manages.

**Comment by omega8cc** [comment]
@g33k-g1rl Please post your custom vhost example so we could take a look.

**Comment by g33k-g1rl** [comment]
@omega8cc Sorry for the delay! The workaround was working for several months, but just recently stopped working after the last upgrade I think.

Here is my BOA Info:
[boainfo.txt](https://github.com/user-attachments/files/17176877/boainfo.txt)

Here is the vhost with the actual information:
[a1-pm.snrg.us--CDN.txt](https://github.com/user-attachments/files/17176880/a1-pm.snrg.us--CDN.txt)

Here is the dummy site vhost:
[pm.snrg.us.txt](https://github.com/user-attachments/files/17176881/pm.snrg.us.txt)

**Comment by g33k-g1rl** [comment]
Here is a screenshot showing the DNS information set correctly as well:
![brave_screenshot_secure rosehosting com](https://github.com/user-attachments/assets/3e89d042-2f89-4305-9404-fe8d3c3c32e5)

**Comment by omega8cc** [comment]
Please add the required `location ^~ /.well-known/acme-challenge` complete location in your own vhost to make SSL / LE certs renewal possible.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by g33k-g1rl** [comment]
Thank you so much! That fixed the issue. You are the best!

Here is the code in case anyone finds this thread

  ###
  ### Allow access to letsencrypt.org ACME challenges directory.
  ###
  location ^~ /.well-known/acme-challenge {
    allow all;
    alias /data/disk/INSTANCE_NAME/tools/le/.acme-challenges;
    try_files $uri 404;
  }

**Comment by g33k-g1rl** [comment]
Ok I'm now getting the same issue on a different instance on a website that isn't a dummy site. I confirmed the acme-challenges code is included in the vhost file. 

[fellowshipoffiction.com.txt](https://github.com/user-attachments/files/17252530/fellowshipoffiction.com.txt)

Here is the DNS information:
![brave_screenshot_secure rosehosting com](https://github.com/user-attachments/assets/56324070-5685-4dda-b5eb-a2513093cdb2)

**Comment by omega8cc** [comment]
@g33k-g1rl Please check the recent verbose log in `/var/xdrago/log/daily/*` to determine the culprit.

**Comment by g33k-g1rl** [comment]
I tried renewing the certificate again to see if I could get it to print to the log. This is the only thing in the log:

==> /var/xdrago/log/daily/daily-241004-041501.log <==
#
Processing shortlink.snrg.us
 + Checking domain name(s) of existing cert... unchanged.
 + Checking expire date of existing cert...
 + Valid till Dec 23 06:54:04 2024 GMT (Longer than 30 days). Skipping renew!
No new LE cert for hostmaster shortlink.snrg.us to copy
Done for /data/disk/shortlink


_DEL_OLD_EMPTY_PLATFORMS is set to         7 days on /var/aegir instance

**Comment by g33k-g1rl** [comment]
I deleted all the aliases for the domain, verified the site and it renewed the SSL certificate. I am going to add the aliases back after careful checking of the DNS records.
