### ISSUE TITLE
I am finding an "o2.admin" user in "/etc/group-", "/etc/passwd-" "/etc/gshadow-" and "/etc/shadow-" 4 extra files on our boa server

### ISSUE THREAD

**Issue by EdNett** [omega8cc/boa#1823]
Hello on Monday October 14 2024 17:30 UTC

I am finding an "o2.admin" user in "/etc/group-", "/etc/passwd-" "/etc/gshadow-" and "/etc/shadow-" 4 extra files on our boa server!

This is in addition to the four normal required "/etc/passwd" etc files (the ones without the dash at their end.

Is this from your side ?  I didn't put those extra files there with the o2.admin user - and I need to know what is going on. This is the second of our 3 servers (one vps test, etc) that this has happened to, and all of a sudden today our principal platform on this server won't verify - and there is very strange behavior - sites no longer working, etc.

Has there ever been an o1.admin or o2.admin user with a path of  .../ltd-shell  created with a boa update ?

Our normal o1.ftp adn o2.ftp users have as path /usr/bin/mysecureshell

IS there a change from mysecureshell to ltd-shell ?

Are these four modified copies of /etc/passwd, group, gshadow and shadow somehow needed for a new boa? 

I just really need to understand what has happened here, please.

I trust that it is clear that no-one who works for BOA has the right to enter into any of our servers or vps for any reason, right? Do I need to think that I've been hacked ?

Best,

Ed

**Comment by omega8cc** [comment]
It seems there may be a misunderstanding regarding how Unix/Linux systems work. Please take the time to familiarize yourself with the basics, as it is a fundamental requirement for using BOA. It's crucial to have either the necessary system administration skills or the willingness to learn, rather than making assumptions that could be seen as offensive.

We take security and trust very seriously. While it is technically possible to use the BOA self-update tools to assist with access issues by adding our SSH keys, this would only be done if explicitly requested and under a paid, non-standard service agreement. We would also require the system hostname or public IP address to proceed in such a scenario.

That being said, it's inappropriate to suggest that we would ever perform such actions without your permission. If there is a trust issue, we recommend reconsidering your use of BOA, as a healthy trust relationship is essential for any support or collaboration.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
