### ISSUE TITLE
Barracuda up-lts locked me out - can't connect via ssh

### ISSUE THREAD

**Issue by FemPriv** [omega8cc/boa#1838]
Hello,

On this VPS which was updated to Daedalus and to which I needed to add solr, I ran an barracuda up-lts and now I can't login via ssh. I can't give you the results from boa info, but it was Devuan Daedalus with php 7.4 to 8.3. What can I do to get an ssh access, please? I tried rebooting at the server provider, but that doesn't work.

I did receive an email - a log about a failed Barracuda update, and the errors in it are:
https://gist.github.com/FemPriv/e97fb857df361b907bfee44cd151924a

Boa info was at the end of the email-log: https://gist.github.com/FemPriv/6de47b6527334e605b56a1813e7a5cfb

Thank you.

**Comment by ColdSunERA** [comment]
Check your /etc/network/interfaces  and verify there's an eth0 entry

**Comment by omega8cc** [comment]
Hello,  

When a Barracuda upgrade fails during the Aegir Master Instance upgrade step, it may cause issues with restoring the expected permissions in the cleanup step. However, this should not prevent you from accessing the server via SSH.  

To avoid such issues, we recommend running the following instead of a full Barracuda upgrade, unless there is a significant update to Aegir/Hostmaster:  

```  
barracuda up-lts system  
```  

If you’re still unable to access the system, it might be related to your SSH keys. Usually, removing the corresponding entry in `~/.ssh/known_hosts` on your computer resolves the issue.  

If the problem persists, you may need to access the system via the remote console provided in your VPS control panel or use rescue mode to inspect the system further.  

Please let us know if you need any additional assistance.

**Comment by FemPriv** [comment]
After a few up-lts (barracuda and octopus) it works fine now.

Thank you.
