### ISSUE TITLE
Only PHP 8.3 is being allowed now. We need 7.4 and 8.1, too.

### ISSUE THREAD

**Issue by EdNett** [omega8cc/boa#1850]
Hello,

I see that barracuda up-lts is changing php_multi from "7.4 8.1 8.3" to "8.3" only. We need 7.4 and 8.1 in order to run drupal 7 sites and try to migrate them to drupal 10.  Are you cutting off access to 7.4 and 8.1 - as in no further installs - no upgrades ? Please let us know.

Thank you.
Ed

boa info here:  https://gist.github.com/EdNett/561d2335a6d833493761a29d9b77831b

**Comment by omega8cc** [comment]
No, we don't enforce single PHP version. Please make sure you follow the instructions in https://github.com/omega8cc/boa/blob/5.x-dev/docs/INSTALL.md

**Comment by omega8cc** [comment]
Note that the upgrade may reduce the versions to those actually used by hosted sites if you have run major OS upgrade before, because it runs the `barracuda php-idle disable` automatically. To bring back any inactive versions you need to explicitly specify the upgrade mode with either `php-min` or `php-max` as explained in the docs. You can also use the `barracuda php-idle enable` command to reactivate any inactive PHP versions.

**Comment by EdNett** [comment]
Thank you for this explanation. I see that I will have to read all the docs again, since things have changed a little.
