### ISSUE TITLE
Local BOA install sets nameserver to itself and fails to resolve it's own hostname to an ip

### ISSUE THREAD

**Issue by karudonaldson** [omega8cc/boa#347]
How to prevent resolveconf from setting localhost/127.0.0.1 as the primary resolver, or perhaps the question is how to set an external dns nameserver as primary resolver so it won't be overridden at install time?

**Comment by omega8cc** [comment]
This should be indirectly fixed in this commit: https://github.com/omega8cc/boa/commit/7477f60cf42be24855bb616502f3371b4d023666

For context please check also:
https://github.com/omega8cc/boa/blob/2.3.x-dev/docs/ctrl/system.ctrl#L68
https://www.drupal.org/node/2007990#comment-9127905
#380

That said, we should still get the localhost mode to work out of the box, with no extra tricks involved.
