### ISSUE TITLE
Provide default value for composer_manager_vendor_dir variable

### ISSUE THREAD

**Issue by andytruong** [omega8cc/boa#385]
More and more modules start using composer_manager to manage dependencies. But by default the vendor dir is `./sites/all/vendor/`, which will conflict the multi-sites. Can we just provide default value in settings.php to override module default's value?

```php
<?php
$config['composer_manager_vendor_dir'] = 'sites/example.com/vendor';
```

**Comment by jerbob92** [comment]
I'm pretty sure this commit broke some sites for us temporarily (because the vendor dir suddenly changed after we updated, so we had to redownload the composer packages).

It also broke 1 site permanently because ```'sites/' . $_SERVER['SERVER_NAME'] . '/vendor'``` did not match the actual site folder.
The folder should have been ```sites/www.example.com/vendor``` but since ```$_SERVER['SERVER_NAME']``` was example.com, it became ```sites/example.com/vendor```, which does not exist.

**Comment by omega8cc** [comment]
You can always override this in either local.settings.php or /data/conf/settings.global.inc

**Comment by omega8cc** [comment]
Also, `$_SERVER['SERVER_NAME']` should always point to the existing directory thanks to this fallback:

````
/**
 * Use Aegir/BOA specific variable as a reverse fallback
 */
if (isset($_SERVER['MAIN_SITE_NAME']) && !isset($_SERVER['SERVER_NAME'])) {
  $_SERVER['SERVER_NAME'] = $_SERVER['MAIN_SITE_NAME'];
}
if (!isset($_SERVER['MAIN_SITE_NAME']) && isset($_SERVER['SERVER_NAME'])) {
  $_SERVER['MAIN_SITE_NAME'] = $_SERVER['SERVER_NAME'];
}
````

The only edge case (known) is when you are using alias redirect in Aegir and it points to the alias other than the main site name. It is a bad idea to use this for www/non-www redirects.

**Comment by jerbob92** [comment]
I know I can override, but:
 - It took me quite some time to figure out BOA suddenly configures composer_manager, I'm not really sure that's something you even want to take care of in BOA.
 - It shouldn't do a wrong/site breaking override by default.

That specific site indeed uses the alias redirect and it points to the "Automatic domain aliases" and not the "Domain name". So your suggestion would be to clone the site to have the "Domain name" without the www part?
Isn't there some way BOA can know the actual site dir? Everything else works just fine.

**Comment by omega8cc** [comment]
BOA is a pretty invasive stack by design. You really need to read the changelog before running the upgrade to avoid such surprises.

The problem with false `SERVER_NAME` forced by Aegir (there is nothing BOA specific here) is known and a bit tricky to avoid.

We have added custom `MAIN_SITE_NAME` header in Provision to stop relying on possibly fake `SERVER_NAME`, so maybe we should ignore `SERVER_NAME` and always set it to `MAIN_SITE_NAME` in global.inc, as we do in Provision.

**Comment by omega8cc** [comment]
Related issue: https://www.drupal.org/node/2358977

**Comment by jerbob92** [comment]
Agreed, we should have read the changelog.

If ```MAIN_SITE_NAME``` is always correct I think it's indeed better to use that for the composer_manager config dir. 
Composer Manager shows really weird behaviour when it can't find the given directory which makes it hard to find the problem.

**Comment by jerbob92** [comment]
Wow, thanks for the quick fix and the fast replies! :+1:
