### ISSUE TITLE
Github post-receive hook to automatically pull code on a git push

### ISSUE THREAD

**Issue by jlyon** [omega8cc/boa#439]
Is there a way to set up my barricuda server so that my git repos automatically 
pull when I push code (like with Acquia and Pantheon)? I am using Github, so 
it could just be a little script that receives a Github post-receive hook 
(https://help.github.com/articles/post-receive-hooks).

I have had success with https://github.com/A21z/node-cd on another server I 
manage myself and have run into php scripts that do the same.

We're looking for ways to limit access/make things more efficient for a 
growing team.

**Comment by Amstercad** [comment]
Here's <a href="https://stackoverflow.com/questions/10728824/how-to-access-a-private-github-repository-from-aegir-through-drush-make-on-aws">a simple way to create a new Aegir Platform, using a make file, effectively by copying a repo from Gitlab</a>. Using Github wouldn't be so different. Search for the word 'Gitlab' on the page, to find the answer I am actually referring to.

Bitnami offers <a href="https://bitnami.com/stack/gitlab/installer">a dead-simple virtual machine for downloading, free</a>, with both Gitlab & Gitlab CI well integrated.

Or for another perspective, the developer behind <a href="https://www.drupal.org/project/devshop">Devshop</a> has written Aegir modules and functionality for pulling and syncing with your own repo hosted either on your own Gitlab server, or if you are allowed to push, then to a public Github repo.

Devshop on the LAN perhaps could integrate with BOA on a public host like Linode or Digital Ocean. Once Devshop migrates a website to Staging using GIT, Gitlab CI can kick off a runner that creates a new Aegir Platform from a BOA make file/git repo from GitLab, ...then starts something like <a href="http://fourword.fourkitchens.com/article/testing-drupal-casperjs">Casper.js</a> for functional-testing on the production BOA server. Once a version of a site passes all its tests, it should be ready to go into public Production next.

At the moment I'm busy working to integrate <a href="https://github.com/samrocketman/gitlab-mirrors/blob/master/docs/installation.md">gitlab-mirrors</a> to make for a nice CI workflow.

Ideally, prior to creating your own repo branch, you'd install gitlab-mirror on the gitlab server. 

<blockquote>gitlab-mirrors creates read only copies of remote repositories in gitlab. It provides a CLI management interface for managing the mirrored repositories (e.g. add, delete, update) so that an admin may regularly update all mirrors using crontab. It operates by interacting with the GitLab API using python-gitlab3.</blockquote>

Currently I use drush rsync and drush sqlsync and not git, to sync websites across servers, and these are my notes as I've worked to make improvements.

**Comment by Pls** [comment]
+1, this would be a big plus for getting right workflow.

**Comment by omega8cc** [comment]
This will work once we upgrade to Hostmaster 3.x + new contrib. Another option is to add Aegir fork support (OpenDevShop)

**Comment by Pls** [comment]
OpenDevShop looks really interesting addition for BOA, we should create new issue and talk with community what they think about it.

**Comment by omega8cc** [comment]
Feel free to open fresh issue then. Previous DevShop related issues:

https://github.com/omega8cc/boa/issues/720
https://github.com/omega8cc/boa/issues/473
https://www.drupal.org/node/1935810

**Comment by omega8cc** [comment]
BOA now comes with many variants of codebase management workflows thanks to included by default:

https://www.drupal.org/project/hosting_git (not enabled by default)
https://www.drupal.org/project/hosting_deploy (enabled by default)
