### ISSUE TITLE
[monitor] Skip fpmcheck for high traffic

### ISSUE THREAD

**Issue by pricejn2** [omega8cc/boa#442]
Perhaps we should not run `/var/xdrago/monitor/check/locked &fpmcheck` for high traffic systems.

**Comment by Pls** [comment]
Can you guys comment on what is considered high traffic in visitor numbers per second/minute/hour/day? Perhaps documentation about it would be useful too.

**Comment by omega8cc** [comment]
> Can you guys comment on what is considered high traffic in visitor numbers per second/minute/hour/day? Perhaps documentation about it would be useful too.

It depends more on the machine and network performance.

We host some sites which generate 600-900 Mb/s traffic 12-18/24, effectively saturating single machine network connection, so the page views rate is just completely crazy (just page views, no downloads) but thanks to various tweaks we have implemented in BOA by default, the load on the machine is at about 25-35 % of its max power, on an average.

Still, it is a high traffic example, because if you will try to purge all Speed Booster caches and restart Redis at the same time, the load will immediately go through roof, at least until the caches are warmed again.

So, by high traffic we would consider traffic which has the power to kill the machine if you will disable both Speed Booster and Redis.=

**Comment by Pls** [comment]
Ok, thanks for detailed explanation. So, in theory if we have machine, which could be killed by visitors without any caching, then we should totally consider adding empty /root/.high_traffic.cnf file? Are there any drawbacks of having this file - longer services problem detection or etc.?

**Comment by omega8cc** [comment]
No drawbacks, it is safe to use.
