### ISSUE TITLE
forbidden shell escape: echo ZSH_VERSION

### ISSUE THREAD

**Issue by ar-jan** [omega8cc/boa#504]
It seems there's still a problem with RVM (after #496), on a clean install with 2.3.6.

I'm following https://omega8.cc/how-to-use-rvm-to-install-compass-tools-329. Some time after creating ~/static/control/compass.info with o1.ftp, I get this Shell Escape Alert by email:

`2014-11-21 15:55:09,368 (o1.ftp): *** forbidden shell escape: echo ZSH_VERSION`

Then (after waiting some more), RVM seems to be installed correctly (e.g. doing `rvm` shows the help), but doing `rvm all do gem install --conservative compass` doesn't do anything, it just finishes without any output.

**Comment by omega8cc** [comment]
Is this still an issue?

**Comment by ar-jan** [comment]
When using "CSS" in _XTRAS_LIST it was no longer an issue, I haven't checked again to see what happens when you try to install rvm without this setting. Would it be useful to try that again?

**Comment by omega8cc** [comment]
OK, thanks for the update. If it works fine with `CSS` added to `_XTRAS_LIST` first, then we can consider the problem fixed, I hope. Thank you!

BTW, we can't automate this further, because it would require triggering a system-wide installation with root privileges initiated via user-land control file, which would be just against security good practices.
