### ISSUE TITLE
Add the Lightning Distro to Octopus

### ISSUE THREAD

**Issue by rlnorthcutt** [omega8cc/boa#525]
https://www.drupal.org/project/lightning

This is a newish distro built by Acquia and intended to be a base platform for new site builds. It pulls in some of the Spark features (responsive admin menu, and other fixes), has Panels IPE out of the box, Workbench, a full Media/file system, and lots of other goodies. The base theme is Zurb Foundation.

**Comment by omega8cc** [comment]
This distro looks interesting, but comes with some issues which need to be fixed before we could add it. Namely, it depends on several Drupal core patches, so it is not going to work with our D7 core version out of the box - see the current patches list: http://cgit.drupalcode.org/lightning/tree/drupal-org-core.make

Next, the test build referenced in the distro failed: https://api.travis-ci.com/acquia/lightning.svg?token=fkKCDWeX7fUCfybPUjJb

Next, it comes with some contrib modules w/o proper version included, so they throws errors / false "Not supported!" alarms - at least for Colorbox and Lightning Features.

Next. the Colorbox seems to come with too new/not supported library version, because it throws  this error:

>>> Colorbox plugin Not detected: At least 1.3.21.1
>>> The version of the Colorbox plugin library could not be detected. You need to download the Colorbox plugin, extract the archive and place the colorbox directory in the sites/all/libraries directory on your server.

Adding the library copy to sites/all/libraries doesn't help, so it is probably a version mismatch.

Not sure if we can ignore those problems, but at least because it needs a few core patches, we can't include it without prior testing how these patches could affect other supported distros.

This needs more work.

**Comment by Aciid** [comment]
Just gave this platform a go. Looks very nifty and feature packed, quite like what Spark is for Drupal 8. This is also an Acquia curated platform that includes tools to start rapidly building your site, so it serves you a double purpose. Fast building, great set of tools to start publishing with.

**Comment by macmladen** [comment]
I think it is more like a Drupal demonstration than useful platform. It has just too many modules to be useful as a starting point and it was really demanding even to set up in local. It could be that it will be demanding to integrate and yet not too useful (I'd rather see some other popular distributions like Opigna or FarmOS).

**Comment by ryanhanau** [comment]
+1 for adding it to BOA.

**Comment by rlnorthcutt** [comment]
@macmladen is correct. Lightning in D7 is (and will most likely remain) more of a demonstration distro. That being said, the D8 version is intended to be a stable distro that can be used as the foundation for building sites. The Lightning team is also driving alot of development, so its a good project to watch.

Its currently in beta, so not ready for prime time use... but its a good one to keep an eye on. Might be a solid distro for D8 once you start adding those in the not to distant future.

**Comment by omega8cc** [comment]
Thank you all for the feedback! The problem with Drupal 8 is that it doesn't support symlinked core, so we can't easily provide it as a built-in platform (yet). This obviously affects all D8 based distros.

**Comment by rlnorthcutt** [comment]
The latest version of D8 Lightning works great on install, with one exception: they put the profile in "/profiles/contrib/lightning" by default, and Aegir can't see the profile. Once I move it to "/profiles/lightning", its fine.

Considering the way D8 deals with profiles, this may be something to keep in mind.

**Comment by colans** [comment]
This is a core Aegir issue.  See [Cannot find profiles beneath top-level directories](https://www.drupal.org/node/2650290).

**Comment by omega8cc** [comment]
Closing because it's included since BOA-4.0.1
