### ISSUE TITLE
Master instance offline after upgrade

### ISSUE THREAD

**Issue by mindi1** [omega8cc/boa#530]
I installed BOA a few days ago on my vps at Linode. Installation went smoothly. No errors or warnings. BOA is installed on a clean Debian 7 installation. DNS is also working. I have added all records mentioned in INSTALL.TXT. Yesterday I got an email saying there's two 2 Debian package update(s). I logged in from root and entered this command.

>barracuda up-stable system

Installation was a success, I got that in my email. But when i visit master.mydomain.com; I see site offline message. I found out it cant establish a database connection. I haven't tried to change any password before, I'm using the generated password. I have tried this on a clean BOA installation without any changes/sites added to anything and I come across the same message. 

Any idea why this is happening?

**Comment by EdNett** [comment]
Might want to look at:
https://github.com/omega8cc/boa/issues/605  - current boa 240 is not working and puts the master instance offline. There are also HUGE load spikes reported (which are probably false reports) that I have had to work around by setting the CPU_MAX to 100, etc. (this on both a new dedicated server AND a vps that have only 1 test site on them)!

There is something very wrong here - first the connection to the db was attempted on the ipv6 address, and failed. SO I removed the IPv6 address from /etc/hosts, and now it is trying to connect to mariadb on the ipv4 instead of the localhost.  Why isn't this problem being taken seriously?
