### ISSUE TITLE
AllowedUsers in /etc/ssh/sshd_config

### ISSUE THREAD

**Issue by BrianGilbert** [omega8cc/boa#535]
While creating a new Octopus instance is it possible for the user to get added to AllowedUsers in /etc/ssh/sshd_config? To only allow login for specific usernames..

**Comment by omega8cc** [comment]
This should be left for system admin to manage. I don't see any reason to make it a BOA feature, especially since by default all new accounts must start with password based access before they can add SSH keys etc. I would say that for non-standard use case, like when you don't have untrusted users on your system anyway, it should be easy enough to manage custom access restrictions outside of BOA managed settings.

If you could propose some scenario which could benefit other BOA users, feel free to reopen.
