### ISSUE TITLE
Load investigation suggestions

### ISSUE THREAD

**Issue by petrowsky** [omega8cc/boa#558]
This isn't specifically a bug or issue, but rather a request for suggestions.

It may be BOA related since I'm running BOA on the affected box and it auto-updates, but I've seen a significant increase in CPU load in the last 30 days and since I'm pretty much a less advanced sysadmin I'm having a hard time troubleshooting.

I posted info and an image of cpu use on the BOA groups here.

https://groups.drupal.org/node/453818

Feel free to close the issue if this is non relevant. I was thinking the label would be type:question.

**Comment by omega8cc** [comment]
Two suggestions:

1. https://twitter.com/omega8cc/status/538371551960522752

2. What happens to the average load if you disable system cron temporarily?

**Comment by omega8cc** [comment]
We have received an almost identical report related to BOA hosted on Linode.

Your CPU usage stats:
[linode1](https://groups.drupal.org/files/cpu_load.png)

The other BOA server on Linode stats:
[linode2](https://groups.drupal.org/files/linode2.jpg)

The problem is that we haven't seen such pattern on our own and other non-Linode servers. This could suggest that it is Linode specific issue.

**Comment by petrowsky** [comment]
Well, in my particular case I'm now guessing something was related to my java Confluence install. In order to assess normal load at idle, I spun up a new Linode and installed BOA there. Given my box is normally quite low on the traffic side of things, I think this may be a non BOA issue - but it is interesting.

It does look like the second picture above shows the same jump in cpu use, at the same relative time, if you take out the traffic spikes. Here are some pictures of my box 1 and now box 2. Does a 20% idle cpu use on new, no traffic box seem high?

![linode-1](https://cloud.githubusercontent.com/assets/96553/5724434/63aee39c-9b00-11e4-973a-ccc46eba5c8c.png)

![linode-2](https://cloud.githubusercontent.com/assets/96553/5724447/72b73aa6-9b00-11e4-97e5-23b33831640f.png)

**Comment by omega8cc** [comment]
Hmm, interesting.

Yes, some load is expected because there are backend/Provision tasks running all the time.

This may need further observation, but I suppose that on any VPS with strictly limited resources like CPU and I/O, the faster task scheduler could cause this affect.

It was introduced in this commit:
7226a409eb6f5048a82b0e5236eb8ca808ca557c

We have later made it optional, so now it requires control file:
aa85ab46f39ceae9cdad0dd85c27d0605dc730ac

This old behaviour has been re-introduced today, so if the load will go down for folks on Linode, it will prove that the fast scheduler is not a good idea on too limited VPS systems, like those provided by Linode.

**Comment by omega8cc** [comment]
We have documented this feature in this commit: 9ba7fe60b3d0cb714ec31e1a102240a8e4673c77

**Comment by petrowsky** [comment]
Load on a fresh box with no traffic is pushing pretty high with cron running. I stopped cron and got an obvious reduction. Here's htop output without cron then with. One thing that seems to happen is it will start out on the lower end of things then increase over a bit of time. Once it increases in cpu use it will stick there.

	1  [|                                                                  0.7%]     Tasks: 45, 76 thr; 1 running
	2  [                                                                   0.0%]     Load average: 0.02 0.12 0.19 
	3  [                                                                   0.0%]     Uptime: 1 day, 00:03:44
	4  [                                                                   0.0%]
	Mem[|||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||724/4002MB]
	Swp[                                                                0/511MB]

Shortly after restart

	1  [||                                                                 1.3%]     Tasks: 58, 76 thr; 2 running
	2  [|                                                                  0.7%]     Load average: 0.13 0.11 0.15 
	3  [|                                                                  1.3%]     Uptime: 1 day, 00:09:49
	4  [|                                                                  0.7%]
	Mem[|||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||728/4002MB]
	Swp[                                                                0/511MB]

**Comment by omega8cc** [comment]
The `Load average: 0.13 0.11 0.15` is pretty much nothing. Where do you see the high load here?

**Comment by petrowsky** [comment]
Yes, I know that is low load. It's actually no load relative to 4 cores. I posted it as a relative reference to running cron versus no cron. It's not there to show actual load from traffic or app metrics. It's just there to make note of what xdrago is consuming in terms of cpu.

**Comment by omega8cc** [comment]
I think it is a bug if BOA generates constantly high load, and if this is reported by more than 3 people as starting at the same moment. I just suspect that it is related to updated Provision tasks scheduler speed but without updating advanced cron module, which comes with related updates in HEAD.

**Comment by karudonaldson** [comment]
Have to admit I'm seeing this also.  Generally it occurs after a system upgrade, then re-occurs for a couple of days following that upgrade.  After approximately 4-5 days it seems to settle down again.

**Comment by omega8cc** [comment]
OK, we need to figure it out before 2.4.0 release then, to make sure we don't introduce some unidentified regression.

**Comment by EdNett** [comment]
I am also seeing extremely high loads (could these be false reports?)

For example (vmstat showed almost no memory in use and only an xdrago find command in order to set permissions on the static platform modules and themes - of which there are hundreds, using 21% of cpu), on a powerful server:

Time:                    Thu Jan 29 03:00:17 2015 +0100
1 Min Load Avg:          154.80
5 Min Load Avg:          34.54
15 Min Load Avg:         11.46
Running/Total Processes: 8/261

**Comment by omega8cc** [comment]
Still not sure what could cause this, but we have forced BOA agent to disable _PERMISSIONS_FIX by default, since it is most likely the culprit affecting weak VPS systems: https://github.com/omega8cc/boa/commit/0e195697c45963b2d680d7c71b184e13bce0ccae

**Comment by omega8cc** [comment]
Obviously the _PERMISSIONS_FIX thing can't cause high load as shown in the original bug report, but it could still cause a load spikes for a few hours on a weak VPS system with too limited I/O performance.

**Comment by omega8cc** [comment]
We couldn't reproduce this anywhere after changing both heavy system task to NO by default:

https://github.com/omega8cc/boa/commit/228f642bd903d02a2656032a5fd5747aa7a39faa
https://github.com/omega8cc/boa/commit/0e195697c45963b2d680d7c71b184e13bce0ccae

Feel free to reopen if you could reproduce the problem with BOA-2.4.0 once released or with current head.
