### ISSUE TITLE
Cache warmer for nginx microcaching (Speed Booster)

### ISSUE THREAD

**Issue by Pls** [omega8cc/boa#582]
Found https://www.drupal.org/project/cache_warmer module, which does cache warming thru drush command. As I understand the concept is to keep microcaching primed all the time, so that every anonymous user gets page from microcaching (As BOA callts it Speed Booster). Generally, I see benefits of having this system - system can potentially handle more anonymous traffic. Of course, priming cache for all pages will need more disk space on /var/lib/nginx/speed directory, but that's not big deal.

I know that Speed Booster TTL is hardcoded to 10 sec, but can easily be adjusted with site INI file, to something like 5 minutes. Having said that, is this good practice to setup this module for priming Speed Booster (microcaching) ? On downside, anonymous users will have to wait the configured TTL to see updated content.

Does this module fit into BOA system with added crontab running for priming Speed Booster cache?

**Comment by omega8cc** [comment]
No. For the same reason we have blocked Boost crawler previously. It is kind of logic error, in my opinion. If you have so little audience that you need a crawler to warm the cache, then you don't really need the crawler, because you have enough power to serve the site fast enough even for not yet cached requests. If you have so big audience that performance and load spikes are real concern, then you also don't need crawler, because your audience warms your cache optimally. It seems to be a solution for non-existent problem.

**Comment by Pls** [comment]
Ok, that makes good point. Thank you, for detailed answer on this one.
