### ISSUE TITLE
Erronious fix_locales function in system.sh.inc script - fix provided - relates to issue 506

### ISSUE THREAD

**Issue by EdNett** [omega8cc/boa#583]
This is asking you to fix a script and relates to issue https://github.com/omega8cc/boa/issues/506

Hello,

I think there is something wrong with your script:
https://github.com/omega8cc/boa/blob/master/lib/functions/system.sh.inc
on lines 502 and 503: (I added the 2 line numbers and provided a fix, below, substitutung a # for the misplaced ASTERISK, which doesn't appear in these comments when saved.): - so the system up doesn't find that my locales are BROKEN when they are not:

#
Fix locales.

fix_locales() {
if [ -e "/etc/ssh/sshd_config" ]; then
SSH_LC_TEST=$(grep "^AcceptEnv LANG LC" /etc/ssh/sshd_config 2>&1)
if [[ "$SSH_LC_TEST" =~ "AcceptEnv LANG LC" ]]; then
DO_NOTHING=YES
else
sed -i "s/.AcceptEnv.//g" /etc/ssh/sshd_config
echo "AcceptEnv LANG LC" >> /etc/ssh/sshd_config
fi
fi
if [ -e "/usr/etc/sshd_config" ]; then
SSH_LC_TEST=$(grep "^AcceptEnv LANG LC" /usr/etc/sshd_config 2>&1)
if [[ "$SSH_LC_TEST" =~ "AcceptEnv LANG LC" ]]; then
_DO_NOTHING=YES
else
sed -i "s/.AcceptEnv.//g" /usr/etc/sshd_config
echo "AcceptEnv LANG LC_" >> /usr/etc/sshd_config
fi
fi
_LOCALE_TEST=BROKEN
_LOC_TEST=$(locale 2>&1)
502 if [[ "$_LOC_TEST" =~ LANGUAGE=.#UTF-8 ]] \ #shouldn't this be LANGUAGE=#.UTF-8
503 && [[ "$_LOC_TEST" =~ LANG=.#UTF-8 ]]; then #shouldn't this be LANG=#.UTF-8
_LOCALE_TEST=OK
fi
if [[ "$_LOC_TEST" =~ "Cannot" ]]; then
_LOCALE_TEST=BROKEN
fi
if [ "${_LOCALE_TEST}" = "BROKEN" ]; then
msg "WARNING!"
cat <<EOF

**Comment by ar-jan** [comment]
No, the syntax is correct: dot matches any character, `*` matches zero or more of the preceding token.

But there may still be a problem with the test itself.

**Comment by ar-jan** [comment]
For posting code, use backticks `, or start each line with four spaces for code blocks.

**Comment by ar-jan** [comment]
In e67479591424c62bcbeaba90f70b33c0fdef00a7, setting the LANGUAGE is removed to prevent warnings. The _LOCALE_TEST still checks if LANGUAGE= is configured with a UTF-8 locale, but this variable is only a fallback setting and is not required.

I think _LOCALE_TEST should only look at the LANG= setting.

**Comment by omega8cc** [comment]
A patch?

**Comment by EdNett** [comment]
OK, here's my first attempt at writing an official patch for a boa fix.

Ed  Can't seem to upload it, here it is:

From 00568cb985faf4f2e4c1d36c35404828bbb7c69e Mon Sep 17 00:00:00 2001
From: EdNett <EM-fast1@3105319.no-reply.drupal.org>
Date: Wed, 28 Jan 2015 11:13:10 +0100
Subject: [PATCH] patch for function fix_locales () in
 lib/functions/system.sh.inc

---
 lib/functions/system.sh.inc | 4 ++--
 1 file changed, 2 insertions(+), 2 deletions(-)

diff --git a/lib/functions/system.sh.inc b/lib/functions/system.sh.inc
index e364ade..5df6b3a 100644
--- a/lib/functions/system.sh.inc
+++ b/lib/functions/system.sh.inc
@@ -499,8 +499,8 @@ fix_locales() {
   fi
   _LOCALE_TEST=BROKEN
   _LOC_TEST=$(locale 2>&1)
-  if [[ "$_LOC_TEST" =~ LANGUAGE=.*UTF-8 ]] \
-    && [[ "$_LOC_TEST" =~ LANG=.*UTF-8 ]]; then
+  if [[ "$_LOC_TEST" =~ LANGUAGE=*.UTF-8 ]] \
+    && [[ "$_LOC_TEST" =~ LANG=*.UTF-8 ]]; then
     _LOCALE_TEST=OK
   fi
   if [[ "$_LOC_TEST" =~ "Cannot" ]]; then
-- 
2.1.0

**Comment by EdNett** [comment]
Here is the fixed file at my boa pull zone:

https://github.com/EdNett/boa-1/blob/master/lib/functions/system.sh.inc

**Comment by EdNett** [comment]
I have tried to test this by substituting my boa pull url for the url in
cd;wget -q -U iCab http://files.aegir.cc/BOA.sh.txt;bash BOA.sh.txt

but it didn't work. Can you verify that there are some hard-coded url's that lead to the files in your master stable repository, and that I will never be able to really test what is in my pull repository at

https://github.com/EdNett/boa-1/blob/master/BOA.sh.txt  ?


 I see code in my pull repository like:

'''
ffList="${vBs}/boa-mirrors.txt"
    mkdir -p ${vBs}
    if [ ! -e "${ffList}" ]; then
      echo "jp.files.aegir.cc"  > ${ffList}
      echo "nl.files.aegir.cc" >> ${ffList}
      echo "uk.files.aegir.cc" >> ${ffList}
      echo "us.files.aegir.cc" >> ${ffList}
    fi
    if [ -e "${ffList}" ]; then
      _CHECK_MIRROR=$(bash ${ffMirr} < ${ffList} 2>&1)
      _USE_MIR="${_CHECK_MIRROR}"
      [[ "${_USE_MIR}" =~ "printf" ]] && _USE_MIR="files.aegir.cc"
    else
      _USE_MIR="files.aegir.cc"
    fi
  else
    _USE_MIR="files.aegir.cc"
  fi
  if ! netcat -w 10 -z "${_USE_MIR}" 80; then
    echo "INFO: The mirror ${_USE_MIR} doesn't respond, let's try default"
    _USE_MIR="files.aegir.cc"
  fi
  urlDev="http://${_USE_MIR}/dev"
  urlHmr="http://${_USE_MIR}/versions/master/aegir"
  urlStb="http://${_USE_MIR}/versions/stable"

'''

that make me think I'll never be able to test my pull repository.  Can you confirm this, or give me a link to a guide about how to do this, if it exists, please?

Thank you.

**Comment by ar-jan** [comment]
Here's a couple of notes:

1) This fix isn't going to help you with your problem in 506 as long as your locales are somehow hardcoded to use POSIX, because en_US.UTF-8 is required for some variables.
2) You should be able to test your changes by just overwriting BARRACUDA.sh.txt with your modified version (without running the meta installer), and running `barracuda up-stable`. At least I think so, @omega8cc please correct me if I'm wrong.
3) You worked on the master branch, which has completely rearranged files. In the 2.3.x branch, fix_locales() is located in BARRACUDA.sh.txt. For testing it's probably easier to try from that version, otherwise I think you'd have to update to head first. So just modify the 2.3.8 BARRACUDA.sh.txt version on your server.
4) Most importantly, I think the patch should reflect [this](https://github.com/omega8cc/boa/issues/583#issuecomment-71634828), the wildcard syntax was correct before. So basically just remove the check for LANGUAGE.
5) For omega8cc to accept your changes, you should make a pull request. The best way to do that is to create a branch in your fork dedicated to this particular change. Github has docs for recommended forking and pull request workflows.

Good luck!

**Comment by ar-jan** [comment]
P.S. did you see my comment in 506 [here](https://github.com/omega8cc/boa/issues/506#issuecomment-71643654)?

**Comment by EdNett** [comment]
Hello,

I was able to solve this prublem by using aptitude to purge the locales, reinstall them, then run "dpkg-reconfigure locales" and then editing the /etc/default/locale file, which ONLY contained the line LANG=en_US.UTF-8  and adding the line
LANGUAGE=en_US.UTF-8  to it, restarting the server and running the barracuda up-stable system.
Thank you for your help.

I think you are wrong when you say that I should be able to test my changes to the boa scripts on my git pull/fork, because all the paths are not relative, there are many references to the omega8cc sites from which files are provided. The script I wanted to test is not in the barracuda.sh.txt - it is in the system.sh.inc file, which running any barracude up-stable system (even from my boa fork) will never give me my version of it unless I modify dozens or perhaps hundreds of lines in many files ... too much work.  It looks like I was wrong about the asterisk and the dot in that file, anyways. I am not a scripter.  
FYI the mysql password was 80 characters long - that's fine - it must be the encryption of the desired 96 character password that rendered it 80 characters. I have tested this before and I have gotten a range of password character values from 80 to 85.
Best regards,

Ed

**Comment by EdNett** [comment]
Actually, It was adding the following lines to my /root/.bashrc file that allowed the output of the "locale" command to be en_US.UTF-8 rather than the POSIX that was the previous output:

export LANG=en_US.UTF-8
export LANGUAGE=en_US.UTF-8

**Comment by ar-jan** [comment]
Good! Note that at some point BOA configured the LANGUAGE= variable, but this was removed because if may conflict with LC_ALL (as you also encountered), so it would be better to remove it. Since it's only a fallback option, you don't need it anyway.

**If** you now were to use an SSH client that sends specific locale settings (i.e. `LC_*` variables), your LANG setting would be overridden by these more specific settings, and you could encounter locale problems again. Also, there are two settings where you actually want POSIX rather than en_US.UTF-8, to ensure consistency. I'd recommend this for your .bashrc then:

    export LANG=en_US.UTF-8
    export LC_CTYPE=en_US.UTF-8
    export LC_NUMERIC=POSIX
    export LC_COLLATE=POSIX
    export LC_ALL=

Too bad the [mystery of the POSIX settings](http://unix.stackexchange.com/q/155559/20865) isn't solved though.

**Comment by ar-jan** [comment]
And yes, the new version uses system.sh.inc, but if you were still on 2.3.8 the fix_locales() function hadn't moved yet.

**Comment by ar-jan** [comment]
@EdNett see #584 for why you still had to use LANGUAGE variable to fix your problem, which is what I meant [here](https://github.com/omega8cc/boa/issues/583#issuecomment-71634828).

**Comment by omega8cc** [comment]
Thanks for the investigation and for the patch which fixes the problem.

**Comment by EdNett** [comment]
Hello,

Well, the problem isn't really fixed for me. Unless, of course, this fix hasn't been applied to the stable 2.3.8.

First of all, I see that with every upgrade, you write over the /root/.bashrc  file, so I would constantly have to modify that file before every upgrade. That shouldn't be necessary.  There is probably some incompatability (as in dpkg conflict) with the linux base version boa is using (which is pretty old) and a more recent locales or bash package, is my guess.

I have another problem with my production server that I have to create a new issue for - it seems there is never any response from the boa servers, and I wonder if my IP or domain is blocked?

**Comment by ar-jan** [comment]
This fix will be in 2.4.0. But the real underlying problem for you is why you cannot define a default locale in the usual manner (/etc/default/locale), and this really cannot be caused by BOA.

You did reboot after changing /etc/default/locale, right? Another thing you could try is to add these locale assignments also with `export ...` in /etc/default/locale.
