### ISSUE TITLE
Update JS module to 7.x-2.0

### ISSUE THREAD

**Issue by markcarver** [omega8cc/boa#586]
I'm not entirely sure where the JS module is used in this project or if it's just bundled (this project is listed on our project page). If there is any custom modules that implements a JS callback, there is a new 7.x-2.x branch that will soon be released. Just trying to give a heads-up and also asking for feedback/testing if possible.

https://www.drupal.org/project/js

**Comment by omega8cc** [comment]
Thanks for the heads-up!

High-performance JavaScript callback handler is bundled with BOA because it requires integration both on the Aegir platforms and Nginx rewrites level, so it works out of the box for every site hosted on our stack.

We have always included js-7.x-1.x-dev, but we can of course use js-7.x-2.0-beta1 in the next release.

**Comment by markcarver** [comment]
Do you mean that you just include it to ensure that if someone _wants_ to use it they can, but are not actually providing any JS callbacks yourselves?

**Comment by omega8cc** [comment]
Correct, BOA is about high performance hosting environment for Drupal, not about managing codebases, so we include the module in every hosted site codebase ready to use, so we also create the symlink to the /js.php URI with proper rewrites on the Nginx / PHP-FPM level.

This means that site admin can simply enable the module and use it with other modules which depend on it, without any extra work.

**Comment by markcarver** [comment]
Awesome :)

I'd be interested in knowing what those Nginx rewrites are. I run Nginx locally and have my own rewrites, but haven't yet put anything official in the JS module regarding it (just Apache rewrites now).

**Comment by omega8cc** [comment]
It is a very simple rewrite, with built-in protection from DoS attempts:

https://github.com/omega8cc/provision/blob/2.4.x-dev/http/Provision/Config/Nginx/Inc/vhost_include.tpl.php#L258

Since built-in platforms/codebases in BOA don't allow to access Drupal root, BOA also maintains a js.php symlink to the shared contrib space for even better speed. It just works! :)

**Comment by markcarver** [comment]
Ok, yeah that's identical to what I have. I also put in some manual langcode support, but haven't yet figured out better dynamic langcode support (my nginx regex isn't that great). The langcode is included with the `pathPrefix` property when sending a request via JS:

```js
var url = Drupal.settings.base + Drupal.settings.pathPrefix + 'js/';
```

```nginx
location ^~ /de/js {
    location ~* ^/de/js/ {
        if ($is_bot) {
          return 403;
        }
        rewrite ^/(.*)$ /js.php?q=$1 last;
    }
}
location ^~ /zh-cn/js {
    location ~* ^/zh-cn/js/ {
        if ($is_bot) {
          return 403;
        }
        rewrite ^/(.*)$ /js.php?q=$1 last;
    }
}
```

**Comment by omega8cc** [comment]
This can be tricky, because you need to use two-level locations to make sure it stops at `/de/js` or `/zh-cn/js`, to avoid collisions with URI which should be sent to Drupal, like `/de/js-is-great-article`, so you need literal location matching `^~`, which doesn't support regex to "export" part of the URI and, say, send it as a separate variable appended to the rewritten URL etc.

**Comment by markcarver** [comment]
Exactly. Luckily these sites don't use pathauto or anything and just internal, but still the issue remains (which is why I haven't yet added support). Anyway, thanks for the chat. I will have to look into this separate issue later. I'll create a new one for the full release of the JS module and hopefully one for Nginx if I can figure out a dynamic way.

**Comment by ar-jan** [comment]
> We have always included js-7.x-1.x-dev, but we can of course use js-7.x-2.0-beta1 in the next release.

Seems like that could be a problem for sites already using the 1.x version? Seeing this:

> Modules that already have integration with the 7.x-1.x API, you will need to re-integrate your callback to provide a token at the very least

**Comment by markcarver** [comment]
It's possible, but considering that the JS module only has 1,369 installs... I don't really see this being too huge of an issue in all honesty. If it is, I am willing to work with other module maintainers in getting their callbacks working with the new 7.x-2.x API, just file an issue in our queue. I have already contacted the ones that I am aware of (which is how I found out that this distro includes it).

**Comment by ar-jan** [comment]
Stated differently: if you run current versions of e.g. admin_menu or shs, and js module is upgraded to 2.x, would they break? (I happen to use these two modules on BOA)

If so, this could be a problem even if updated versions were already available, because you may not have updated them on your sites yet. So the potential issue I see is more about how to introduce this 2.x version to BOA, since the version is controlled at the BOA/platform level.

**Comment by markcarver** [comment]
Until their respective issues are fixed and committed, yes. This is a major version change of the JS module. In fact @omega8cc, you may want to revert the commit you made earlier today. I wasn't planning on such a quick reaction TBH.

There is no stable release of the 7.x-2.x branch of the JS module. It's still only in the first beta stage.

As stated above, I have already been working with popular contrib modules that utilize this module:
Admin menu - https://www.drupal.org/node/2219467
SHS - https://www.drupal.org/node/2417417

**Comment by omega8cc** [comment]
This commit will affect only *new* platforms, but if there is a major API change without backward compatibility in place for modules which depend on this, this may cause problems, indeed. OK, reverting for now.

**Comment by markcarver** [comment]
That's why this was a major version bump in the JS module, as its ok to break APIs then and not keep backwards compatibility. I'll keep this issue in mind when the main modules that use this one are updated.

Typos courtesy of Siri

**Comment by thebennos** [comment]
reminder here. this is from 2015 
JS module is stable and now at version 2.1

**Comment by omega8cc** [comment]
Thanks, updated!
