### ISSUE TITLE
Clean up stale advagg js and css files?

### ISSUE THREAD

**Issue by ar-jan** [omega8cc/boa#606]
I just noticed advagg js and css files never get cleaned up in BOA. The files in sites/example.com/files/{advagg_js,advagg_css} go back to when I first created the site on the platform (30 MB of js files in my case).

I found this issue in the advagg queue: https://www.drupal.org/node/2162601. It says `Note that advagg uses atime where core uses mtime.` which I assume is why in BOA files are never cleaned up.

This seems to be by design in advagg, and since BOA supports the module I wanted to bring it up here first. Or maybe we should file a request to advagg to use mtime instead?

**Comment by omega8cc** [comment]
BOA will never clean up these files. It is left for the module internal clean-up logic and manual management, if needed, because these files are by design intended to be used long-term, and rebuilt partially if needed, automatically, but never purged arbitrarily by anything other than the module itself -- also because it is associated with DB entries.

**Comment by omega8cc** [comment]
Also, many systems disable `atime` altogether for performance reasons, so it is never going to work properly. I would suggest to use `mtime` instead. This probably needs a feature request in AdvAgg.

**Comment by omega8cc** [comment]
But again, the `atime` / `mtime` stuff has not impact in the BOA context, because BOA would never check/clear these files anyway.

**Comment by ar-jan** [comment]
I wouldn't expect BOA to clean up the files, but what might be related to BOA is that stale files apparently keep being accessed? Presumably this doesn't happen via Drupal/Advagg, since these are stale files.
Normally, aggregated files that haven't been accessed in 30 days would already automatically be purged by AdvAgg, as far as I can see.

Maybe this is due to the Aegir workflow of migrating?

I'll also open an issue for AdvAgg.

**Comment by omega8cc** [comment]
If any module depends on `atime` while the system has `noatime` defined in `/etc/fstab` then it will never work as expected. It is not related to BOA (we don't modify your `/etc/fstab`) and should be fixed in AdvAgg so it stops depending on a system feature which shouldn't be expected as always available.
