### ISSUE TITLE
_SQUEEZE_TO_WHEEZY=YES breaks the system after reboot on Linode and DigitalOcean

### ISSUE THREAD

**Issue by omega8cc** [omega8cc/boa#627]
We have tested this major upgrade on Linode and DigitalOcean recently and both just lock the system into read-only mode after reboot with no easy way to recover, while the same procedure works elsewhere and worked for us hundreds of times already.

Either they do something unusual or we have a bug to find and fix.

**Comment by omega8cc** [comment]
We should deprecate this feature. It is too dangerous if it may brick the system on some hosts, while it never happened on our systems. Besides, running any major upgrades *in place* is against all best practices, not only for Drupal sites.

We should recommend the `xboa` magic from now on: https://github.com/omega8cc/boa/blob/master/docs/MIGRATE.txt

**Comment by omega8cc** [comment]
While it could be dangerous if there are underlying issues affecting some hosts, we should still work on debugging this to make it work. Debian itself is expected to "be upgraded painlessly, in place, without any forced downtime".

**Comment by HyperGlide** [comment]
Thanks for the additional information. 

I do recall and had a look for this thread that was related to myself and others that where in the same position of migrating from from the 32 to 64 bit kernel.

https://www.drupal.org/node/2271951

**Comment by petrowsky** [comment]
Well, I figured I'll post my situation here since it might be useful down the road. I just upgraded the day before this post from squeeze to wheezy. I've been on the same Linode box since 2011. It was a BOA 2.0.4 release.

I had previously (about half year ago) attempted using _SQUEEZE_TO_WHEEZY=YES and it certainly did brick my system. I had to scrap it and start over from a clone of the vm using Linode's backups.

Yesterday, I found success with bringing squeeze up to wheezy. I took the long route and decided to do a standard apt-get upgrade then dist-upgrade as is typically suggested. I then ran BOA just after those upgrades.

As part of the process, I opted to be prompted on each install of new binaries to decide if I wanted to keep older configs or install newer ones from the repos. This process was a bit arbitrary, but I knew I would learn a bit more by looking at the diffs on them.

Using apt-get and doing it the "non suggested" way - as opposed to xboa, was worth it to me because of multiple configured IP's for ssl, some custom installs of other apps and other sites hosted and proxied via vhosts. I figured it was worth a shot and the learning experience. The following are all guesses as to what problems there were. They may be unique or apply to Linode vm's in general.

Long story short, here's what happend.

- apt-get upgrade while running deb 6 - no problems (I was at 2.4.0 boa)
- updated apt sources to wheezy (including maria db)
- standard apt-get upgrade went along just fine with no issues to deb 7
- apt-get dist-upgrade (here's where some things broke)
- fixed broken things like openssl, aptitude & postfix
- ran barracuda and got a stable setup

Looking at the apt log, there were a few things which got removed which were not added back in. Possibly because of how I had answered on questions about conf files. Here's what the command showed was removed on the apt-get dist-upgrade command.

```
Remove: gcj-4.4-base:amd64 (4.4.5-2), libdjvulibre-dev:amd64 (3.5.23-3+squeeze1), libtiff4-dev:amd64 (3.9.4-5+squeeze12), aptitude:amd64 (0.6.3-3.2+squeeze1), gcj-4.4-jre-lib:amd64 (4.4.5-2), libgcj10:amd64 (4.4.5-2), libpango1.0-common:amd64 (1.28.3-1+squeeze2), libept1:amd64 (1.0.4), console-terminus:amd64 (4.30-2), libmagickwand-dev:amd64 (6.6.0.4-3+squeeze6), x-ttcidfont-conf:amd64 (32), libperl5.10:amd64 (5.10.1-17squeeze6), libmagickcore-dev:amd64 (6.6.0.4-3+squeeze6), libjpeg62-dev:amd64 (6b1-1), portmap:amd64 (6.0.0-2), defoma:amd64 (0.11.11)
End-Date: 2015-07-13  19:21:57
```

The biggie was that aptitude was removed and was not able to be reinstalled back in because of dependancies which were being held (I'm guessing) based on the use of _SSL_FROM_SOURCES=YES.

Subsequent commands which were autorun by apt-get showed this.

```
apt-get autoremove -y --force-yes -qq
```
(with many packages being removed - mostly a lot of libs - including aptitude-common)

also was this

```
apt-get purge postfix -y
```

So, postfix was killed off, aptitude did not get updated/installed and openssl was broken.

In order to get to the point where I could run barracuda, which needs aptitude, I had to fix openssl. There were a few packages which were held (openssl being the big one) and I had to use apt-mark to unhold and then update - which fortunately worked.

Ultimately, the system standard openssl did install along with some other libs that had been held - like unzip, zlib1g-dev & zlib1g - pretty critical stuff right?

Once the missing libs and openssl were back in, then I tried installing aptitude again and got it to install.

I then ran barracuda and wonderfully, I didn't see it error out when trying to use aptitude. Looked at the barracuda install log and didn't find any errors.

I've gone through the system with as much time as I have and compared it against a working boa install which was done on another linode box with a fresh wheezy install and it seems like things are in working order - including all my customizations and vhosts! Yeah!!!

What I can say is that I am EXTREMELY grateful for the work that Omega8 has done! I was surprised I was able to get it working with my mediocre sysadmin skills and I'm looking forward to updating some of my older Drupal sites.

Omega, if there's anything you want to see in my logs or have questions about my experience then I'm happy to answer. Would apt's term.log help out?

I also have a snapshot of the 2.4.0 Deb 6 but I have no idea how you can restore it with another ip or isolated or if Linode even supports that.

Just thought I would share the experience in case there is anyone else who is trying to upgrade a squeeze box on Linode.

**Comment by HyperGlide** [comment]
Thanks @petrowsky for the write up and sharing.

I did try the upgrade over a year ago and like you had to revert to a linode backup.

Have not tried it since, although we did do a kernel change from 32 - 64 when linode was updating there servers and pricing. After we ran a force reinstall of BOA and all was working great. Only recently we have been having issues with OPENSSL as it appears the server still has the 32 bit version.

Have tried a few times to resolve with no luck. At present we are looking to migrate to a new server with a fresh BOA install.

**Comment by omega8cc** [comment]
Thanks for the detailed feedback! I just looked at the code again and realized that while we do un-held packages normally marked as hold on Squeeze to prevent conflicts, we don't actually re-install them before proceeding further. Yes, aptitude has to be re-installed first, but that step was always covered. The culprit here is `_SSL_FROM_SOURCES=YES` set as default on Squeeze, because we decided to get all supported systems to use SPDY and PFS. I guess that is where it broke the `_SQUEEZE_TO_WHEEZY` procedure. We probably didn't detect nor experience this because we have used VMs with no local kernel, so broken `_SQUEEZE_TO_WHEEZY` procedure couldn't brick the system even if the cascade of forced installs and removals could probably cause this elsewhere.

**Comment by omega8cc** [comment]
@HyperGlide -- you could perhaps run forced upgrade like this:

```
echo "libssl-dev install" | dpkg --set-selections
echo "openssl install" | dpkg --set-selections
```
```
apt-get install libssl-dev -f -y --force-yes --reinstall
apt-get install openssl -f -y --force-yes --reinstall
```

Then just `barracuda up-stable system` again.

**Comment by omega8cc** [comment]
We are testing this on Linode, but while there are no more problems with uninstalled packages or libraries, just no errors at all, yet, after reboot the system goes into read-only mode. So the culprit must be still elsewhere in the upgrade procedure.

**Comment by HyperGlide** [comment]
@omega8cc Thank you for the additional support will have a try and report back.

**Comment by HyperGlide** [comment]
Failed again with similar errors - log posted at - 

https://gist.github.com/HyperGlide/b7ada33815879d612234

**Comment by omega8cc** [comment]
Ouch, the problem was really "trivial" (see latest commit above), but it is officially fixed!
