### ISSUE TITLE
Opcache  on 2.4.1 is not enabled by default?

### ISSUE THREAD

**Issue by nasl** [omega8cc/boa#650]
On fresh default install opcache is not enabled. Is there some reason behind this?
If it can be enabled, what are the recommended settings?

**Comment by nasl** [comment]
Oops, phpinfo() shows it running, do not know why it is not reflected in /opt/php55/lib/php.ini

**Comment by omega8cc** [comment]
There are separate php.ini files for CLI and FPM, and opcache is not used in CLI, by design. Furthermore, both CLI (drush backend) and FPM (web front-end) use instance/user specific php.ini files, so the default php.ini files are almost never used, unless for Chive and other non-Drupal apps, if hosted.
