### ISSUE TITLE
Scaling a BOA stack - new system values

### ISSUE THREAD

**Issue by theodorosploumis** [omega8cc/boa#653]
I 've installed BOA on a 1GB machine. Then I decided to scale up the machine to **4GB RAM** and run command:

`barracuda up-stable system`

My questions are simple.
1) Are the system values recalculated automatically (eg php_admin_value[memory_limit] found at /opt/etc/fpm/fpm-pool-common.conf)?
2) If not, how could I force the system to change these values according to the new RAM?
3) Is there any algorithm on the BOA files that does this calculation?

Thanks for this awesome project.

**Comment by omega8cc** [comment]
Yes, barracuda will re-calculate limits/settings on upgrade, depending on the available RAM and CPU cores, however this auto-configuration is not fluid enough, yet.

Some related issues:

https://github.com/omega8cc/boa/issues/559
https://github.com/omega8cc/boa/issues/636

Related tool: https://github.com/omega8cc/boa/blob/master/aegir/tools/BOND.sh.txt

Related code: https://github.com/omega8cc/boa/blob/master/lib/functions/system.sh.inc#L217

**Comment by geofftech** [comment]
Based on this thread, I thought I would run BOND and see if it made any suggestions. I did upgrade my hardware since my original installation. However I get an error

`ERROR: Please upgrade this system to BOA version BOA-2.4.2-dev first`

The version is defined in the "Do not edit" section. Is BOND just for dev systems or am I doing something wrong?

Thanks

**Comment by omega8cc** [comment]
Use the version corresponding with the BOA version you have currently installed. For latest stable use:

https://github.com/omega8cc/boa/blob/BOA-2.4.1/aegir/tools/BOND.sh.txt
