### ISSUE TITLE
7.35 Release?

### ISSUE THREAD

**Issue by gmeans** [omega8cc/boa#661]
Will there be a point release soon for the Drupal 7.35 upgrade? Thanks!

**Comment by omega8cc** [comment]
Since these vulnerabilities may affect only very specific setups and in a very rare situations, as explained at: https://www.drupal.org/SA-CORE-2015-001 we don't plan to release BOA version out of normal schedule, also because some distributions are still working on their own updates, and we need to wait a bit to have them all included.

You can check our projected releases dates at: https://github.com/omega8cc/boa/milestones

You can always build and use custom codebase, though, without waiting for another BOA release.

Just make sure to follow our docs and use recommended, latest enhanced Drupal core versions, available to download from https://omega8.cc/how-to-add-custom-platform-properly-140

**Comment by omega8cc** [comment]
Known issues with latest Drupal core -- Read before you upgrade! D7: bit.ly/1Na962Y, D6: bit.ly/19Mpb2w
