### ISSUE TITLE
.gitconfig support

### ISSUE THREAD

**Issue by ginal** [omega8cc/boa#662]
On previous BOA versions, creating the file ~/.gitconfig and giving write permission to the limited shell users enabled them to use the command "git config --global". On latest BOA 2.4.1 the limited shell users cannot run "git config --global" even if the .gitconfig file exists and is writable by the user. For example when I try to run "git config --global user.name James" I get the error:

    error: could not lock config file /home/o1.david/.gitconfig: Permission denied

because git config also needs write access to the user's home directory (if I chattr -i the home dir it works). Is there anyway for BOA to support the .gitconfig file?

**Comment by omega8cc** [comment]
We have made the extra sub-accounts write-protected a long, long time ago after receiving many reports about various types of service abuse, with the least serious being uploading a gigabytes of data and using the account as a remote disk archive. Sub-accounts are very limited by design. This doesn't affect the main lshell account, though.

**Comment by ginal** [comment]
Ok, that's reasonable, I just hoped that there was some workaround specifically for git. Thanks for your support.
