### ISSUE TITLE
home and .drush directory permissions

### ISSUE THREAD

**Issue by ginal** [omega8cc/boa#677]
I am trying to install the drupal composer module (https://www.drupal.org/project/composer) which is a drush only module. Using 'drush dl composer-8.x' I get the following error:
```
Download and install the Drush Composer extension? (y/n): y
Directory /home/o1.acb/.drush exists, but is not writable. Please check directory permissions. [error]
Project composer (8.x-1.x-dev) could not be downloaded to /home/o1.acb/.drush/composer.
```
I understand the reasons behind the choice of making all the users home dirs and .drush dirs by default not writable in a shared hosting environment, but in a self-hosted situation it creates more problems than it solves.
Would you consider merging a patch that optionally makes these directories writable, based on the existence of a configuration file? I'd be happy to contribute something like this back to Boa.

**Comment by ar-jan** [comment]
I think it's a bug - at least, I believe the .drush folder should be writable. I had the same problem installing [Drush Search & Replace](https://www.drupal.org/project/sar) about a week ago.
I noticed that the `_PERMISSIONS_FIX=YES`  setting in my /root/.barracuda.cnf kept getting overwritten to NO again. IIRC I fixed it by setting it to YES again and then running `bash /var/xdrago/daily.sh` manually. Afterwards the _PERMISSIONS_FIX setting was no longer overwritten and I could download drush extensions.

**Comment by omega8cc** [comment]
@ginal It is by design, for security reasons. You can add any drush extension you wish to the Aegir backend user, though. BOA is designed to allow to securely host many Octopus instances on the same system, with kind of virtual chroot, and these permissions are an important part of this. If you are willing to make this a feature to disable these security measures, so it will be configurable, patches are welcome.

@ar-jan This is unrelated here, please open separate issue.

**Comment by ar-jan** [comment]
Ah, sorry for the noise. But I was able to do `drush dl sar` as lshell user and get it installed to `/home/o1.ftp/.drush/sar`, without manually changing permissions, so I thought installing Drush modules was possible in general.
But now that I try on another lshell account I get `home/o2.ftp/.drush exists, but is not writable.` even though the permissions for the .drush folder are the same on both accounts:
`drwxr-sr-x  4 o1.ftp users  4096 mrt 27 18:09 .drush`
Now I'm stumped what the expected behavior is.

**Comment by omega8cc** [comment]
The `.drush` directory should be made immutable for `o1.fp` and all sub-accounts, and writable only for master instance `aegir` and satellite `o1`.

**Comment by omega8cc** [comment]
You can change this temporarily with `chattr -i .drush`

**Comment by omega8cc** [comment]
As for composer, note that you can use it directly, without drush, and it is already pre-installed, because Drush 7 depends on it.
