### ISSUE TITLE
INTL extension not enabled in PHP - installing it also dont work

### ISSUE THREAD

**Issue by andrilablateral** [omega8cc/boa#691]
Hi Omega8

I need to install and enable intl on our current BOA server but for some reason it wont initialise.

I have installed it using "apt-get install php5-intl" (being root) and it installed successfully, but after restarting nginx (or even the box) it still wont initialise.

Help greatly appreciated!

Kind Regards

Andri

**Comment by omega8cc** [comment]
BOA doesn't support installing PHP extensions like this, because we have a custom layout for multi-version support. PHP built-in extensions can be enabled via:

`_PHP_EXTRA_CONF="" #------------ Allows to add custom options to PHP build`

However any other extension can't be installed without adding the support in BOA explicitly.
