### ISSUE TITLE
Preserve custom mysql settings on weekly system update

### ISSUE THREAD

**Issue by ixiam** [omega8cc/boa#699]
Add a new configuration option to preserve custom mysql values on weekly system update
(For example max_connections, max_user_connections, etc)

**Comment by omega8cc** [comment]
Instead of adding new variable (or variables), we will use existing `_PHP_FPM_WORKERS` variable (mostly deprecated otherwise since PHP workers have been switched to on demand mode anyway and they are further configurable per Octopus instance), so all SQL connections limits are now configurable via `_PHP_FPM_WORKERS` in the `/root/.barracuda.cnf` file. Note that `_PHP_FPM_WORKERS`variables for all Octopus instances in their respective `/root/.ox.octopus.cnf` files are independent and don't affect SQL limits.
