### ISSUE TITLE
DNS fails even when DNS checks are disabled

### ISSUE THREAD

**Issue by BrianGilbert** [omega8cc/boa#712]
BOA [01:04:55] ==> FATAL ERROR: DNS looks broken for server master

I have preset the IP in .barracuda.cnf to the elastic IP for the server, and disabled DNS checks in both barracuda and o1.octopus.cnf files.

.barracuda.cnf (sanitised)
http://www.privatepaste.com/73057bb58a

.o1.octopus.cnf (sanitised)
http://www.privatepaste.com/3949bac1aa

cat: /var/log/barracuda_log.txt: No such file or directory
cat: /data/disk/o1/log/octopus_log.txt: No such file or directory

cat: /etc/pdnsd.conf: No such file or directory

cat /etc/resolv.conf
```
# Generated by dhcpcd for interface eth0
search us-west-1.compute.internal
nameserver 172.30.0.2
```

install command:
```
boa in-stable public o1.domain.org sysadmin@domain.com o1 none

**Comment by omega8cc** [comment]
The `_DNS_SETUP_TEST=NO` doesn't disable all checks, because even when the DNS entry is fake intentionally or local etc, the `getent ahostsv4 this.host.name` must result with non-empty response (it gets this.host.name from `uname -n`), or it will abort the installer. The single word "master" is not a valid FQDN hostname, no matter what.
