### ISSUE TITLE
BOA with Aegir Hostmaster 3.x

### ISSUE THREAD

**Issue by mrconnerton** [omega8cc/boa#715]
I have looked around for an issue / wiki post but haven't found anything. I wanted to know what the plans are (if there are any) for getting BOA on Aegir 3.x

http://community.aegirproject.org/3.0-beta1

**Comment by omega8cc** [comment]
We are already running Aegir 3.x backend (Provision) since BOA-2.4.0

https://github.com/omega8cc/boa/blob/BOA-2.4.2/CHANGELOG.txt#L227

The frontend is less important at the moment and we will consider the upgrade once it is stable and the upgrade path is working without hiccups due to problems with Drush 7 etc.

**Comment by mrconnerton** [comment]
Facinating, I didn't realize they could be used with each other. Thanks.

**Comment by omega8cc** [comment]
We have started using Provision 3.x to be able to test support for Drupal 8 and Backdrop CMS, which in turn required running latest Drush 7.

We have mentioned this also in the BOA-2.4.2 release notes: https://github.com/omega8cc/boa/blob/BOA-2.4.2/CHANGELOG.txt#L35

>>>
  @=> NOTE: Drupal 8 support is broken in this release, because latest Drush
      doesn't support older Drupal 8 beta versions, while new D8 beta is not
      released and tested yet, and we really need latest Drush to fix broken
      D6->D7 upgrade path, so we could prepare for full Aegir 3, which comes
      with D7 in the frontend.
>>>

**Comment by BrianGilbert** [comment]
Here is one case for 3.x on the fronted: https://www.drupal.org/project/hosting_remote_import

**Comment by omega8cc** [comment]
The hosting_remote_import is supported and included in BOA for ages (over 3 years, since BA-2.0.3). But you should use Octopus and not only Barracuda to be able to use it: 

https://github.com/omega8cc/boa/blob/BOA-2.4.6/CHANGELOG.txt#L5031
https://github.com/omega8cc/boa/blob/master/docs/MODULES.txt#L183
https://github.com/omega8cc/boa/blob/master/docs/REMOTE.txt

**Comment by omega8cc** [comment]
That said, check also: https://github.com/omega8cc/boa/blob/master/docs/MIGRATE.txt

**Comment by omega8cc** [comment]
The upgrade path is now stable. Fixed!
