### ISSUE TITLE
Mitigate LOGJAM

### ISSUE THREAD

**Issue by obrienmd** [omega8cc/boa#723]
See: https://weakdh.org/sysadmin.html

BOA 2.4.3 is not bad (i.e. an exploit would require tremendous computing power) but still vulnerable per scanners, which report "This site uses a commonly-shared 1024-bit Diffie-Hellman Group".

**Comment by omega8cc** [comment]
The problem is that we always generated very strong and unique 4096-bits DHP, but we normally add them to the crt/key files instead of using currently supported ssl_dhparam directive. After moving the already generated params to a separate file, it works as it should -- test omega8.cc at https://weakdh.org/sysadmin.html now.

**Comment by obrienmd** [comment]
Ah, that makes perfect sense. Thanks for making this a 2.4.4 priority - I really appreciate the focus on security.

**Comment by obrienmd** [comment]
Thanks as usual for quick response!

**Comment by omega8cc** [comment]
Hmm, we should probably use 2048 instead of 4096 because on an idle system, which is typical for freshly installed BOA or low traffic system, generating this takes forever:

```
BOA [23:31:19] ==> INFO: Generating DH parameters, 4096 bit, please wait...
BOA [00:21:05] ==> INFO: Aegir Master Instance upgrade completed
```

Almost 1 hour (!)

**Comment by omega8cc** [comment]
Much better:

```
BOA [01:12:09] ==> INFO: Generating DH parameters, 2048 bit, please wait...
BOA [01:12:16] ==> INFO: Aegir Master Instance upgrade completed
```

**Comment by obrienmd** [comment]
Right, then maybe 3072 or 4096 when it becomes more feasible to crack 2048 (a long, long time)?

**Comment by omega8cc** [comment]
We could add a variable to control this via `/root/.barracuda.cnf` but for now 2048 seems to be enough without slowing down .dhp generation dramatically. The problem is that we must generate it also on initial install and on barracuda upgrade *during the upgrade* and not via daily.sh when it doesn't hurt to have it running for ~1 hour, so it just can't take that long.
