### ISSUE TITLE
Switch to Drush 8 for Drupal 8

### ISSUE THREAD

**Issue by omega8cc** [omega8cc/boa#729]
We can't move past this point, because Drush 8-dev dropped support for PHP 5.3, while Drush 7.0.0 dropped support for Drupal 8 entirely. This means that we have to temporarily drop support for Drupal 8 officially, until we can move forward and start using Drush 8 (and forcefully drop support for PHP 5.3, as a consequence, which may cause problems for some old D6 contrib, perhaps).

References:

https://pantheon.io/blog/introducing-drush-8
https://github.com/drush-ops/drush/releases/tag/7.0.0
https://github.com/drush-ops/drush/commit/ded6ccfdc3bc10241a5af065bf38e5bc86c45640

**Comment by omega8cc** [comment]
That said, we should try to include Drupal 8.0.0-Beta11 if possible, since Drush 7.0-rc2 is supposed to support Beta10.

**Comment by omega8cc** [comment]
There was no point in trying to support Drupal 8 beta with Drush 7.0-rc2. Instead, we need to introduce dual support for Drush 7 and Drush 8, as we did before with Drush 4, 5 and 6, so we could re-introduce support for Drupal 8 per Octopus instance without forcing all instances to use Drush 8 with PHP 5.5+.

**Comment by omega8cc** [comment]
For some reason, latest Drupal 8.0.0-beta15 (vanilla, no patches!) just works again with BOA-2.4.5, which still comes with Drush 7.0-rc2

**Comment by omega8cc** [comment]
This means that current BOA stable supports Drupal 6, 7 and 8, out of the box, with the same Drush version used. Pretty good D8 reloading!

**Comment by florisvanwoudenberg** [comment]
We have installed Drupal 8 in a clean boa 2.4.6, but ran into issues where Drush 7 is still used and we cannot execute drush cr because of updates in drush. 

Are there plans to include drush 8 in boa?

**Comment by omega8cc** [comment]
Yes, this issue (as visible in its title above) is for adding Drush 8 (in BOA-2.5.0 milestone shown on the right here).

**Comment by omega8cc** [comment]
It looks like Drupal 8.0.0-beta15 was the last version still working with Drush 7.0-rc2.

Drupal 8.0.0-beta16 removed `conf_path()` which effectively renders Drush 7.0-rc2 useless for D8 core newer than beta15.

We should probably consider more aggressive approach and just switch to Drush 8 (head), and effectively stop supporting PHP 5.3 (and 5.4)

Similarly like we did with PHP 5.2 in the past, we will first block ability to upgrade for any Octopus instance which still runs on PHP 5.3, but we will not remove PHP 5.3 yet.

This will greatly simplify and speed up development, so we don't need to deal with legacy and not secure software no one should run.

Now the questions is: does Aegir 3 support Drush 8? Probably not :| https://www.drupal.org/node/1194602#comment-10343893

**Comment by EdNett** [comment]
Hi,

Since Drupal 8.0.0 is going to be released before November ends, could you think about doing the following with the install and upgrade script logic:
Download only drush 7 and 8 when only php 5.5 and/or 5.6 are specified in the barracuda and octopus configuration file. BOA *must* support drupal 8 once it's released, right?

This way BOA users can have one instance for D6 and 7 sites which supports php 5.3 and 5.4, and a separate instance for d 7 and d8 sites which allow only php 5.5 and  5.6 and 7 (I assume it's about time to start adding php 7 as an option, right?)

I'm just really looking forward to starting to build and use d8.

Best regards,

Ed

**Comment by EdNett** [comment]
Or - another idea - How about having a separate octopus instance for a drupal 8 ONLY instance? We could require php 5.5 or later, and have 5.6 and 7.0 as options, and only allow d8 sites and platforms. Doing it this way might save a lot of time and work, since nothing needs to be changes in the existing installations. Is this possible? Or, am I missing a major point - Is the aegir hostmaster and provisioning system incompatible with d8 and drush 8?  In any case, could you please let us know if we won't be able to host drupal 8 sites on BOA in the next 2 or 3 months - if we need to make other arrangements, please?

Thank you.

**Comment by omega8cc** [comment]
You will be stuck in BOA-2.5.0 if you still want Drush 7 and PHP 5.3 for some reason. BOA-3.0.0 will remove PHP 5.3 and 5.4, along with Drush 7. We can't make it volatile "on the fly", depending on PHP versions installed.

**Comment by BrianGilbert** [comment]
Is head working with the stable releases of D8 yet?

**Comment by omega8cc** [comment]
@BrianGilbert Yes, but you need to use drush branch: https://twitter.com/omega8cc/status/702139876729298944
