### ISSUE TITLE
OpenSSL not updating on wheezy with install_from_sources=YES

### ISSUE THREAD

**Issue by EdNett** [omega8cc/boa#749]
Hello,

I just ran the 2.4.4 stable hotfix (after having upgraded to 2.4.4 stable a week ago), and I set both OpenSSH and openSSL to upgrade and install from sources. OpenSSh upgraded to 6.9p1, however openSSL did not upgrade and remains at :+1: 
aptitude show openssl
Package: openssl
State: installed
Automatically installed: yes
Version: 1.0.1e-2+deb7u17.

Is this a bug?

Logs are here:  
https://gist.github.com/EdNett/f615553b3becbdbb8a4d

Another question - I was expecting to get the upgraded versions of OpenAtrium (2.4.3) and Commons, but no platforms upgraded - is this normal?

Thank you.

Regards

Ed

**Comment by omega8cc** [comment]
This is normal. OpenSSL can't be built from sources on Wheezy, because it caused too many problems in our tests, so we rely on Debian packages for OpenSSL on Wheezy, at least for now and this variable is thus ignored.

As for platforms included in stable please check: https://github.com/omega8cc/boa/blob/BOA-2.4.4/README.txt

OpenAtrium 2.43 has been released after BOA-2.4.4 and thus is not included. It is included in head, though.
