### ISSUE TITLE
Modify my.cnf / innodb_log_file_size 

### ISSUE THREAD

**Issue by mrconnerton** [omega8cc/boa#762]
I'm looking to tune my mysql config file to add a bunch of ram to innodb_buffer_pool_size, innodb_log_buffer_size, and innodb_log_file_size.

There is a warning message "you can't just change log file size, requires special procedure".

What is the proper way to up the log_file_size?

I'm planning on setting:
innodb_log_file_size          = 512M
innodb_buffer_pool_size    = 2048M
innodb_log_buffer_size      = 8M

 I'm also planning to bump up max connections, query_cache_size, etc

**Comment by omega8cc** [comment]
All your questions are answered in this file:

https://github.com/omega8cc/boa/blob/master/docs/cnf/barracuda.cnf

Correct, you can't just change `innodb_log_file_size`. There is special procedure for this and corresponding barracuda.cnf variable: `_INNODB_LOG_FILE_SIZE` to change this safely on barracuda upgrade.

Other mysql settings can be calculated automatically depending on your usage at barracuda upgrade time, but only if you have set `_USE_MYSQLTUNER=YES` -- otherwise barracuda will just allocate as much memory as your RAM and CPU allows, even if your usage is low.

We don't recommend to play with these values just by editing them. Such changes will overwritten on upgrade, unless you have set also `_CUSTOM_CONFIG_SQL=YES`

**Comment by omega8cc** [comment]
Also note:

````
###
### Allows to change InnoDB log file size,
### which requires special procedure.
###
### Accepted value must be an integer between
### 10 and 500 (in megabytes).
###
### Note: if _CUSTOM_CONFIG_SQL is set to YES,
### this option will be ignored.
###
### Example: _INNODB_LOG_FILE_SIZE=50
###
_INNODB_LOG_FILE_SIZE=AUTO
````

**Comment by mrconnerton** [comment]
100% my fault for not specifying but does your answer change if this is a legacy BOA-2.2.9 server? I don't think it has that option and right now mysql is getting barely anything.

**Comment by omega8cc** [comment]
Not sure, but you can always check: https://github.com/omega8cc/boa/blob/BOA-2.2.9/docs/cnf/barracuda.cnf

**Comment by mrconnerton** [comment]
Well by "I dont' think it has that option"  I meant I checked that file and it certainly does not have that option.

It sounds like since I'm legacy I need to:
# Set _CUSTOM_CONFIG_SQL=YES which will (should) ignore _INNODB_LOG_FILE_SIZE
# Update my my.cnf however I want except for _INNODB_LOG_FILE_SIZE
# Run the boa up-legacy to make sure boa gets my _CUSTOM_CONFIG_SQL
# Learn how to set the _INNODB_LOG_FILE_SIZE safely. Likely just mimicking https://github.com/omega8cc/boa/blob/641dece7ecdda4e3add647c0ea51153ff99c8e50/lib/functions/sql.sh.inc#L3-L17

**Comment by omega8cc** [comment]
Why not to just set _INNODB_LOG_FILE_SIZE and run the legacy upgrade?

Then you can check if it worked and only then modify other mysql variables, restart mysql and then add _CUSTOM_CONFIG_SQL=YES

**Comment by mrconnerton** [comment]
Sure, same thing just a different order I guess. You're saying take advantage of boa setting it for me before I customize. I like it.
