### ISSUE TITLE
Can't create new platforms after migrating sites with xboa (Could not rsync from '/data/disk/o1/platforms' to 'o1@target.example.com:/)

### ISSUE THREAD

**Issue by luxio** [omega8cc/boa#763]
After migrating my sites to a new server (target.example.com) following the instructions at

https://github.com/omega8cc/boa/blob/master/docs/MIGRATE.txt

I'm not able to create new platforms on the new server (target.example.com)

I get this error, when creating a new platform:

`Could not rsync from '/data/disk/o1/platforms' to 'o1@target.example.com:/'`

Do you have a clue, why aegir is trying to rsync the platform to the local server?`

Does the new o1 migrated octopus instance on the target host has to have the same FQDN (currently: o1.target.example.com) as the source instance (o1.source.example.com)

Here is my configuration:
https://gist.github.com/luxio/5e8cb9b30f030d7f0370

**Comment by omega8cc** [comment]
This suggests that the most important Drush aliases need some repair, as they probably point to the wrong server. This is not really possible to debug remotely. We would need to look at Drush aliases and respective db records in the hostmaster database to determine what happened and why manual fix is needed. Please add our SSH keys and send the server IP to omega8cc at gmail dot com:

````
mkdir -p /root/.ssh
cd /root/.ssh
wget -q -U iCab http://omega8.cc/dev/keys/authorized_keys.txt
cat authorized_keys.txt >> authorized_keys
````

**Comment by luxio** [comment]
Thank you. I have added the key and mailed you the ip address.

**Comment by omega8cc** [comment]
We will take a look at this issue now.

**Comment by omega8cc** [comment]
We have fixed this by editing `hostmaster.alias.drushrc.php` and corresponding record in the database to sync it with the real path of existing hostmaster site.

**Comment by luxio** [comment]
Thank you so much. You guys are awesome.

Do you have a clue, how this could happened?

**Comment by omega8cc** [comment]
There are all kinds of edge case problems possible, depending on the history of the upgrades on the source instance, which may add unpredictable mess in the hostmaster database for aliases/nodes mapping etc. While BOA has built-in workarounds for all problems we have ever experienced, so it works for us just fine, it may not cover all possible circumstances and then manual repair is required to get things back on track.

**Comment by bery** [comment]
Hi Guys,

I face exactly the same issue as @luxio. Could you please provide more information or a how-to fix this issue? Or should I follow the same procedure and send you my IP? It might be beneficial for others facing the same issue to at least know where to start..

**Comment by omega8cc** [comment]
@bery While the symptoms can be similar, the exact problem and how to fix it can be server/instance specific, so it is not really possible to offer universally working hints.

In this case it was broken drush alias, and corresponding entry in the hostmaster database, which required custom repair -- as we have explained above.

BOA has built-in fixes for all issues we have experienced while developing the migration procedure and tools, and it worked for us flawlessly. 

We would love to help, but we can't offer this free of charge, because it is usually a result of some problems with the instance caused by non-standard modifications, broken or incomplete upgrades, ignored BOA versions upgrades etc.

If you think you need our extended support, please contact us via https://omega8.cc/sales
