### ISSUE TITLE
Restore documentation for multiple IP addresses

### ISSUE THREAD

**Issue by pricejn2** [omega8cc/boa#777]
Following the implementation of #465, I can no longer find the standard documentation for multiple IP addresses (https://github.com/omega8cc/boa/blob/f5ccf4e43bf1ce89f4c4abc936f6f3fe4daed7d1/docs/SSL.txt#L24). Multiple Aegir IP addresses still makes sense (to me at least) for situations where each Octopus installation would be assigned it's own IP address.

We could of course make this a wiki post. 

```
How to use multiple IPs on your server?

 You can use a quick and simple recipe, explained below.

 1. Create one extra configuration files with contents as shown further below.

    * Replace YO.UR.AEGIR.IP with your Aegir Hostmaster main IP address.
    * Replace YO.UR.EXTRA.IP1,2,3 etc with correct extra IP addresses.

 2. Restart Nginx with `service nginx reload` or `service nginx restart`. Done!



###
### Plain HTTP proxy to add more IPs for HTTP connections (START)
###
### CREATE THIS FILE AS: /var/aegir/config/server_master/nginx/pre.d/extra_ip.conf
###
upstream extra_ip {
  server  YO.UR.AEGIR.IP:80;
}
server {
  listen                       YO.UR.EXTRA.IP1:80;
  listen                       YO.UR.EXTRA.IP2:80;
  listen                       YO.UR.EXTRA.IP3:80;
  server_name                  _;
  access_log                   off;
  log_not_found                off;
  location / {
    proxy_pass                 http://extra_ip;
    proxy_redirect             off;
    gzip_vary                  off;
    proxy_buffering            off;
    proxy_set_header           Host              $host;
    proxy_set_header           X-Real-IP         $remote_addr;
    proxy_set_header           X-Forwarded-By    $server_addr:$server_port;
    proxy_set_header           X-Forwarded-For   $proxy_add_x_forwarded_for;
    proxy_set_header           X-Local-Proxy     $scheme;
    proxy_pass_header          Set-Cookie;
    proxy_pass_header          Cookie;
    proxy_pass_header          X-Accel-Expires;
    proxy_pass_header          X-Accel-Redirect;
    proxy_pass_header          X-This-Proto;
    proxy_connect_timeout      180;
    proxy_send_timeout         180;
    proxy_read_timeout         180;
  }
}
###
### Plain HTTP proxy to add more IPs for HTTP connections (END)
###
```

Thoughts?

**Comment by omega8cc** [comment]
This has been removed after we have synced BOA with Aegir to use wildcard instead of per-IP configurations.

No, you can't assign separate IPs per Octopus instance. In fact, all instances can use any/all IPs available, just w/o any extra configuration, thanks to default wildcard setup.

You should not attempt to restore the old behaviour, because it is going to cause problems and is not needed, since BOA/Aegir will just listen on all available IPs by default.

Please read the up to date docs on proper SSL configuration -- we now support both extra IPs and TLS-SNI mode, and it is the only place where using dedicated IPs makes sense.

**Comment by pricejn2** [comment]
Great, thanks for clarifying.
