### ISSUE TITLE
How can I add a new module to PHP? (trying to set up access to MS SQL server)

### ISSUE THREAD

**Issue by jdcollier** [omega8cc/boa#781]
I have freetds installed on my Debian (Wheezy) install ... but I can't figure out how to get mssql added to PHP.

I can connect to the MS SQL server at command line with tsql ... but my application is not working.

This is the same code I know works fine on a CentOs / Apache setup.

So ... how can I get PHP compiled with a new module?

Thank you so much!

**Comment by omega8cc** [comment]
This is not simple, because thanks to the PHP multi-version configuration used in BOA, we are forced to use custom, non-standard directories trees, with customized on the fly environment (paths to corresponding php.ini files) etc.

While you could easily enable extension provided by PHP "core" using `_PHP_EXTRA_CONF` variable -- see: https://github.com/omega8cc/boa/blob/master/docs/cnf/barracuda.cnf#L61 it is not really possible to extend PHP with non-standard extensions which need to be compiled, like we do with Redis and a few other extensions. This would require adding such extension as an option, like we did with z `_PHP_GEOS` and `_PHP_MONGODB`. But I can't promise if we will do something like this, or when, if yes.

So the question is: do you need some non-standard PHP extension, or you just need to enable some built-in extension? If you need some built-in extension, just use the `_PHP_EXTRA_CONF` method and rebuild PHP by adding `_PHP_FORCE_REINSTALL=YES` in the `.barracuda.cnf`, and then run barracuda upgrade.

**Comment by velpan** [comment]
Same problem... I want to access mssql db through ODBC driver from within php so...  

I install unixodbc and I set
_BUILD_FROM_SRC=YES
_PHP_FORCE_REINSTALL=YES
_PHP_EXTRA_CONF="--with-php5-odbc --with-php5-sybase"

and run barracuda upgrade.

Still can't access odbc_connect(..) function 

Is it possible to build odbc.so extension and enable it in pgp5*.ini files?
Any suggestions?

**Comment by velpan** [comment]
If I set _PHP_SINGLE_INSTALL="5.5" and keep only one version of PHP then is it possible to install packages php5-odbc/php5-sybase with apt-get?

What if I already have a multiple-php environment and change it to single-php? Working octopus stays alive and going or have to rebuild it?
