### ISSUE TITLE
How to unblock a crawler bot (rogerbot) ?

### ISSUE THREAD

**Issue by andrilablateral** [omega8cc/boa#784]
Hi Omega8

This has already been raised on a Moz thread: 
https://moz.com/community/q/omega8-cc-decided-to-block-rogerbot

So how would we go about unblocking this?

Kind Regards

Andri

**Comment by omega8cc** [comment]
We have removed their `rogerbot` from the blacklist after they promised to do something about its crazy behaviour, in March this year: https://github.com/omega8cc/provision/commit/f1a68a852de7e3a71dabe893f5b9078a99707c0d

You don't need to do anything beyond running up to date barracuda *and* octopus. The change is in place since BOA-2.4.2
