### ISSUE TITLE
Octopus/Aegir interface/backend is unuseable in the last two head releases

### ISSUE THREAD

**Issue by AntiNSA** [omega8cc/boa#798]
Theme is all messed up and generally unusable.

**Comment by omega8cc** [comment]
Yes, the head is broken due to Drush 8 testing. We have added separate branches now, so head-to-head upgrades should work again, but your hostmaster is already broken.

You will need to run another head upgrade, fix paths in hostmaster.alias.drushrc.php for 'root' and 'site_path' so they will match where the site actually is, possibly fix aliases paths also in the hostmaster database directly, and then run another head upgrade.

**Comment by AntiNSA** [comment]
This seems difficult.... would it be possible to reinstall the stable version, import my site, and then update to head version.... would everything then work?
