### ISSUE TITLE
Remove deprecated PHP versions

### ISSUE THREAD

**Issue by omega8cc** [omega8cc/boa#801]
PHP 5.3 and 5.4 should be removed. PHP 5.5 will be still supported, but 5.6 will be used by default for newly installed systems, with PHP 7 to be added soon.

**Comment by pricejn2** [comment]
Yes, this would be great. I'm only running 5.6 and 7 now (as defined in `.barracuda.cnf` and all `.*.octopus.cnf`) but upgrades still rebuild any previously installed PHP versions which adds a lot of unnecessary time (5.3, 5.4, and 5.5).

**Comment by omega8cc** [comment]
@pricejn2 -- For a quick workaround, if you have already removed not used versions from .barracuda.cnf, do something like this:

mv -f /opt/php53/bin/php /opt/php53/bin/.old.php
mv -f /opt/php54/bin/php /opt/php54/bin/.old.php
mv -f /opt/php55/bin/php /opt/php55/bin/.old.php

This will stop barracuda from rebuilding these not used versions on upgrade.

We should automate this, perhaps.

**Comment by pricejn2** [comment]
Perfect, thanks for the simple workaround!

**Comment by petrowsky** [comment]
Leaving a follow up comment here for anyone who has been upgrading a box since the early days of BOA. I've been through sarge, wheezy and now jessie on the same box (yeah, crazy I know). While the comment above of moving the php binary will stop BOA from rebuilding, it doesn't remove the older versions from your system.

They will still be loaded if they're in your init dir (which they likely will be).

Only do the following if you know for 100% sure you don't want them running on your system. Here's an example of stopping php55 - it's the safer route than killing them off.

`service php55-fpm stop`
`mv /etc/init.d/php55-fpm /opt/php55/`

Note: I didn't kill everything off with rm within /opt/php55/ and I just moved the init script from /etc/inid.d/ to the folder where php55 is installed - just for safe keeping. You'll have to remember you did this as I have know idea what would happen if you re-added 5.5 to the .barracuda conf file.

As a precaution, you will also want to make sure than any domains not managed by aegir are using the right version of php. You could use this.

`grep -r 'fastcgi_pass' /var/aegir/config/server_master/nginx/*`

If you find anything running under the version you're disabling, you best switch it to the one that is. ;)

The output might look like this.

`unix:/var/run/www55.fpm.socket`

Where you need to change to the www56.fpm.socket or www70. (as of this writing)

Hope this helps someone else out and I'm sure @omega8cc will correct any of my errors.

**Comment by omega8cc** [comment]
We are automatically disabling deprecated versions now, but we will not disable/remove if you remove supported version manually from `.barracuda.cnf` -- this file and the list of PHP versions in it is modified automatically via upgrade script (`barracuda`) if you change the mode with arguments on the fly, like switching to single-version from multi-version, but we shouldn't remove/disable any version based on manual edits of this file. Adding new -- yes, but removing is just not something we ever want to do, unless it's related to deprecated versions. Perhaps we could implement separate `cleanup` script for this purpose, with triple checks and warnings etc.
