### ISSUE TITLE
Sites automatically available over SSL

### ISSUE THREAD

**Issue by kazdegroot** [omega8cc/boa#826]
All the sites on my BOA server seem accessible through https, even though encryption on them is disabled. I can't find any other settings relating to ssl, and the documentation in docs/SSL.txt only seems to reference a SNI proxy setup either than normal Drupal sites served through octopus. 

This is kind of annoying, as these ssl sites are showing up in search results, with a self-signed, domain mismatched certificate once you try to visit them.

Is there any way/setting to prevent this? (preferably without getting every site their own certificate)

**Comment by omega8cc** [comment]
This is a feature and can't be disabled. Also, in the near future it should be easy (and free) to create valid certs per site, if needed.

**Comment by EdNett** [comment]
Hello,  Thank you for your comment, Omega8. Would you please shed some light on who is going to be providing free ssl certificates, and when? We would like to be a Certificate Authority so that the certificates we create are recognized by the major browsers. Do you have any advice about how to do this (we realize it is a non-BOA issue, but it relates to hosting).

Thank you.

**Comment by omega8cc** [comment]
It is discussed in https://github.com/omega8cc/boa/issues/500
