### ISSUE TITLE
SSH keys error

### ISSUE THREAD

**Issue by moglesby** [omega8cc/boa#844]
I attempted to upgrade instance and received following:
*****
ERROR: BOA requires working SSH keys for system root present
ERROR: Please add and test your SSH keys for root account
ERROR: before trying again
Bye
****
I regenerated my keys and successfully tested using 
ssh-keygen -y

Any suggestions would be greatly appreciated.

Thanks,
Mark

**Comment by angel0d** [comment]
@moglesby you need you personal public key in /root/.authorized_keys in order to be able to login without using a password

you need to test that you can login without a password before proceeding

**Comment by moglesby** [comment]
@angel0d, thanks for your response. 

I am attempting to upgrade my BOA instance. I login using ssh with a limited account and then use "sudo -i" to use the root account. This is the way the install script set-up the instance and the best practice for security (where sshd_config contains the line "PermitRootLogin no"). Is that not the case?

Thanks!
Mark

**Comment by omega8cc** [comment]
You can use `PermitRootLogin no` although `PermitRootLogin without-password` is better for most people, because it still allows you to access the system root remotely with your SSH keys only, in case anything happens to your unprivileged account.

That said, even if you always log in via unprivileged account, you must add your SSH key also to root, even if you will not use it, because BOA now requires it.
