### ISSUE TITLE
Remote SQL access on *development* environments

### ISSUE THREAD

**Issue by VangelisP** [omega8cc/boa#852]
Hi there! Great work done so far!

I have a question: Is there a way to activate remote MySQL access under very specific circumstances ? Eg. if environment is a development env, to have the ability to activate it on demand. 
It is painful and time consuming to do sql debugging via chive's query preview box.
For other MySQL (not in aegir), I'm using SquirrelSQL free software (under Ubuntu) and I connect to the remote SQLs to do test queries and/or debugging.

Thanks, in advance!

**Comment by bserem** [comment]
Opening the ports on the firewall should do the trick.

Also, if you can connect via an ssh connection (like redis desktop manager does) you'll be fine, without changing any configuration on the firewall.
Check if your app has ssh tuneling supported. I recall sql-workbench could do such things, but I'm not sure.

**Comment by omega8cc** [comment]
Correct, you can easily manage any database remotely with desktop client which supports SSH tunneling, as mentioned at: https://omega8.cc/how-to-use-chive-manager-323

There is no need to make 3306 port available publicly, plus, it would never work anyway, because db access grants are only for localhost, so you couldn't use them remotely via mysql port directly.
