### ISSUE TITLE
aegir_root db_passwd not updated in satellite instances

### ISSUE THREAD

**Issue by pricejn2** [omega8cc/boa#855]
When using FQDN for `_THIS_DB_HOST`, satellite instances connect as aegir_root instead of o1, o2, etc. On upgrade, the aegir_root password get's changed. However, only the master instance's hostmaster database gets updated with the new password.

During the barracuda upgrade: https://github.com/omega8cc/boa/blob/master/lib/functions/master.sh.inc#L139

But during the satellite upgrade, only the o1, o2, etc. users get updated even though the user isn't used in `/data/disk/o1/.drush/server_master.alias.drushrc.php` and doesn't exist in the `hosting_db_server` table:
https://github.com/omega8cc/boa/blob/master/lib/functions/satellite.sh.inc#L1902

This causes octopus upgrades to fail because the satellite instance is verified with the expired aegir_root password.

**Comment by pricejn2** [comment]
After reviewing barracuda_log.txt, this issue appears to be a problem with REMOTE db host not FQDN since FQDN db host should still be using o1, o2, etc. - https://github.com/omega8cc/boa/blob/master/lib/functions/satellite.sh.inc#L1841

barracuda_log.txt
```
Fri Oct 2 16:08:19 EDT 2015 / Debian.wheezy x86_64 XEN / Aegir BOA-2.4.6 / Barracuda BOA-2.4.6 / Nginx 1.9.4 / PHP-MI 5.6 / PHP-SE / FPM 5.6 / CLI 5.6 / MariaDB-10.0.21 REMOTE
Sat Oct 3 14:54:48 EDT 2015 / Debian.wheezy x86_64 XEN / Aegir BOA-2.4.6 / Barracuda BOA-2.4.6 / Nginx 1.9.4 / PHP-MI 5.6 / PHP-SE / FPM 5.6 / CLI 5.6 / MariaDB-10.0.21 FQDN
Mon Oct 5 19:48:58 PDT 2015 / Debian.wheezy x86_64 XEN / Aegir BOA-2.4.6 / Barracuda BOA-2.4.6 / Nginx 1.9.4 / PHP-MI 5.6 / PHP-SE / FPM 5.6 / CLI 5.6 / MariaDB-10.0.21 FQDN
Mon Jan 18 05:00:54 PST 2016 / Debian.wheezy x86_64 XEN / Aegir BOA-2.4.7 / Barracuda BOA-2.4.7 / Nginx 1.9.7 / PHP-MI 5.6 / PHP-SE / FPM 5.6 / CLI 5.6 / MariaDB-10.0.23 REMOTE
```

**Comment by pricejn2** [comment]
Nonetheless, when aegir_root is used as the db user for satellite instances, there is a password mismatch after upgrading the master instance.

**Comment by omega8cc** [comment]
The same user is used by design on cluster-specific installs only. Not sure how you have triggered this on your system?

BTW, the FQDN mode is not really supported for a long time for non-cluster installs, and thus not tested by default, because Aegir by default switched to localhost mode a long time ago, and all grants should be updated accordingly. The REMOTE mode is not designed to be used for normal installs, and should be active only on cluster based installs.

That said, please attach complete barracuda and octopus config files for review.

**Comment by omega8cc** [comment]
By the way, `aegir_root` doesn't exist on any Octopus instance, it is Master instance specific/only.

**Comment by pricejn2** [comment]
I was testing BOA clusters some time back and must have inadvertently used it for this particular server.

Good to know about FQDN support. I had used it as an interim solution while waiting for BOA clusters #502 to (hopefully) come to mainstream.

https://github.com/omega8cc/boa/blob/master/lib/functions/satellite.sh.inc#L1849 looked like there could be conditions when `aegir_root` is used as the satellite db user. If not, then this is a "my fault" situation that doesn't need addressed by BOA at large.

**Comment by omega8cc** [comment]
Yes, shared across cluster heads `aegir_root` *is* used in Octopus when in the cluster mode instead of usual Octopus instance-specific sql user.

It is not a good idea to test cluster and then use one of its nodes as a standalone system, though. There will be special control files left which will affect the system behaviour and cause confusion.
