### ISSUE TITLE
drupal_fast_404() missing from settings.php

### ISSUE THREAD

**Issue by bserem** [omega8cc/boa#910]
I compared the settings.php file in D7 core with the one provided by BOA in a new site and I found out that the lines about D7core handling of 404 errors are not there.

Lines 487 to 526 from here:
http://cgit.drupalcode.org/drupal/tree/sites/default/default.settings.php?h=7.x#n487

I found no documendation about their absence either. Is it something that has been removed from BOA on purpose?
I know that fast_404 module is out there, and it is on my watchlist too, but I thought about going with Core first.

Thanks in advance

**Comment by omega8cc** [comment]
It was never used in Aegir / Provision template for `settings.php` and thus is not used in BOA. Furthermore, in Nginx based Aegir / BOA this core feature is useless, because all requests listed in `404_fast_paths` are always served via Nginx directly anyway, with no Drupal backend involved at all, while all requests whitelisted in `404_fast_paths_exclude` also check is there is already the static files generated to server directly, and forward the request to Drupal only if needed. This BOA/ Aegir with Nginx has the same (and better) behaviour already built-in, on the web server configuration level, so there is no point in duplicating this on the PHP / Drupal level, because Nginx displays its own `404_fast_html` error page.
