### ISSUE TITLE
Best practice for complete BOA server backup plus automatic hostmaster and sites backup

### ISSUE THREAD

**Issue by Corvalan** [omega8cc/boa#918]
What would be a good way to backup a complete debian BOA server, and also backup Aegir with its sites automatically?

**Comment by omega8cc** [comment]
There is no reason for "complete backup" because this kind of backup (often offered by VPS providers) doesn't allow you to recover elsewhere. All essential files, databases and configurations you can use to recreate BOA system anywhere, on a fresh BOA system, can be backed up via backboa tool: https://github.com/omega8cc/boa/blob/master/docs/BACKUPS.txt

We plan to extend it, so it allow to automate recovery procedure.

**Comment by Corvalan** [comment]
Backboa is a great tool!  But it needs a fresh BOA system to restore files. Installing a fresh BOA system takes time.  What are the folders in Debian 8 that the BOA installation adds or changes? A restore of those folders would be quicker.

**Comment by omega8cc** [comment]
Please check docs/BACKUPS.txt -- all backed up directories are listed at the top. It basically creates a "complete" backup of all BOA specific data and files, minus the system part. You can't avoid the fresh BOA install procedure on another server to actually start recovery process (which is currently a manual process)

**Comment by Corvalan** [comment]
I see that the backup files are collected in one folder, in amazons3 like this, wouldn't it be better to make duplicity store it in folders or zipfile per backup?
![amazons3](https://cloud.githubusercontent.com/assets/8040352/15277155/177a62b4-1ad2-11e6-8d3e-ba5d58af94c5.png)

**Comment by omega8cc** [comment]
No, there is no point in modifying how encrypted backups chunks are stored withing bucket. You can't use them without duplicity / backboa anyway.
