### ISSUE TITLE
INFO: Restoring a backup before a migration to another platform restores it to the new platform.

### ISSUE THREAD

**Issue by bserem** [omega8cc/boa#958]
BOA takes automatic backups before a migration (thanks for that!) of a site to another platform.
However, by selecting to restore this backup (from the Aegir UI) the resulting site will be again on the new platform, and not the original one.

I suppose this is an Aegir issue of course, but I'm mentioning it here.
Is this how it supposed to happen?

**Comment by omega8cc** [comment]
This is by design, and is normal. 

Aegir *rollback* procedure moves the site *back* to the old platform if anything goes wrong during migration, but once the site is *migrated*, you can't use the backup feature to move it back to the old codebase, because backups are attached to the site and not the platform, plus, Aegir doesn't support downgrade attempts, which is to be expected.

**Comment by omega8cc** [comment]
We have mentioned this in the docs: https://omega8.cc/your-drupal-site-upgrade-safe-workflow-298

**Comment by bserem** [comment]
Thanks!
