### ISSUE TITLE
Let's Encrypt SSL - switching from demo to live

### ISSUE THREAD

**Issue by ar-jan** [omega8cc/boa#959]
First of, great work on implementing Let's Encrypt! It's an awesome feature to have built-in to BOA.

It seems switching from demo to live mode needs some more work. I enabled SSL on a site while in demo mode, and it generated a certificate with the "Fake LE Intermediate X1" CA as expected. Then I switched to live mode and re-verified the site. I see in the verify log that the actual LE certificate has been generated, but the site still uses the earlier fake cert. It's not a browser cache issue.

**Comment by omega8cc** [comment]
Sounds like a regression.. Thanks for the heads-up!

**Comment by omega8cc** [comment]
Fixed (in head and stable) with:

https://github.com/omega8cc/hosting_le/commit/95e5ef6429aa418828f61ed80cd6fde0d796c1d9
https://github.com/omega8cc/hosting_le/commit/0fa26cae656ac8abc8d775bafbcc9b5249a5f993
https://github.com/omega8cc/hosting_le/commit/3141035c327f820cef5dfa10c5d9f13a60ec1027
https://github.com/omega8cc/hosting_le/commit/c6a852c752d65110e65e4842ec798934d8280b82

**Comment by omega8cc** [comment]
The problem was that `letsencrypt.sh` doesn't force certificate renewal if you switch the mode, but you don't modify aliases or redirections, which could trigger the forced mode, so we had to add some extra dance with control files to properly detect expected mode and force renewal per site, if needed.
