### ISSUE TITLE
elysia_cron exception for cron protection

### ISSUE THREAD

**Issue by pricejn2** [omega8cc/boa#985]
Hello,

Should there be an elysia_cron exception for cron protection in https://github.com/omega8cc/boa/blob/master/aegir/conf/global.inc#L98 ?

Thanks!

**Comment by omega8cc** [comment]
There is no need for anything `elysia_cron` specific in this protection, because it is run via `/cron.php` request anyway. The `elysia_cron` module doesn't require any dedicated .php file -- at least in BOA we don't use its replacement for cron.php anywhere.

**Comment by pricejn2** [comment]
True, `elysia-cron` is available directly through `drush`. That being said, it would be nice to be able to hit `http://www.example.com/sites/all/modules/elysia_cron/cron.php?cron_key=12345678` directly without a 404.

**Comment by omega8cc** [comment]
How would you like to hit such URL? Remotely? Bad idea. If you want to use `elysia_cron` locally, then switch cron method to Drush from Wget (BOA default). It will run `drush elysia-cron` for you.

**Comment by pricejn2** [comment]
> If you want to use elysia_cron locally, then switch cron method to Drush from Wget (BOA default). It will run drush elysia-cron for you.

Wow, did not know that! That is perfect. Thank you.

**Comment by omega8cc** [comment]
Plus, don't confuse two separate protections. That from `global.inc` is to avoid running cron on dev/tmp sites, while `/cron.php` is protected on the Nginx level and available only for local requests, so it can't be hit remotely. We don't protect paths like /sites/all/modules/elysia_cron/cron.php from remote hits like this, but they would not work anyway, because only whitelisted .php files are allowed in BOA.

**Comment by pricejn2** [comment]
Ah, of course. Thank you for clarifying and keeping me honest.

**Comment by pricejn2** [comment]
For others that stumble upon this issue, the Cron method setting of Drush will get reverted to Wget by `daily.sh` unless `hosting_cron_use_backend.txt` exists at `${User}/log/hosting_cron_use_backend.txt`
